# Sundays of Advent

In [1]:
import pycantus
import pycantus.data as data
from pycantus.filtration import Filter
import copy
import utils
import importlib

In [2]:
corpus = data.load_dataset('cantuscorpus_v1.0')

Loading chants and sources...
Data loaded!

In [3]:
n_chants = len(corpus.chants)
print(f'Number of chants in CantusCorpus v1.0: {n_chants}')
n_sources = len(corpus.sources)
print(f'Number of sources in CantusCorpus v1.0: {n_sources}')

Number of chants in CantusCorpus v1.0: 888010
Number of sources in CantusCorpus v1.0: 2278

In [4]:
# Clean the corpus
# Drop doxology
doxo_filter = pycantus.filtration.Filter('doxo_filter')
doxo_filter.add_value_exclude('cantus_id', '909000')
corpus.apply_filter(doxo_filter)

# Drop fragments => sources with less than 100 chants
corpus.drop_small_sources_data(min_chants=100)

In [5]:
n_chants = len(corpus.chants)
print(f'Number of chants in CantusCorpus v1.0: {n_chants}')
n_sources = len(corpus.sources)
print(f'Number of sources in CantusCorpus v1.0: {n_sources}')

Number of chants in CantusCorpus v1.0: 855146
Number of sources in CantusCorpus v1.0: 510

In [6]:
sigla_dict = {source.srclink: source.siglum for source in corpus.sources}

### Complete days

In [7]:
ADVENT_FEASTS = [[f'Dom. {i} Adventus', f"Adventus, dom. {i}"] for i in range(1, 5)] 
ADVENT_FEASTS += [['Nativitas Domini'], ['Vigilia Nat. Domini', 'Nativitas Domini, vig.']]

In [8]:
# Build corpora for whole days
advent_corpora = {}
for feast in ADVENT_FEASTS:
    feast_corpus = copy.deepcopy(corpus)
    feast_filter = Filter(f'{feast[0]}_filter')
    feast_filter.add_value_include('feast', list(feast))
    feast_corpus.apply_filter(feast_filter)
    feast_corpus.drop_empty_sources()
    advent_corpora[feast[0]] = feast_corpus
    print(f'{feast[0]}: {len(feast_corpus.chants)} chants, {len(feast_corpus.sources)} sources')

Dom. 1 Adventus: 6684 chants, 255 sources
Dom. 2 Adventus: 4721 chants, 249 sources
Dom. 3 Adventus: 5069 chants, 260 sources
Dom. 4 Adventus: 4841 chants, 260 sources
Nativitas Domini: 14625 chants, 334 sources
Vigilia Nat. Domini: 4657 chants, 261 sources

In [9]:
# Bulit copora for advent sundays Lauds only
advent_sundays_lauds_corpora = {}
lauds_filter = Filter(f'lauds_filter')
for feast in ADVENT_FEASTS:
    feast_corpus = copy.deepcopy(advent_corpora[feast[0]])
    lauds_filter.add_value_include('office', 'L')
    feast_corpus.apply_filter(lauds_filter)
    feast_corpus.drop_empty_sources()
    advent_sundays_lauds_corpora[feast[0]] = feast_corpus
    print(f'{feast[0]} Lauds: {len(feast_corpus.chants)} chants, {len(feast_corpus.sources)} sources')

Dom. 1 Adventus Lauds: 859 chants, 106 sources
Dom. 2 Adventus Lauds: 668 chants, 100 sources
Dom. 3 Adventus Lauds: 708 chants, 109 sources
Dom. 4 Adventus Lauds: 744 chants, 115 sources
Nativitas Domini Lauds: 1150 chants, 128 sources
Vigilia Nat. Domini Lauds: 833 chants, 116 sources

In [10]:
# Corpora for vespers only
advent_sundays_vespers_corpora = {}

for feast in ADVENT_FEASTS:
    feast_name = feast[0]

    feast_corpus = copy.deepcopy(advent_corpora[feast_name])

    vespers_filter = Filter(f'{feast_name}_vespers_filter')
    vespers_filter.add_value_include('office', 'V')

    feast_corpus.apply_filter(vespers_filter)
    feast_corpus.drop_empty_sources()

    advent_sundays_vespers_corpora[feast_name] = feast_corpus
    print(f'{feast_name} Vespers: {len(feast_corpus.chants)} chants, {len(feast_corpus.sources)} sources')

Dom. 1 Adventus Vespers: 505 chants, 114 sources
Dom. 2 Adventus Vespers: 249 chants, 94 sources
Dom. 3 Adventus Vespers: 302 chants, 102 sources
Dom. 4 Adventus Vespers: 230 chants, 102 sources
Nativitas Domini Vespers: 693 chants, 125 sources
Vigilia Nat. Domini Vespers: 279 chants, 89 sources

In [11]:
# Corpora for second vespers only
advent_sundays_second_vespers_corpora = {}

for feast in ADVENT_FEASTS:
    feast_name = feast[0]

    feast_corpus = copy.deepcopy(advent_corpora[feast_name])

    second_vespers_filter = Filter(f'{feast_name}_second_vespers_filter')
    second_vespers_filter.add_value_include('office', 'V2')

    feast_corpus.apply_filter(second_vespers_filter)
    feast_corpus.drop_empty_sources()

    advent_sundays_second_vespers_corpora[feast_name] = feast_corpus
    print(f'{feast_name} Second Vespers: {len(feast_corpus.chants)} chants, {len(feast_corpus.sources)} sources')

Dom. 1 Adventus Second Vespers: 365 chants, 99 sources
Dom. 2 Adventus Second Vespers: 249 chants, 94 sources
Dom. 3 Adventus Second Vespers: 241 chants, 96 sources
Dom. 4 Adventus Second Vespers: 172 chants, 82 sources
Nativitas Domini Second Vespers: 1032 chants, 142 sources
Vigilia Nat. Domini Second Vespers: 386 chants, 68 sources

In [12]:
# Corpora for matins only
advent_sundays_matins_corpora = {}

for feast in ADVENT_FEASTS:
    feast_name = feast[0]

    feast_corpus = copy.deepcopy(advent_corpora[feast_name])

    matins_filter = Filter(f'{feast_name}_matins_filter')
    matins_filter.add_value_include('office', 'M')

    feast_corpus.apply_filter(matins_filter)
    feast_corpus.drop_empty_sources()

    advent_sundays_matins_corpora[feast_name] = feast_corpus
    print(f'{feast_name} Matins: {len(feast_corpus.chants)} chants, {len(feast_corpus.sources)} sources')

Dom. 1 Adventus Matins: 2967 chants, 121 sources
Dom. 2 Adventus Matins: 2160 chants, 111 sources
Dom. 3 Adventus Matins: 2445 chants, 121 sources
Dom. 4 Adventus Matins: 2389 chants, 125 sources
Nativitas Domini Matins: 4851 chants, 170 sources
Vigilia Nat. Domini Matins: 1485 chants, 125 sources

### Networks

In [13]:
import networkx as nx

In [14]:
advent_nets = {}

for feast, feast_corpus in advent_corpora.items():
    G = utils.build_feast_network(feast_corpus, feast)
    advent_nets[feast] = G

    print(f'{feast}: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')

    nx.write_edgelist(G, f'nets/{feast}_network.edgelist')

Dom. 1 Adventus: 255 nodes, 14906 edges
Dom. 2 Adventus: 249 nodes, 14393 edges
Dom. 3 Adventus: 260 nodes, 15034 edges
Dom. 4 Adventus: 260 nodes, 15142 edges
Nativitas Domini: 334 nodes, 25374 edges
Vigilia Nat. Domini: 261 nodes, 16121 edges

In [15]:
advent_lauds_nets = {}

for feast, feast_corpus in advent_sundays_lauds_corpora.items():
    G = utils.build_feast_network(feast_corpus, feast)
    advent_lauds_nets[feast] = G

    print(f'{feast} Lauds: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')

    nx.write_edgelist(G, f'nets/{feast}_lauds_network.edgelist')

Dom. 1 Adventus Lauds: 106 nodes, 5031 edges
Dom. 2 Adventus Lauds: 100 nodes, 4698 edges
Dom. 3 Adventus Lauds: 109 nodes, 5260 edges
Dom. 4 Adventus Lauds: 115 nodes, 5829 edges
Nativitas Domini Lauds: 128 nodes, 7404 edges
Vigilia Nat. Domini Lauds: 116 nodes, 6069 edges

In [16]:
advent_vespers_nets = {}

for feast, feast_corpus in advent_sundays_vespers_corpora.items():
    G = utils.build_feast_network(feast_corpus, feast)
    advent_vespers_nets[feast] = G

    print(f'{feast} Vespers: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')

    nx.write_edgelist(G, f'nets/{feast}_vespers_network.edgelist')

Dom. 1 Adventus Vespers: 114 nodes, 4236 edges
Dom. 2 Adventus Vespers: 94 nodes, 1154 edges
Dom. 3 Adventus Vespers: 102 nodes, 2421 edges
Dom. 4 Adventus Vespers: 102 nodes, 1128 edges
Nativitas Domini Vespers: 125 nodes, 2072 edges
Vigilia Nat. Domini Vespers: 89 nodes, 1117 edges

In [17]:
advent_vespers2_nets = {}

for feast, feast_corpus in advent_sundays_second_vespers_corpora.items():
    G = utils.build_feast_network(feast_corpus, feast)
    advent_vespers2_nets[feast] = G

    print(f'{feast} Second Vespers: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')

    nx.write_edgelist(G, f'nets/{feast}_second_vespers_network.edgelist')

Dom. 1 Adventus Second Vespers: 99 nodes, 3349 edges
Dom. 2 Adventus Second Vespers: 94 nodes, 2417 edges
Dom. 3 Adventus Second Vespers: 96 nodes, 1770 edges
Dom. 4 Adventus Second Vespers: 82 nodes, 453 edges
Nativitas Domini Second Vespers: 142 nodes, 6403 edges
Vigilia Nat. Domini Second Vespers: 68 nodes, 1261 edges

In [18]:
advent_matins_nets = {}

for feast, feast_corpus in advent_sundays_matins_corpora.items():
    G = utils.build_feast_network(feast_corpus, feast)
    advent_matins_nets[feast] = G

    print(f'{feast} Matins: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')

    nx.write_edgelist(G, f'nets/{feast}_matins_network.edgelist')

Dom. 1 Adventus Matins: 121 nodes, 5618 edges
Dom. 2 Adventus Matins: 111 nodes, 5078 edges
Dom. 3 Adventus Matins: 121 nodes, 5694 edges
Dom. 4 Adventus Matins: 125 nodes, 6559 edges
Nativitas Domini Matins: 170 nodes, 9215 edges
Vigilia Nat. Domini Matins: 125 nodes, 6728 edges

In [19]:
for G in advent_nets.values():
    utils.graph_info_nx(G, fast = False)
    print("--------------------------------")

       Graph | 'Dom. 1 Adventus'
       Nodes | 255 (3)
       Edges | 14,906 (0)
      Degree | 116.91 (237)
  Components | 97.6% (5)
  Clustering | 0.9437
Modularity from Louvain | 0.4224 (6)

--------------------------------
       Graph | 'Dom. 2 Adventus'
       Nodes | 249 (0)
       Edges | 14,393 (0)
      Degree | 115.61 (239)
  Components | 98.8% (2)
  Clustering | 0.9762
Modularity from Louvain | 0.4033 (4)

--------------------------------
       Graph | 'Dom. 3 Adventus'
       Nodes | 260 (1)
       Edges | 15,034 (0)
      Degree | 115.65 (242)
  Components | 97.3% (4)
  Clustering | 0.9617
Modularity from Louvain | 0.4331 (7)

--------------------------------
       Graph | 'Dom. 4 Adventus'
       Nodes | 260 (0)
       Edges | 15,142 (0)
      Degree | 116.48 (246)
  Components | 98.5% (2)
  Clustering | 0.9658
Modularity from Louvain | 0.4948 (4)

--------------------------------
       Graph | 'Nativitas Domini'
       Nodes | 334 (2)
       Edges | 25,374 (0)
      Degree | 151.94 (294)
  Components | 99.4% (3)
  Clustering | 0.8934
Modularity from Louvain | 0.4591 (7)

--------------------------------
       Graph | 'Vigilia Nat. Domini'
       Nodes | 261 (3)
       Edges | 16,121 (0)
      Degree | 123.53 (251)
  Components | 98.1% (5)
  Clustering | 0.9556
Modularity from Louvain | 0.4263 (6)

--------------------------------

In [20]:
for G in advent_lauds_nets.values():
    utils.graph_info_nx(G, fast = False)
    print("--------------------------------")

       Graph | 'Dom. 1 Adventus'
       Nodes | 106 (0)
       Edges | 5,031 (0)
      Degree | 94.92 (103)
  Components | 100.0% (1)
  Clustering | 0.9650
Modularity from Louvain | 0.0331 (3)

--------------------------------
       Graph | 'Dom. 2 Adventus'
       Nodes | 100 (0)
       Edges | 4,698 (0)
      Degree | 93.96 (99)
  Components | 100.0% (1)
  Clustering | 0.9665
Modularity from Louvain | 0.0407 (3)

--------------------------------
       Graph | 'Dom. 3 Adventus'
       Nodes | 109 (1)
       Edges | 5,260 (0)
      Degree | 96.51 (106)
  Components | 99.1% (2)
  Clustering | 0.9568
Modularity from Louvain | 0.0451 (4)

--------------------------------
       Graph | 'Dom. 4 Adventus'
       Nodes | 115 (0)
       Edges | 5,829 (0)
      Degree | 101.37 (112)
  Components | 100.0% (1)
  Clustering | 0.9611
Modularity from Louvain | 0.0447 (2)

--------------------------------
       Graph | 'Nativitas Domini'
       Nodes | 128 (2)
       Edges | 7,404 (0)
      Degree | 115.69 (123)
  Components | 98.4% (3)
  Clustering | 0.9795
Modularity from Louvain | 0.0289 (6)

--------------------------------
       Graph | 'Vigilia Nat. Domini'
       Nodes | 116 (1)
       Edges | 6,069 (0)
      Degree | 104.64 (112)
  Components | 99.1% (2)
  Clustering | 0.9652
Modularity from Louvain | 0.0704 (4)

--------------------------------

In [21]:
for G in advent_vespers_nets.values():
    utils.graph_info_nx(G, fast = False)
    print("--------------------------------")

       Graph | 'Dom. 1 Adventus'
       Nodes | 114 (3)
       Edges | 4,236 (0)
      Degree | 74.32 (102)
  Components | 95.6% (5)
  Clustering | 0.8720
Modularity from Louvain | 0.1326 (9)

--------------------------------
       Graph | 'Dom. 2 Adventus'
       Nodes | 94 (6)
       Edges | 1,154 (0)
      Degree | 24.55 (53)
  Components | 93.6% (7)
  Clustering | 0.7039
Modularity from Louvain | 0.3521 (10)

--------------------------------
       Graph | 'Dom. 3 Adventus'
       Nodes | 102 (3)
       Edges | 2,421 (0)
      Degree | 47.47 (81)
  Components | 95.1% (5)
  Clustering | 0.8410
Modularity from Louvain | 0.2083 (8)

--------------------------------
       Graph | 'Dom. 4 Adventus'
       Nodes | 102 (10)
       Edges | 1,128 (0)
      Degree | 22.12 (62)
  Components | 90.2% (11)
  Clustering | 0.7186
Modularity from Louvain | 0.3291 (15)

--------------------------------
       Graph | 'Nativitas Domini'
       Nodes | 125 (12)
       Edges | 2,072 (0)
      Degree | 33.15 (78)
  Components | 90.4% (13)
  Clustering | 0.7095
Modularity from Louvain | 0.3019 (20)

--------------------------------
       Graph | 'Vigilia Nat. Domini'
       Nodes | 89 (4)
       Edges | 1,117 (0)
      Degree | 25.10 (62)
  Components | 93.3% (6)
  Clustering | 0.7207
Modularity from Louvain | 0.3997 (10)

--------------------------------

In [22]:
for G in advent_matins_nets.values():
    utils.graph_info_nx(G, fast = False)
    print("--------------------------------")

       Graph | 'Dom. 1 Adventus'
       Nodes | 121 (4)
       Edges | 5,618 (0)
      Degree | 92.86 (112)
  Components | 95.0% (6)
  Clustering | 0.8912
Modularity from Louvain | 0.1025 (8)

--------------------------------
       Graph | 'Dom. 2 Adventus'
       Nodes | 111 (1)
       Edges | 5,078 (0)
      Degree | 91.50 (106)
  Components | 99.1% (2)
  Clustering | 0.9586
Modularity from Louvain | 0.1089 (5)

--------------------------------
       Graph | 'Dom. 3 Adventus'
       Nodes | 121 (0)
       Edges | 5,694 (0)
      Degree | 94.12 (112)
  Components | 98.3% (2)
  Clustering | 0.9430
Modularity from Louvain | 0.1029 (7)

--------------------------------
       Graph | 'Dom. 4 Adventus'
       Nodes | 125 (0)
       Edges | 6,559 (0)
      Degree | 104.94 (120)
  Components | 100.0% (1)
  Clustering | 0.9698
Modularity from Louvain | 0.0883 (3)

--------------------------------
       Graph | 'Nativitas Domini'
       Nodes | 170 (9)
       Edges | 9,215 (0)
      Degree | 108.41 (142)
  Components | 89.4% (12)
  Clustering | 0.8794
Modularity from Louvain | 0.0470 (17)

--------------------------------
       Graph | 'Vigilia Nat. Domini'
       Nodes | 125 (3)
       Edges | 6,728 (0)
      Degree | 107.65 (120)
  Components | 97.6% (4)
  Clustering | 0.9318
Modularity from Louvain | 0.0672 (8)

--------------------------------

In [23]:
for G in advent_vespers2_nets.values():
    utils.graph_info_nx(G, fast = False)
    print("--------------------------------")

       Graph | 'Dom. 1 Adventus'
       Nodes | 99 (2)
       Edges | 3,349 (0)
      Degree | 67.66 (88)
  Components | 96.0% (4)
  Clustering | 0.8859
Modularity from Louvain | 0.1274 (8)

--------------------------------
       Graph | 'Dom. 2 Adventus'
       Nodes | 94 (4)
       Edges | 2,417 (0)
      Degree | 51.43 (77)
  Components | 95.7% (5)
  Clustering | 0.8729
Modularity from Louvain | 0.1454 (9)

--------------------------------
       Graph | 'Dom. 3 Adventus'
       Nodes | 96 (3)
       Edges | 1,770 (0)
      Degree | 36.88 (71)
  Components | 94.8% (5)
  Clustering | 0.8145
Modularity from Louvain | 0.3225 (9)

--------------------------------
       Graph | 'Dom. 4 Adventus'
       Nodes | 82 (6)
       Edges | 453 (0)
      Degree | 11.05 (31)
  Components | 92.7% (7)
  Clustering | 0.7563
Modularity from Louvain | 0.5859 (14)

--------------------------------
       Graph | 'Nativitas Domini'
       Nodes | 142 (8)
       Edges | 6,403 (0)
      Degree | 90.18 (121)
  Components | 90.1% (11)
  Clustering | 0.8670
Modularity from Louvain | 0.0426 (14)

--------------------------------
       Graph | 'Vigilia Nat. Domini'
       Nodes | 68 (6)
       Edges | 1,261 (0)
      Degree | 37.09 (57)
  Components | 91.2% (7)
  Clustering | 0.8354
Modularity from Louvain | 0.2310 (11)

--------------------------------

In [24]:
# just a check
print("whole day:", len(advent_nets))
print("lauds:", len(advent_lauds_nets))
print("vespers:", len(advent_vespers_nets))
print("second vespers:", len(advent_vespers2_nets))
print("matins:", len(advent_matins_nets))

whole day: 6
lauds: 6
vespers: 6
second vespers: 6
matins: 6

In [25]:
THRESHOLDS = [0.0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

In [26]:
import pandas as pd
import itertools
importlib.reload(utils)

def compare_edgewise_networks(networks, thresholds):
    rows = []
    for feast1, feast2 in itertools.combinations(networks.keys(), 2):
        row = {'network_1': feast1, 'network_2': feast2}
        for threshold in thresholds:
            result = utils.compare_edge_overlap(networks[feast1], networks[feast2], threshold=threshold)
            row['edges_1'] = result['edges_1']
            row['edges_2'] = result['edges_2']
            row['shared_edges'] = result['shared_edges']
            row['edge_overlap_' + str(threshold)] = result[f'edge_overlap_{threshold}']
        rows.append(row)
    overlap_df = pd.DataFrame(rows)
    return overlap_df

In [27]:
comparison_df = compare_edgewise_networks(advent_nets, THRESHOLDS)
comparison_df

,network_1,network_2,edges_1,edges_2,shared_edges,edge_overlap_0.0,edge_overlap_0.2,edge_overlap_0.3,edge_overlap_0.4,edge_overlap_0.5,edge_overlap_0.6,edge_overlap_0.7,edge_overlap_0.8
0,Dom. 1 Adventus,Dom. 2 Adventus,1420,2248,970,0.886971,0.857684,0.776512,0.710637,0.683638,0.611587,0.542998,0.359526
1,Dom. 1 Adventus,Dom. 3 Adventus,1420,1324,621,0.826724,0.790774,0.732352,0.662654,0.628361,0.559563,0.442338,0.292511
2,Dom. 1 Adventus,Dom. 4 Adventus,1420,343,156,0.668962,0.614356,0.495844,0.352725,0.253537,0.167482,0.110042,0.097075
3,Dom. 1 Adventus,Nativitas Domini,1420,1351,509,0.504613,0.553858,0.505103,0.440384,0.406710,0.367373,0.294413,0.225022
4,Dom. 1 Adventus,Vigilia Nat. Domini,1420,1646,652,0.644163,0.634629,0.563112,0.484052,0.472877,0.426242,0.331242,0.270091
5,Dom. 2 Adventus,Dom. 3 Adventus,2248,1324,842,0.873973,0.832320,0.788814,0.755843,0.734998,0.633248,0.471647,0.308425
6,Dom. 2 Adventus,Dom. 4 Adventus,2248,343,193,0.712174,0.653522,0.516848,0.376577,0.271988,0.157420,0.102114,0.080484
7,Dom. 2 Adventus,Nativitas Domini,2248,1351,709,0.502626,0.551705,0.499207,0.451963,0.428132,0.391713,0.308165,0.245329
8,Dom. 2 Adventus,Vigilia Nat. Domini,2248,1646,817,0.661711,0.644559,0.575522,0.522388,0.513298,0.462530,0.349175,0.265518
9,Dom. 3 Adventus,Dom. 4 Adventus,1324,343,192,0.768090,0.693591,0.559757,0.386963,0.265094,0.172148,0.121980,0.130169
10,Dom. 3 Adventus,Nativitas Domini,1324,1351,464,0.526674,0.590236,0.543860,0.486610,0.444204,0.390684,0.320402,0.209860
11,Dom. 3 Adventus,Vigilia Nat. Domini,1324,1646,594,0.706002,0.671583,0.617668,0.548587,0.532727,0.474092,0.356043,0.250000
12,Dom. 4 Adventus,Nativitas Domini,343,1351,161,0.523788,0.560442,0.458243,0.307523,0.215627,0.132740,0.114602,0.105023
13,Dom. 4 Adventus,Vigilia Nat. Domini,343,1646,182,0.680445,0.630453,0.505631,0.337151,0.233595,0.140330,0.116661,0.100719
14,Nativitas Domini,Vigilia Nat. Domini,1351,1646,750,0.594000,0.720850,0.647286,0.597412,0.593325,0.521704,0.431897,0.333778

In [28]:
lauds_df = compare_edgewise_networks(advent_lauds_nets, THRESHOLDS)
lauds_df

,network_1,network_2,edges_1,edges_2,shared_edges,edge_overlap_0.0,edge_overlap_0.2,edge_overlap_0.3,edge_overlap_0.4,edge_overlap_0.5,edge_overlap_0.6,edge_overlap_0.7,edge_overlap_0.8
0,Dom. 1 Adventus,Dom. 2 Adventus,350,639,79,0.852790,0.828515,0.812290,0.734209,0.586284,0.377007,0.194241,0.086813
1,Dom. 1 Adventus,Dom. 3 Adventus,350,1170,110,0.789428,0.781441,0.780251,0.713279,0.613508,0.384204,0.188055,0.078014
2,Dom. 1 Adventus,Dom. 4 Adventus,350,781,84,0.697405,0.714665,0.711107,0.650280,0.548089,0.341237,0.189873,0.080229
3,Dom. 1 Adventus,Nativitas Domini,350,121,9,0.559639,0.518048,0.481696,0.349333,0.221221,0.111184,0.046898,0.019481
4,Dom. 1 Adventus,Vigilia Nat. Domini,350,104,12,0.653262,0.630035,0.573782,0.401494,0.222222,0.095051,0.054762,0.027149
5,Dom. 2 Adventus,Dom. 3 Adventus,639,1170,304,0.805948,0.782556,0.774959,0.724290,0.612075,0.439264,0.289277,0.201993
6,Dom. 2 Adventus,Dom. 4 Adventus,639,781,168,0.716732,0.741519,0.728409,0.667555,0.545989,0.353273,0.270825,0.134185
7,Dom. 2 Adventus,Nativitas Domini,639,121,23,0.534035,0.489788,0.462333,0.340404,0.221072,0.105445,0.053659,0.031208
8,Dom. 2 Adventus,Vigilia Nat. Domini,639,104,22,0.652394,0.627458,0.566347,0.404742,0.228593,0.110603,0.073529,0.030513
9,Dom. 3 Adventus,Dom. 4 Adventus,1170,781,206,0.777653,0.825068,0.826715,0.785647,0.704186,0.471707,0.293715,0.118052
10,Dom. 3 Adventus,Nativitas Domini,1170,121,26,0.622966,0.591561,0.564795,0.419188,0.267549,0.127057,0.046529,0.020553
11,Dom. 3 Adventus,Vigilia Nat. Domini,1170,104,44,0.715995,0.704890,0.650725,0.465192,0.255393,0.112421,0.061704,0.035772
12,Dom. 4 Adventus,Nativitas Domini,781,121,33,0.650206,0.634731,0.609883,0.458652,0.286891,0.146929,0.067326,0.037975
13,Dom. 4 Adventus,Vigilia Nat. Domini,781,104,31,0.736934,0.727856,0.655271,0.452834,0.227245,0.102987,0.061881,0.036300
14,Nativitas Domini,Vigilia Nat. Domini,121,104,11,0.740923,0.676754,0.573877,0.346050,0.157978,0.084636,0.076283,0.051402

In [29]:
vespers_df = compare_edgewise_networks(advent_vespers_nets, THRESHOLDS)
vespers_df

,network_1,network_2,edges_1,edges_2,shared_edges,edge_overlap_0.0,edge_overlap_0.2,edge_overlap_0.3,edge_overlap_0.4,edge_overlap_0.5,edge_overlap_0.6,edge_overlap_0.7,edge_overlap_0.8
0,Dom. 1 Adventus,Dom. 2 Adventus,34,33,0,0.233692,0.165603,0.096244,0.058405,0.042463,0.015625,0.010526,0.000000
1,Dom. 1 Adventus,Dom. 3 Adventus,34,44,0,0.353599,0.240270,0.124375,0.073227,0.041736,0.023697,0.008850,0.000000
2,Dom. 1 Adventus,Dom. 4 Adventus,34,37,0,0.151814,0.118734,0.072180,0.033613,0.028112,0.005495,0.010753,0.000000
3,Dom. 1 Adventus,Nativitas Domini,34,23,1,0.224141,0.101816,0.059835,0.025862,0.012077,0.005618,0.011364,0.017857
4,Dom. 1 Adventus,Vigilia Nat. Domini,34,78,0,0.136277,0.096810,0.046073,0.032345,0.024621,0.000000,0.000000,0.000000
5,Dom. 2 Adventus,Dom. 3 Adventus,33,44,1,0.262359,0.193831,0.114058,0.090764,0.075510,0.097403,0.062500,0.013158
6,Dom. 2 Adventus,Dom. 4 Adventus,33,37,1,0.186687,0.129420,0.091021,0.065934,0.064103,0.030303,0.012346,0.014493
7,Dom. 2 Adventus,Nativitas Domini,33,23,0,0.119750,0.098394,0.054022,0.042986,0.035370,0.007634,0.013158,0.000000
8,Dom. 2 Adventus,Vigilia Nat. Domini,33,78,1,0.145234,0.113768,0.072243,0.053388,0.044706,0.036364,0.008264,0.009091
9,Dom. 3 Adventus,Dom. 4 Adventus,44,37,0,0.228878,0.172076,0.107759,0.067504,0.055877,0.032895,0.000000,0.000000
10,Dom. 3 Adventus,Nativitas Domini,44,23,0,0.163086,0.089836,0.048480,0.017054,0.006637,0.013245,0.010638,0.000000
11,Dom. 3 Adventus,Vigilia Nat. Domini,44,78,1,0.118205,0.080139,0.054237,0.035088,0.030357,0.032258,0.014493,0.008264
12,Dom. 4 Adventus,Nativitas Domini,37,23,1,0.088806,0.070566,0.043931,0.020134,0.011799,0.008403,0.013514,0.016949
13,Dom. 4 Adventus,Vigilia Nat. Domini,37,78,1,0.096191,0.075562,0.058323,0.034623,0.031042,0.012739,0.016949,0.008772
14,Nativitas Domini,Vigilia Nat. Domini,23,78,1,0.079553,0.064808,0.044848,0.021097,0.013624,0.006494,0.008772,0.010000

In [30]:
vespers2_df = compare_edgewise_networks(advent_vespers2_nets, THRESHOLDS)
vespers2_df

,network_1,network_2,edges_1,edges_2,shared_edges,edge_overlap_0.0,edge_overlap_0.2,edge_overlap_0.3,edge_overlap_0.4,edge_overlap_0.5,edge_overlap_0.6,edge_overlap_0.7,edge_overlap_0.8
0,Dom. 1 Adventus,Dom. 2 Adventus,41,195,4,0.472421,0.326469,0.190296,0.127273,0.098958,0.053571,0.016064,0.017241
1,Dom. 1 Adventus,Dom. 3 Adventus,41,92,2,0.353159,0.229108,0.120201,0.078091,0.068215,0.057143,0.013245,0.015267
2,Dom. 1 Adventus,Dom. 4 Adventus,41,40,0,0.084427,0.073725,0.032206,0.018310,0.013780,0.023256,0.020408,0.000000
3,Dom. 1 Adventus,Nativitas Domini,41,121,1,0.400144,0.226385,0.130297,0.082308,0.054651,0.023828,0.019531,0.006211
4,Dom. 1 Adventus,Vigilia Nat. Domini,41,40,0,0.127691,0.064490,0.041026,0.034525,0.042553,0.049751,0.017857,0.000000
5,Dom. 2 Adventus,Dom. 3 Adventus,195,92,10,0.499105,0.399646,0.235142,0.147271,0.131550,0.060423,0.035714,0.036101
6,Dom. 2 Adventus,Dom. 4 Adventus,195,40,0,0.087533,0.070560,0.030612,0.023058,0.020566,0.019011,0.000000,0.000000
7,Dom. 2 Adventus,Nativitas Domini,195,121,7,0.289474,0.210044,0.138247,0.082847,0.071429,0.024460,0.023292,0.022654
8,Dom. 2 Adventus,Vigilia Nat. Domini,195,40,1,0.123053,0.068561,0.050034,0.040130,0.036755,0.027119,0.008032,0.004274
9,Dom. 3 Adventus,Dom. 4 Adventus,92,40,0,0.092920,0.073983,0.050053,0.030829,0.032609,0.017647,0.000000,0.000000
10,Dom. 3 Adventus,Nativitas Domini,92,121,0,0.231059,0.178140,0.095197,0.050432,0.040761,0.012957,0.005396,0.000000
11,Dom. 3 Adventus,Vigilia Nat. Domini,92,40,4,0.124675,0.075408,0.065341,0.060261,0.075431,0.045226,0.041379,0.031250
12,Dom. 4 Adventus,Nativitas Domini,40,121,1,0.061958,0.047542,0.030172,0.016560,0.015270,0.006462,0.007968,0.006250
13,Dom. 4 Adventus,Vigilia Nat. Domini,40,40,1,0.058678,0.055866,0.055556,0.027027,0.025830,0.033058,0.020833,0.012658
14,Nativitas Domini,Vigilia Nat. Domini,121,40,2,0.169541,0.068972,0.047683,0.037303,0.028571,0.020717,0.009709,0.012579

In [31]:
matins_df = compare_edgewise_networks(advent_matins_nets, THRESHOLDS)
matins_df

,network_1,network_2,edges_1,edges_2,shared_edges,edge_overlap_0.0,edge_overlap_0.2,edge_overlap_0.3,edge_overlap_0.4,edge_overlap_0.5,edge_overlap_0.6,edge_overlap_0.7,edge_overlap_0.8
0,Dom. 1 Adventus,Dom. 2 Adventus,35,62,12,0.783261,0.772520,0.573790,0.389731,0.346693,0.344388,0.315789,0.141176
1,Dom. 1 Adventus,Dom. 3 Adventus,35,65,12,0.711088,0.688515,0.520751,0.345387,0.293103,0.282474,0.250000,0.136364
2,Dom. 1 Adventus,Dom. 4 Adventus,35,97,17,0.646208,0.612145,0.406739,0.314861,0.313122,0.287698,0.260504,0.147826
3,Dom. 1 Adventus,Nativitas Domini,35,51,12,0.508338,0.467693,0.352354,0.227070,0.153522,0.168157,0.272727,0.162162
4,Dom. 1 Adventus,Vigilia Nat. Domini,35,50,8,0.644817,0.549633,0.368457,0.205694,0.153015,0.169811,0.204301,0.103896
5,Dom. 2 Adventus,Dom. 3 Adventus,62,65,26,0.794735,0.782457,0.636047,0.455187,0.408740,0.384146,0.358974,0.257426
6,Dom. 2 Adventus,Dom. 4 Adventus,62,97,33,0.731954,0.710036,0.506029,0.400000,0.401582,0.393701,0.330709,0.261905
7,Dom. 2 Adventus,Nativitas Domini,62,51,12,0.478229,0.492424,0.364367,0.230750,0.136865,0.148387,0.232143,0.118812
8,Dom. 2 Adventus,Vigilia Nat. Domini,62,50,10,0.612181,0.589427,0.392841,0.242229,0.170912,0.178344,0.180180,0.098039
9,Dom. 3 Adventus,Dom. 4 Adventus,65,97,36,0.842556,0.815249,0.595413,0.419439,0.407556,0.449458,0.368030,0.285714
10,Dom. 3 Adventus,Nativitas Domini,65,51,23,0.558704,0.578725,0.445310,0.314117,0.172487,0.185022,0.264463,0.247312
11,Dom. 3 Adventus,Vigilia Nat. Domini,65,50,25,0.715746,0.683533,0.466927,0.299823,0.195915,0.210428,0.226891,0.277778
12,Dom. 4 Adventus,Nativitas Domini,97,51,28,0.611071,0.635646,0.474880,0.275366,0.161308,0.168067,0.253846,0.233333
13,Dom. 4 Adventus,Vigilia Nat. Domini,97,50,16,0.737090,0.712266,0.492336,0.300875,0.234488,0.224231,0.177358,0.122137
14,Nativitas Domini,Vigilia Nat. Domini,51,50,23,0.679625,0.638767,0.493220,0.275681,0.157681,0.180243,0.243781,0.294872

In [19]:
import itertools
import pandas as pd
import importlib
import utils
importlib.reload(utils)

CORE_THRESHOLDS = [0.2, 0.4, 0.6]

rows = []

for feast1, feast2 in itertools.combinations(advent_nets.keys(), 2):
    for threshold in CORE_THRESHOLDS:
        result = utils.compare_largest_cores(
            advent_nets[feast1],
            advent_nets[feast2],
            threshold
        )
        rows.append(result)

core_comparison_df = pd.DataFrame(rows)
core_comparison_df

,network_1,network_2,threshold,core_size_1,core_size_2,shared_core_sources,core_overlap
0,Dom. 1 Adventus,Dom. 2 Adventus,0.2,130,131,129,0.977273
1,Dom. 1 Adventus,Dom. 2 Adventus,0.4,122,125,121,0.960317
2,Dom. 1 Adventus,Dom. 2 Adventus,0.6,113,119,110,0.901639
3,Dom. 1 Adventus,Dom. 3 Adventus,0.2,130,243,129,0.528689
4,Dom. 1 Adventus,Dom. 3 Adventus,0.4,122,122,118,0.936508
5,Dom. 1 Adventus,Dom. 3 Adventus,0.6,113,118,108,0.878049
6,Dom. 1 Adventus,Dom. 4 Adventus,0.2,130,245,118,0.459144
7,Dom. 1 Adventus,Dom. 4 Adventus,0.4,122,119,108,0.812030
8,Dom. 1 Adventus,Dom. 4 Adventus,0.6,113,102,90,0.720000
9,Dom. 1 Adventus,Nativitas Domini,0.2,130,294,123,0.408638
10,Dom. 1 Adventus,Nativitas Domini,0.4,122,138,109,0.721854
11,Dom. 1 Adventus,Nativitas Domini,0.6,113,116,93,0.683824
12,Dom. 1 Adventus,Vigilia Nat. Domini,0.2,130,249,118,0.452107
13,Dom. 1 Adventus,Vigilia Nat. Domini,0.4,122,130,114,0.826087
14,Dom. 1 Adventus,Vigilia Nat. Domini,0.6,113,125,102,0.750000
15,Dom. 2 Adventus,Dom. 3 Adventus,0.2,131,243,130,0.532787
16,Dom. 2 Adventus,Dom. 3 Adventus,0.4,125,122,119,0.929688
17,Dom. 2 Adventus,Dom. 3 Adventus,0.6,119,118,115,0.942623
18,Dom. 2 Adventus,Dom. 4 Adventus,0.2,131,245,119,0.463035
19,Dom. 2 Adventus,Dom. 4 Adventus,0.4,125,119,110,0.820896
20,Dom. 2 Adventus,Dom. 4 Adventus,0.6,119,102,93,0.726562
21,Dom. 2 Adventus,Nativitas Domini,0.2,131,294,124,0.411960
22,Dom. 2 Adventus,Nativitas Domini,0.4,125,138,110,0.718954
23,Dom. 2 Adventus,Nativitas Domini,0.6,119,116,96,0.690647
24,Dom. 2 Adventus,Vigilia Nat. Domini,0.2,131,249,119,0.455939
25,Dom. 2 Adventus,Vigilia Nat. Domini,0.4,125,130,115,0.821429
26,Dom. 2 Adventus,Vigilia Nat. Domini,0.6,119,125,109,0.807407
27,Dom. 3 Adventus,Dom. 4 Adventus,0.2,243,245,231,0.898833
28,Dom. 3 Adventus,Dom. 4 Adventus,0.4,122,119,109,0.825758
29,Dom. 3 Adventus,Dom. 4 Adventus,0.6,118,102,93,0.732283
30,Dom. 3 Adventus,Nativitas Domini,0.2,243,294,233,0.766447
31,Dom. 3 Adventus,Nativitas Domini,0.4,122,138,109,0.721854
32,Dom. 3 Adventus,Nativitas Domini,0.6,118,116,96,0.695652
33,Dom. 3 Adventus,Vigilia Nat. Domini,0.2,243,249,226,0.849624
34,Dom. 3 Adventus,Vigilia Nat. Domini,0.4,122,130,114,0.826087
35,Dom. 3 Adventus,Vigilia Nat. Domini,0.6,118,125,109,0.813433
36,Dom. 4 Adventus,Nativitas Domini,0.2,245,294,234,0.767213
37,Dom. 4 Adventus,Nativitas Domini,0.4,119,138,108,0.724832
38,Dom. 4 Adventus,Nativitas Domini,0.6,102,116,89,0.689922
39,Dom. 4 Adventus,Vigilia Nat. Domini,0.2,245,249,227,0.850187
40,Dom. 4 Adventus,Vigilia Nat. Domini,0.4,119,130,111,0.804348
41,Dom. 4 Adventus,Vigilia Nat. Domini,0.6,102,125,95,0.719697
42,Nativitas Domini,Vigilia Nat. Domini,0.2,294,249,245,0.822148
43,Nativitas Domini,Vigilia Nat. Domini,0.4,138,130,121,0.823129
44,Nativitas Domini,Vigilia Nat. Domini,0.6,116,125,108,0.812030

In [32]:
import sbmodel 
importlib.reload(sbmodel)
importlib.reload(utils)

def perform_weighted_sbm_analysis(network):
    model = sbmodel.SBModel()
    model.load_graph_nx(network)
    model.fit_sbm_weighted('weight')
    best_state = model.best_states['Weighted_DC_SBM']
    partitions = utils.get_partitions_from_state(best_state, sigla_dict=sigla_dict)
    return partitions

In [33]:
def prepare_sbm_by_pairs(nets):
    sbm_results_by_pairs = {}
    for feast1, feast2 in itertools.combinations(nets.keys(), 2):
        network1, network2 = utils.networks_reduction_on_shared_nodes(nets[feast1], nets[feast2])
        partition1 = perform_weighted_sbm_analysis(network1)[1]
        partition2 = perform_weighted_sbm_analysis(network2)[1]
        sbm_results_by_pairs[(feast1, feast2)] = (partition1, partition2)

    return sbm_results_by_pairs

In [34]:
advent_sbm_results = prepare_sbm_by_pairs(advent_nets)

Loaded graph with 245 vertices, 14424 edges
Fitting weighted SBM to graph with 245 vertices and 14424 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16288.47
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15984.67
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15973.31
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15984.48
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16018.93
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16214.82
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16214.34
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 17213.16
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16010.33
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15988.84
Loaded graph with 245 vertices, 14005 edges
Fitting weighted SBM to graph with 245 vertices and 14005 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16621.45
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16544.87
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16616.54
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16577.86
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 24831.85
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16644.49
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16645.78
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16544.87
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16546.10
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16623.54
Loaded graph with 247 vertices, 14488 edges
Fitting weighted SBM to graph with 247 vertices and 14488 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15942.71
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15937.51
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15899.60
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15903.90
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15909.36
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15910.41
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15895.21
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15935.52
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15924.76
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15976.62
Loaded graph with 247 vertices, 13889 edges
Fitting weighted SBM to graph with 247 vertices and 13889 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16206.45
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16189.29
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 18033.10
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16176.31
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16578.22
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16207.09
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16203.55
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16222.66
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16255.88
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16181.13
Loaded graph with 234 vertices, 13200 edges
Fitting weighted SBM to graph with 234 vertices and 13200 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 14606.59
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 14462.15
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 14465.90
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 14809.63
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 14453.69
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 14469.87
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 14476.22
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 14504.03
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 14527.67
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 14452.38
Loaded graph with 234 vertices, 12400 edges
Fitting weighted SBM to graph with 234 vertices and 12400 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 11539.34
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 11558.29
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 11517.06
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 11569.11
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 11512.26
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 11518.49
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 11547.47
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 11517.01
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 11546.27
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 11543.21
Loaded graph with 246 vertices, 13924 edges
Fitting weighted SBM to graph with 246 vertices and 13924 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15023.20
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15034.03
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15000.23
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15009.02
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 19143.46
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15011.01
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 14993.45
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15030.99
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15008.88
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15011.85
Loaded graph with 246 vertices, 16836 edges
Fitting weighted SBM to graph with 246 vertices and 16836 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 9901.93
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 9864.63
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 9933.38
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 9926.91
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 9890.25
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 9878.73
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 9887.51
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 9850.71
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 9866.38
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 9878.12
Loaded graph with 230 vertices, 13034 edges
Fitting weighted SBM to graph with 230 vertices and 13034 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 14703.96
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 14693.64
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 14686.70
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16392.61
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 14713.46
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 14673.22
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 14686.91
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 14701.20
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 14681.67
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 14685.95
Loaded graph with 230 vertices, 12663 edges
Fitting weighted SBM to graph with 230 vertices and 12663 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15201.68
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 17048.07
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15208.64
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15131.95
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15319.00
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15451.67
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15265.20
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15208.80
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15192.20
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15149.96
Loaded graph with 247 vertices, 14153 edges
Fitting weighted SBM to graph with 247 vertices and 14153 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16613.04
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16622.78
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16633.14
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16634.27
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16628.77
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16809.06
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16700.34
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16643.50
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16684.76
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16690.01
Loaded graph with 247 vertices, 14115 edges
Fitting weighted SBM to graph with 247 vertices and 14115 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 17534.83
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 25103.18
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16595.07
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16425.41
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16527.28
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16583.68
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16416.53
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16430.84
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16502.83
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16446.48
Loaded graph with 237 vertices, 13040 edges
Fitting weighted SBM to graph with 237 vertices and 13040 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15085.72
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15163.49
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15110.08
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15168.68
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15108.04
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15109.99
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15147.36
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15101.23
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15107.20
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15169.59
Loaded graph with 237 vertices, 12735 edges
Fitting weighted SBM to graph with 237 vertices and 12735 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 12026.92
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 11817.02
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 11812.34
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 11818.69
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 11809.50
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 11830.26
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 11814.85
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 11826.97
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 11793.57
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 11803.72
Loaded graph with 241 vertices, 13520 edges
Fitting weighted SBM to graph with 241 vertices and 13520 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15701.69
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15712.82
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15711.43
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15783.16
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15974.23
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15705.81
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15782.09
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15709.15
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15743.65
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16104.89
Loaded graph with 241 vertices, 16443 edges
Fitting weighted SBM to graph with 241 vertices and 16443 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 10098.26
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 10168.86
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 10117.86
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 11626.61
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 10099.17
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 10081.37
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 10055.26
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 10084.04
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 10083.16
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 10050.10
Loaded graph with 229 vertices, 12757 edges
Fitting weighted SBM to graph with 229 vertices and 12757 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15353.97
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15393.65
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15426.66
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 23530.65
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15359.73
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15409.65
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15396.08
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15579.21
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15440.99
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15371.56
Loaded graph with 229 vertices, 12698 edges
Fitting weighted SBM to graph with 229 vertices and 12698 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15159.86
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15099.90
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15276.66
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15159.49
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15108.65
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15183.02
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15291.53
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15117.18
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15129.20
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15159.50
Loaded graph with 245 vertices, 13753 edges
Fitting weighted SBM to graph with 245 vertices and 13753 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15511.77
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15518.35
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16716.23
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15495.78
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15523.62
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15507.13
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15492.75
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15529.98
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15497.46
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15513.79
Loaded graph with 245 vertices, 13529 edges
Fitting weighted SBM to graph with 245 vertices and 13529 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 12633.32
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 12633.09
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 12640.90
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 12641.65
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 12639.13
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 12636.11
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 12629.64
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 12692.09
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 12670.08
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 12644.33
Loaded graph with 252 vertices, 14163 edges
Fitting weighted SBM to graph with 252 vertices and 14163 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16153.21
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16128.19
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16144.79
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16177.42
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16132.64
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16149.38
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 17317.00
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16144.89
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16155.04
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16160.09
Loaded graph with 252 vertices, 17744 edges
Fitting weighted SBM to graph with 252 vertices and 17744 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 10908.27
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 10928.76
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 10770.91
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 10777.20
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 10776.81
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 10760.46
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 10987.92
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 10766.78
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 10799.07
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 10864.11
Loaded graph with 237 vertices, 13542 edges
Fitting weighted SBM to graph with 237 vertices and 13542 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15535.03
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 17063.86
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15550.43
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15594.86
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15565.57
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15555.64
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15565.24
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15536.14
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15555.64
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15537.96
Loaded graph with 237 vertices, 13576 edges
Fitting weighted SBM to graph with 237 vertices and 13576 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 18629.89
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16184.19
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16166.22
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16197.98
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16094.62
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 17862.50
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16087.52
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16145.80
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16140.31
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16075.34
Loaded graph with 252 vertices, 14209 edges
Fitting weighted SBM to graph with 252 vertices and 14209 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 13051.55
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 17068.77
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 13017.44
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 13618.19
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 13071.21
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 13035.42
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 13040.09
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 13662.95
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 13046.29
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 13029.44
Loaded graph with 252 vertices, 17785 edges
Fitting weighted SBM to graph with 252 vertices and 17785 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 10639.02
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 10627.11
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 10681.22
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 10653.02
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 10633.38
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 10598.21
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 10632.51
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 10579.52
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 10684.45
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 10645.54
Loaded graph with 236 vertices, 13263 edges
Fitting weighted SBM to graph with 236 vertices and 13263 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 12495.02
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 12557.94
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 12486.00
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 12524.78
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 12534.21
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 12486.43
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 13530.67
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 12490.22
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 12600.01
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 12534.21
Loaded graph with 236 vertices, 13461 edges
Fitting weighted SBM to graph with 236 vertices and 13461 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15702.85
Fitting weighted SBM (init 2/10)...

In [39]:
import pickle
with open('visual/advent_sbm_results.pkl', 'wb') as f:
    pickle.dump(advent_sbm_results, f)

In [35]:
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

def transform_partition_to_labels(partition):
    node_to_block = {}
    for block, nodes in partition.items():
        for node in nodes:
            node_to_block[node] = block
    return node_to_block


def compare_weighted_sbm_partitions(sbm_on_nets):
    rows = []
    for (feast1, feast2), (partition1, partition2) in sbm_on_nets.items():
        row = {'network_1': feast1, 'network_2': feast2}
        row['num_partitions_1'] = len(partition1)
        row['num_partitions_2'] = len(partition2)

        partition1 = transform_partition_to_labels(partition1)
        partition2 = transform_partition_to_labels(partition2)

        shared_nodes = sorted(set(partition1) & set(partition2))
        labels1 = [partition1[node] for node in shared_nodes]
        labels2 = [partition2[node] for node in shared_nodes]

        row['n_shared_nodes'] = len(shared_nodes)
        row['adjusted_rand_index'] = adjusted_rand_score(labels1, labels2)
        row['normalized_mutual_info'] = normalized_mutual_info_score(labels1, labels2)

        rows.append(row)
    comparison_df = pd.DataFrame(rows)
    return comparison_df

In [36]:
sbm_comparison_df = compare_weighted_sbm_partitions(advent_sbm_results)
sbm_comparison_df

,network_1,network_2,num_partitions_1,num_partitions_2,n_shared_nodes,adjusted_rand_index,normalized_mutual_info
0,Dom. 1 Adventus,Dom. 2 Adventus,9,9,245,0.763359,0.710236
1,Dom. 1 Adventus,Dom. 3 Adventus,9,8,247,0.783877,0.707909
2,Dom. 1 Adventus,Dom. 4 Adventus,8,7,234,0.689264,0.689721
3,Dom. 1 Adventus,Nativitas Domini,10,11,246,0.450834,0.533041
4,Dom. 1 Adventus,Vigilia Nat. Domini,9,7,230,0.748537,0.637724
5,Dom. 2 Adventus,Dom. 3 Adventus,11,8,247,0.692776,0.700640
6,Dom. 2 Adventus,Dom. 4 Adventus,10,7,237,0.618297,0.684793
7,Dom. 2 Adventus,Nativitas Domini,8,11,241,0.567508,0.552658
8,Dom. 2 Adventus,Vigilia Nat. Domini,7,7,229,0.740288,0.656052
9,Dom. 3 Adventus,Dom. 4 Adventus,8,8,245,0.783970,0.743635
10,Dom. 3 Adventus,Nativitas Domini,8,12,252,0.486859,0.578575
11,Dom. 3 Adventus,Vigilia Nat. Domini,8,7,237,0.824070,0.725886
12,Dom. 4 Adventus,Nativitas Domini,7,11,252,0.578013,0.569865
13,Dom. 4 Adventus,Vigilia Nat. Domini,6,7,236,0.740685,0.666721
14,Nativitas Domini,Vigilia Nat. Domini,12,7,257,0.474688,0.535522

## Summary accross Sundays

In [37]:
edge_comparison_df = compare_edgewise_networks(advent_nets, THRESHOLDS)

advent_sbm_results = prepare_sbm_by_pairs(advent_nets)
sbm_comparison_df = compare_weighted_sbm_partitions(advent_sbm_results)

advent_comparison_df = edge_comparison_df.merge(sbm_comparison_df, on=["network_1", "network_2"])
advent_comparison_df.to_csv("visual/advent_comparison.csv", index=False)

Loaded graph with 245 vertices, 14424 edges
Fitting weighted SBM to graph with 245 vertices and 14424 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15985.06
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16050.01
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16000.94
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16019.91
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15995.87
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15956.33
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 24219.81
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16018.60
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15986.02
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16017.13
Loaded graph with 245 vertices, 14005 edges
Fitting weighted SBM to graph with 245 vertices and 14005 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16549.96
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16552.77
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16554.40
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 18767.49
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16558.98
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16555.15
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16611.61
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16532.68
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16619.41
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16552.52
Loaded graph with 247 vertices, 14488 edges
Fitting weighted SBM to graph with 247 vertices and 14488 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15909.46
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15896.70
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15918.58
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15960.42
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15934.54
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15922.90
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16393.02
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15924.96
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15902.65
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15932.78
Loaded graph with 247 vertices, 13889 edges
Fitting weighted SBM to graph with 247 vertices and 13889 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16183.27
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16226.24
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16193.59
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16178.75
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16237.19
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16182.40
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16183.27
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16189.48
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16178.82
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16176.70
Loaded graph with 234 vertices, 13200 edges
Fitting weighted SBM to graph with 234 vertices and 13200 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 14447.81
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 14451.40
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 14456.17
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 14452.05
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 14451.21
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 14452.05
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 14417.61
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 14449.85
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 14431.99
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 14444.51
Loaded graph with 234 vertices, 12400 edges
Fitting weighted SBM to graph with 234 vertices and 12400 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 11532.93
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 11541.85
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 11548.22
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 11533.33
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 11533.51
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 11638.76
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 11535.55
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 11536.31
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 11538.12
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 11531.36
Loaded graph with 246 vertices, 13924 edges
Fitting weighted SBM to graph with 246 vertices and 13924 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15026.02
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15002.47
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15013.62
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15477.55
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15015.18
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15027.60
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15072.72
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 22487.68
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 14998.24
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15018.19
Loaded graph with 246 vertices, 16836 edges
Fitting weighted SBM to graph with 246 vertices and 16836 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 9850.74
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 9904.91
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 9860.64
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 9867.74
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 9872.84
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 9893.43
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 9977.26
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 9881.68
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 9876.99
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 9957.26
Loaded graph with 230 vertices, 13034 edges
Fitting weighted SBM to graph with 230 vertices and 13034 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15210.14
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 14851.56
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 14682.91
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 14709.98
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 14696.11
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 14679.12
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 14696.11
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 14692.36
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 14658.77
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 22016.35
Loaded graph with 230 vertices, 12663 edges
Fitting weighted SBM to graph with 230 vertices and 12663 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15150.34
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15191.07
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15192.20
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 23259.34
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15142.35
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15191.07
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15129.89
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15215.95
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 18166.65
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15240.52
Loaded graph with 247 vertices, 14153 edges
Fitting weighted SBM to graph with 247 vertices and 14153 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16679.39
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16617.19
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16772.95
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16699.03
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16634.73
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16684.48
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16622.08
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 24451.59
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16631.26
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16636.85
Loaded graph with 247 vertices, 14115 edges
Fitting weighted SBM to graph with 247 vertices and 14115 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16426.21
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 17555.26
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16427.51
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 17323.71
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16862.53
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16461.84
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16425.59
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16419.98
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16520.83
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 18910.74
Loaded graph with 237 vertices, 13040 edges
Fitting weighted SBM to graph with 237 vertices and 13040 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15245.05
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15577.99
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15180.74
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15108.29
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15172.55
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15170.23
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15114.01
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16375.48
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15101.04
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15735.31
Loaded graph with 237 vertices, 12735 edges
Fitting weighted SBM to graph with 237 vertices and 12735 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 11800.22
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 11798.20
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 11868.19
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 11829.18
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 11806.22
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 11806.59
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 11817.42
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 11818.34
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 11817.42
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 11801.29
Loaded graph with 241 vertices, 13520 edges
Fitting weighted SBM to graph with 241 vertices and 13520 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15783.91
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15753.29
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15782.33
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15791.34
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15738.80
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15737.50
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15717.85
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15707.31
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15701.69
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15706.13
Loaded graph with 241 vertices, 16443 edges
Fitting weighted SBM to graph with 241 vertices and 16443 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 10207.53
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 10105.32
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 10243.95
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 10092.55
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 10140.56
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 10069.92
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 10241.44
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 10061.81
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 10041.12
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 10906.56
Loaded graph with 229 vertices, 12757 edges
Fitting weighted SBM to graph with 229 vertices and 12757 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15354.10
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15420.91
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15471.67
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15410.50
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16371.25
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15362.06
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15354.10
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15344.58
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15354.10
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15352.06
Loaded graph with 229 vertices, 12698 edges
Fitting weighted SBM to graph with 229 vertices and 12698 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15159.50
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15127.91
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15492.64
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15181.90
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15136.78
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15103.68
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15169.40
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15128.14
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15180.97
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15159.09
Loaded graph with 245 vertices, 13753 edges
Fitting weighted SBM to graph with 245 vertices and 13753 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15490.40
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15546.79
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15501.79
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15522.81
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15568.06
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15521.76
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15493.06
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15564.46
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15521.19
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15491.26
Loaded graph with 245 vertices, 13529 edges
Fitting weighted SBM to graph with 245 vertices and 13529 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 12635.14
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 12646.06
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 13450.56
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 13014.63
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 12867.22
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 12650.09
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 12638.86
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 12624.78
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 12734.25
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 12629.42
Loaded graph with 252 vertices, 14163 edges
Fitting weighted SBM to graph with 252 vertices and 14163 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16158.41
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16177.29
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16162.98
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16148.63
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16128.38
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16148.23
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16151.61
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16133.88
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16146.20
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 18996.22
Loaded graph with 252 vertices, 17744 edges
Fitting weighted SBM to graph with 252 vertices and 17744 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 10755.84
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 10765.90
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 10783.88
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 10748.65
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 10777.85
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 10784.51
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 10791.10
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 10785.52
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 10841.20
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 10900.94
Loaded graph with 237 vertices, 13542 edges
Fitting weighted SBM to graph with 237 vertices and 13542 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15567.34
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 15537.99
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 15626.84
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 15555.64
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 15546.38
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 15550.43
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 15583.21
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 15550.39
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 15572.61
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 15541.56
Loaded graph with 237 vertices, 13576 edges
Fitting weighted SBM to graph with 237 vertices and 13576 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 16145.80
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 16193.79
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 16094.62
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 16159.36
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 16075.03
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 16213.98
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 16075.34
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 16146.39
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 16096.16
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 16146.06
Loaded graph with 252 vertices, 14209 edges
Fitting weighted SBM to graph with 252 vertices and 14209 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 13030.17
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 13507.52
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 13077.58
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 13031.26
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 13023.38
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 13049.32
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 13031.59
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 13259.11
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 13031.20
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 13046.14
Loaded graph with 252 vertices, 17785 edges
Fitting weighted SBM to graph with 252 vertices and 17785 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 10912.73
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 10639.13
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 10597.83
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 10696.47
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 10599.23
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 13503.88
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 10713.41
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 11639.15
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 10673.60
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 10620.49
Loaded graph with 236 vertices, 13263 edges
Fitting weighted SBM to graph with 236 vertices and 13263 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 12521.08
Fitting weighted SBM (init 2/10)...
[2/10] entropy = 13726.08
Fitting weighted SBM (init 3/10)...
[3/10] entropy = 12488.83
Fitting weighted SBM (init 4/10)...
[4/10] entropy = 12537.61
Fitting weighted SBM (init 5/10)...
[5/10] entropy = 12488.66
Fitting weighted SBM (init 6/10)...
[6/10] entropy = 12508.05
Fitting weighted SBM (init 7/10)...
[7/10] entropy = 12489.26
Fitting weighted SBM (init 8/10)...
[8/10] entropy = 12490.55
Fitting weighted SBM (init 9/10)...
[9/10] entropy = 12491.02
Fitting weighted SBM (init 10/10)...
[10/10] entropy = 12485.81
Loaded graph with 236 vertices, 13461 edges
Fitting weighted SBM to graph with 236 vertices and 13461 edges...
Fitting weighted SBM (init 1/10)...
[1/10] entropy = 15825.69
Fitting weighted SBM (init 2/10)...

## Summary accross Office (V, L, M, V2)

In [38]:
# Preparation of all the metrics for individula subcorpora (Lauds, Vespers, Matins, Second Vespers) 
# and comparison of the results for each office separately.

# CSV having same lines as pairs of feasts
# and in colums would be like "edgewise_overlap_0.2_M" for Matins only etc for the others as well.

# Summary across offices: whole day + Lauds + Vespers + Second Vespers + Matins

OFFICE_NETWORKS = {
    "whole_day": advent_nets,
    "L": advent_lauds_nets,
    "V": advent_vespers_nets,
    "V2": advent_vespers2_nets,
    "M": advent_matins_nets,}

office_dfs = []

for office_name, nets in OFFICE_NETWORKS.items():
    df = compare_edgewise_networks(nets, THRESHOLDS)

    rename_cols = {
        col: f"{col}_{office_name}"
        for col in df.columns
        if col not in ["network_1", "network_2"]}

    df = df.rename(columns = rename_cols)
    office_dfs.append(df)

office_comparison_df = office_dfs[0]

for df in office_dfs[1:]:
    office_comparison_df = office_comparison_df.merge(df, on = ["network_1", "network_2"], how = "outer")

office_comparison_df.to_csv("visual/advent_office_edge_overlap_comparison.csv", index = False)
office_comparison_df

,network_1,network_2,edges_1_whole_day,edges_2_whole_day,shared_edges_whole_day,edge_overlap_0.0_whole_day,edge_overlap_0.2_whole_day,edge_overlap_0.3_whole_day,edge_overlap_0.4_whole_day,edge_overlap_0.5_whole_day,...,edges_2_M,shared_edges_M,edge_overlap_0.0_M,edge_overlap_0.2_M,edge_overlap_0.3_M,edge_overlap_0.4_M,edge_overlap_0.5_M,edge_overlap_0.6_M,edge_overlap_0.7_M,edge_overlap_0.8_M
0,Dom. 1 Adventus,Dom. 2 Adventus,1420,2248,970,0.886971,0.857684,0.776512,0.710637,0.683638,...,62,12,0.783261,0.772520,0.573790,0.389731,0.346693,0.344388,0.315789,0.141176
1,Dom. 1 Adventus,Dom. 3 Adventus,1420,1324,621,0.826724,0.790774,0.732352,0.662654,0.628361,...,65,12,0.711088,0.688515,0.520751,0.345387,0.293103,0.282474,0.250000,0.136364
2,Dom. 1 Adventus,Dom. 4 Adventus,1420,343,156,0.668962,0.614356,0.495844,0.352725,0.253537,...,97,17,0.646208,0.612145,0.406739,0.314861,0.313122,0.287698,0.260504,0.147826
3,Dom. 1 Adventus,Nativitas Domini,1420,1351,509,0.504613,0.553858,0.505103,0.440384,0.406710,...,51,12,0.508338,0.467693,0.352354,0.227070,0.153522,0.168157,0.272727,0.162162
4,Dom. 1 Adventus,Vigilia Nat. Domini,1420,1646,652,0.644163,0.634629,0.563112,0.484052,0.472877,...,50,8,0.644817,0.549633,0.368457,0.205694,0.153015,0.169811,0.204301,0.103896
5,Dom. 2 Adventus,Dom. 3 Adventus,2248,1324,842,0.873973,0.832320,0.788814,0.755843,0.734998,...,65,26,0.794735,0.782457,0.636047,0.455187,0.408740,0.384146,0.358974,0.257426
6,Dom. 2 Adventus,Dom. 4 Adventus,2248,343,193,0.712174,0.653522,0.516848,0.376577,0.271988,...,97,33,0.731954,0.710036,0.506029,0.400000,0.401582,0.393701,0.330709,0.261905
7,Dom. 2 Adventus,Nativitas Domini,2248,1351,709,0.502626,0.551705,0.499207,0.451963,0.428132,...,51,12,0.478229,0.492424,0.364367,0.230750,0.136865,0.148387,0.232143,0.118812
8,Dom. 2 Adventus,Vigilia Nat. Domini,2248,1646,817,0.661711,0.644559,0.575522,0.522388,0.513298,...,50,10,0.612181,0.589427,0.392841,0.242229,0.170912,0.178344,0.180180,0.098039
9,Dom. 3 Adventus,Dom. 4 Adventus,1324,343,192,0.768090,0.693591,0.559757,0.386963,0.265094,...,97,36,0.842556,0.815249,0.595413,0.419439,0.407556,0.449458,0.368030,0.285714
10,Dom. 3 Adventus,Nativitas Domini,1324,1351,464,0.526674,0.590236,0.543860,0.486610,0.444204,...,51,23,0.558704,0.578725,0.445310,0.314117,0.172487,0.185022,0.264463,0.247312
11,Dom. 3 Adventus,Vigilia Nat. Domini,1324,1646,594,0.706002,0.671583,0.617668,0.548587,0.532727,...,50,25,0.715746,0.683533,0.466927,0.299823,0.195915,0.210428,0.226891,0.277778
12,Dom. 4 Adventus,Nativitas Domini,343,1351,161,0.523788,0.560442,0.458243,0.307523,0.215627,...,51,28,0.611071,0.635646,0.474880,0.275366,0.161308,0.168067,0.253846,0.233333
13,Dom. 4 Adventus,Vigilia Nat. Domini,343,1646,182,0.680445,0.630453,0.505631,0.337151,0.233595,...,50,16,0.737090,0.712266,0.492336,0.300875,0.234488,0.224231,0.177358,0.122137
14,Nativitas Domini,Vigilia Nat. Domini,1351,1646,750,0.594000,0.720850,0.647286,0.597412,0.593325,...,50,23,0.679625,0.638767,0.493220,0.275681,0.157681,0.180243,0.243781,0.294872