In [1]:
import utils
import sbmodel
import pycantus
import pycantus.data as data

In [2]:
corpus = data.load_dataset('cantuscorpus_v1.0')

Loading chants and sources...
Data loaded!

In [3]:
n_chants = len(corpus.chants)
print(f'Number of chants in CantusCorpus v1.0: {n_chants}')
n_sources = len(corpus.sources)
print(f'Number of sources in CantusCorpus v1.0: {n_sources}')

Number of chants in CantusCorpus v1.0: 888010
Number of sources in CantusCorpus v1.0: 2278

In [4]:
# Drop doxology
doxo_filter = pycantus.filtration.Filter('doxo_filter')
doxo_filter.add_value_exclude('cantus_id', '909000')
corpus.apply_filter(doxo_filter)

In [81]:
MIN_CHANTS_PER_SOURCE = 600

In [7]:
# Drop fragments => sources with less than 100 chants
corpus.drop_small_sources_data(min_chants=MIN_CHANTS_PER_SOURCE)

In [8]:
n_chants = len(corpus.chants)
print(f'Number of chants in CantusCorpus v1.0: {n_chants}')
n_sources = len(corpus.sources)
print(f'Number of sources in CantusCorpus v1.0: {n_sources}')

Number of chants in CantusCorpus v1.0: 812806
Number of sources in CantusCorpus v1.0: 363

In [9]:
sigla_dict = {source.srclink: source.siglum for source in corpus.sources}

### Networks

In [10]:
import importlib
importlib.reload(utils)

In [55]:
MIN_CID_PER_FEAST = 50
MIN_FEAST_CHANTS_PER_SOURCE = 10

In [56]:
graph = utils.construct_bipart_source_feast_reducted_graph(corpus, min_cid_per_feast=MIN_CID_PER_FEAST, 
                                                           per_source_threshold=MIN_FEAST_CHANTS_PER_SOURCE)

Constructing bipartite graph between sources and feasts...
Number of source nodes: 363
Number of feast nodes: 719
Number of source-feast edges: 17638

In [57]:
utils.save_graph(graph, f"nets/source_feast_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_bi_graph_min_{MIN_CHANTS_PER_SOURCE}.gt")

### SBM

In [58]:
N_INIT = 20

In [59]:
model = sbmodel.SBModel()

In [60]:
model.load_graph(f"nets/source_feast_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_bi_graph_min_{MIN_CHANTS_PER_SOURCE}.gt")

Loaded graph with 1082 vertices, 17638 edges

In [61]:
model.fit_sbm(n_init=N_INIT)

Fitting SBM to graph with 1082 vertices and 17638 edges...
Fitting SBM (init 1/20)...
[1/20] entropy = 41789.92
Fitting SBM (init 2/20)...
[2/20] entropy = 41694.33
Fitting SBM (init 3/20)...
[3/20] entropy = 41688.49
Fitting SBM (init 4/20)...
[4/20] entropy = 41691.36
Fitting SBM (init 5/20)...
[5/20] entropy = 41760.45
Fitting SBM (init 6/20)...
[6/20] entropy = 41734.55
Fitting SBM (init 7/20)...
[7/20] entropy = 41674.23
Fitting SBM (init 8/20)...
[8/20] entropy = 41764.46
Fitting SBM (init 9/20)...
[9/20] entropy = 41826.97
Fitting SBM (init 10/20)...
[10/20] entropy = 41758.91
Fitting SBM (init 11/20)...
[11/20] entropy = 41677.11
Fitting SBM (init 12/20)...
[12/20] entropy = 41739.53
Fitting SBM (init 13/20)...
[13/20] entropy = 41702.36
Fitting SBM (init 14/20)...
[14/20] entropy = 41752.75
Fitting SBM (init 15/20)...
[15/20] entropy = 41757.06
Fitting SBM (init 16/20)...
[16/20] entropy = 41764.63
Fitting SBM (init 17/20)...
[17/20] entropy = 41808.34
Fitting SBM (init 18/20)...
[18/20] entropy = 41801.79
Fitting SBM (init 19/20)...
[19/20] entropy = 41710.89
Fitting SBM (init 20/20)...
[20/20] entropy = 41792.87

In [62]:
model.save_states(f"models/dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

In [63]:
model.fit_nested_sbm(n_init=N_INIT)

Fitting nested SBM to graph with 1082 vertices and 17638 edges...
Fitting nested SBM (init 1/20)...
[1/20] entropy = 40548.29
Fitting nested SBM (init 2/20)...
[2/20] entropy = 40527.14
Fitting nested SBM (init 3/20)...
[3/20] entropy = 40546.93
Fitting nested SBM (init 4/20)...
[4/20] entropy = 40564.36
Fitting nested SBM (init 5/20)...
[5/20] entropy = 40531.09
Fitting nested SBM (init 6/20)...
[6/20] entropy = 40655.28
Fitting nested SBM (init 7/20)...
[7/20] entropy = 40498.42
Fitting nested SBM (init 8/20)...
[8/20] entropy = 40537.75
Fitting nested SBM (init 9/20)...
[9/20] entropy = 40585.76
Fitting nested SBM (init 10/20)...
[10/20] entropy = 40637.48
Fitting nested SBM (init 11/20)...
[11/20] entropy = 40539.96
Fitting nested SBM (init 12/20)...
[12/20] entropy = 40520.28
Fitting nested SBM (init 13/20)...
[13/20] entropy = 40543.91
Fitting nested SBM (init 14/20)...
[14/20] entropy = 40574.78
Fitting nested SBM (init 15/20)...
[15/20] entropy = 40552.02
Fitting nested SBM (init 16/20)...
[16/20] entropy = 40478.34
Fitting nested SBM (init 17/20)...
[17/20] entropy = 40620.54
Fitting nested SBM (init 18/20)...
[18/20] entropy = 40494.46
Fitting nested SBM (init 19/20)...
[19/20] entropy = 40582.01
Fitting nested SBM (init 20/20)...
[20/20] entropy = 40509.59

In [64]:
model.save_states(f"models/dc_nested_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

In [65]:
model.fit_sbm_weighted(n_init=N_INIT, weight_label='weight')

Fitting weighted SBM to graph with 1082 vertices and 17638 edges...
Fitting weighted SBM (init 1/20)...
[1/20] entropy = 86667.92
Fitting weighted SBM (init 2/20)...
[2/20] entropy = 86650.34
Fitting weighted SBM (init 3/20)...
[3/20] entropy = 86696.09
Fitting weighted SBM (init 4/20)...
[4/20] entropy = 86784.72
Fitting weighted SBM (init 5/20)...
[5/20] entropy = 86637.14
Fitting weighted SBM (init 6/20)...
[6/20] entropy = 86619.33
Fitting weighted SBM (init 7/20)...
[7/20] entropy = 86714.30
Fitting weighted SBM (init 8/20)...
[8/20] entropy = 86705.94
Fitting weighted SBM (init 9/20)...
[9/20] entropy = 86725.19
Fitting weighted SBM (init 10/20)...
[10/20] entropy = 86707.01
Fitting weighted SBM (init 11/20)...
[11/20] entropy = 86674.58
Fitting weighted SBM (init 12/20)...
[12/20] entropy = 86637.75
Fitting weighted SBM (init 13/20)...
[13/20] entropy = 86794.16
Fitting weighted SBM (init 14/20)...
[14/20] entropy = 86645.96
Fitting weighted SBM (init 15/20)...
[15/20] entropy = 86700.36
Fitting weighted SBM (init 16/20)...
[16/20] entropy = 86734.06
Fitting weighted SBM (init 17/20)...
[17/20] entropy = 86657.14
Fitting weighted SBM (init 18/20)...
[18/20] entropy = 86655.76
Fitting weighted SBM (init 19/20)...
[19/20] entropy = 86660.78
Fitting weighted SBM (init 20/20)...
[20/20] entropy = 86697.10

In [66]:
model.save_states(f"models/weighted_dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

In [67]:
model.fit_nested_sbm_weighted(n_init=N_INIT, weight_label='weight')

Fitting weighted nested SBM to graph with 1082 vertices and 17638 edges...
Fitting weighted nested SBM (init 1/20)...
[1/20] entropy = 86685.79
Fitting weighted nested SBM (init 2/20)...
[2/20] entropy = 86698.05
Fitting weighted nested SBM (init 3/20)...
[3/20] entropy = 86827.22
Fitting weighted nested SBM (init 4/20)...
[4/20] entropy = 86790.82
Fitting weighted nested SBM (init 5/20)...
[5/20] entropy = 86714.04
Fitting weighted nested SBM (init 6/20)...
[6/20] entropy = 86647.19
Fitting weighted nested SBM (init 7/20)...
[7/20] entropy = 86714.22
Fitting weighted nested SBM (init 8/20)...
[8/20] entropy = 86686.91
Fitting weighted nested SBM (init 9/20)...
[9/20] entropy = 86723.56
Fitting weighted nested SBM (init 10/20)...
[10/20] entropy = 86732.76
Fitting weighted nested SBM (init 11/20)...
[11/20] entropy = 86691.99
Fitting weighted nested SBM (init 12/20)...
[12/20] entropy = 86782.74
Fitting weighted nested SBM (init 13/20)...
[13/20] entropy = 86676.09
Fitting weighted nested SBM (init 14/20)...
[14/20] entropy = 86778.77
Fitting weighted nested SBM (init 15/20)...
[15/20] entropy = 86760.03
Fitting weighted nested SBM (init 16/20)...
[16/20] entropy = 86743.75
Fitting weighted nested SBM (init 17/20)...
[17/20] entropy = 86695.73
Fitting weighted nested SBM (init 18/20)...
[18/20] entropy = 86769.94
Fitting weighted nested SBM (init 19/20)...
[19/20] entropy = 86723.51
Fitting weighted nested SBM (init 20/20)...
[20/20] entropy = 86735.89

In [68]:
model.save_states(f"models/weighted_nested_dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

### Infering

In [69]:
import pickle
importlib.reload(sbmodel)
importlib.reload(utils)

In [70]:
model = sbmodel.SBModel()

In [71]:
model.load_states(f'models/weighted_nested_dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.pickle')

In [72]:
print(model.best_states.keys())

dict_keys(['DC_SBM', 'Nested_DC_SBM', 'Weighted_DC_SBM', 'Weighted_Nested_DC_SBM'])

#### DC-SBM

In [73]:
best_state = model.best_states['DC_SBM']

In [74]:
print("Best DC SBM state:")
print(best_state)
index_partitions, sigla_partitions, feasts_partitions = utils.get_partitions_from_state(best_state, sigla_dict)
print('Number of partitions:', len(index_partitions))
print('Number of sigla partitions:', len(sigla_partitions))
print('Number of feast partitions:', len(feasts_partitions))

Best DC SBM state:
<BlockState object with 1082 blocks (22 nonempty), degree-corrected, for graph <Graph object, undirected, with 1082 vertices and 17638 edges, 2 internal vertex properties, 2 internal edge properties, at 0x74ea86ce45e0>, at 0x74ea86ce72e0>
Number of partitions: 22
Number of sigla partitions: 10
Number of feast partitions: 12

In [75]:
with open(f'visual/dc_sbm_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}min_{MIN_CHANTS_PER_SOURCE}.txt', 'w') as f:
    for partition, feasts in feasts_partitions.items():
        print(sorted(feasts), file=f)
        print(file=f)

In [78]:
importlib.reload(utils)
print(utils.detect_sanctorale_in_partitions(feasts_partitions))

Partition 875: 29/72 : {'Dec': 9, 'Jan': 12, 'Feb': 3, 'Mar': 2, 'Apr': 1, 'May': 1, 'Sep': 1}
Partition 446: 4/17 : {'Dec': 3, 'Jan': 1}
Partition 402: 148/240 : {'Jul': 24, 'Aug': 21, 'Jun': 13, 'Feb': 6, 'May': 11, 'Nov': 15, 'Sep': 20, 'Jan': 6, 'Oct': 16, 'Apr': 6, 'Dec': 8, 'Mar': 2}
Partition 593: 13/18 : {'Nov': 3, 'Jun': 4, 'Aug': 2, 'Sep': 2, 'May': 1, 'Oct': 1}
Partition 557: 6/27 : {'Jun': 1, 'Sep': 1, 'Oct': 1, 'Nov': 2, 'Jul': 1}
Partition 561: 17/38 : {'Jul': 2, 'Jun': 1, 'Aug': 6, 'Apr': 1, 'Oct': 2, 'May': 2, 'Sep': 1, 'Nov': 2}
Partition 378: 1/46 : {'Dec': 1}
Partition 806: 2/14 : {'Dec': 1, 'Aug': 1}
Partition 684: 10/15 : {'Jan': 3, 'Dec': 1, 'Feb': 4, 'Mar': 2}
Partition 907: 37/131 : {'Jun': 1, 'Dec': 6, 'Jan': 4, 'Jul': 4, 'Aug': 8, 'Sep': 6, 'Nov': 3, 'Feb': 1, 'Oct': 2, 'May': 1, 'Apr': 1}
Partition 839: 2/53 : {'Oct': 1, 'Dec': 1}
Partition 1029: 12/48 : {'Apr': 1, 'Feb': 1, 'Dec': 1, 'Jun': 3, 'Jul': 2, 'Nov': 1, 'Sep': 1, 'May': 1, 'Aug': 1}
None

#### DC-Weighted-SBM

In [79]:
best_state = model.best_states['Weighted_DC_SBM']

In [80]:
print("Best Weighted DC SBM state:")
print(best_state)
index_partitions, sigla_partitions, feasts_partitions = utils.get_partitions_from_state(best_state, sigla_dict)
print('Number of partitions:', len(index_partitions))
print('Number of sigla partitions:', len(sigla_partitions))
print('Number of feast partitions:', len(feasts_partitions))

Best Weighted DC SBM state:
<BlockState object with 1082 blocks (22 nonempty), degree-corrected, with 1 edge covariate, for graph <Graph object, undirected, with 1082 vertices and 17638 edges, 2 internal vertex properties, 2 internal edge properties, at 0x74ea86ce45e0>, at 0x74ea84acf820>
Number of partitions: 22
Number of sigla partitions: 10
Number of feast partitions: 12

In [42]:
with open(f'visual/weighted_dc_sbm_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}__threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.txt', 'w') as f:
    for partition, feasts in feasts_partitions.items():
        print(sorted(feasts), file=f)
        print(file=f)

In [76]:
importlib.reload(utils)
source_vs_feast_df = utils.get_sigla_vs_feast_partitions(corpus, sigla_partitions, feasts_partitions)

In [77]:
source_vs_feast_df.to_csv(f'visual/weighted_dc_sbm_source_vs_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.csv', index=False)

#### DC-Nested-SBM

In [47]:
best_state = model.best_states['Nested_DC_SBM']

In [48]:
importlib.reload(utils)
print("Best Nested DC SBM state:")
print(best_state)
index_partitions, sigla_partitions, feasts_partitions = utils.get_nested_partitions_from_state(best_state, sigla_dict)

Best Nested DC SBM state:
<NestedBlockState object, with base <BlockState object with 1082 blocks (60 nonempty), degree-corrected, for graph <Graph object, undirected, with 1082 vertices and 39601 edges, 2 internal vertex properties, 2 internal edge properties, at 0x74ea85998160>, at 0x74ea75aa5ab0>, and 12 levels of sizes [(1082, 60), (60, 18), (18, 5), (5, 3), (3, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)] at 0x74ea86819de0>

In [49]:
print('Feast partitions:')
for level in feasts_partitions:
    print(f'Level {level}:')
    print(len(feasts_partitions[level]))
    for partition, feasts in feasts_partitions[level].items():
        print(f'Partition {partition}: {len(feasts)} {sorted(feasts)}')
    print()

Feast partitions:
Level 0:
26
Partition 470: 13 ['Blasii', 'Conceptio Mariae', 'Conversio Pauli', 'De BMV post Purif.', 'Hilarii', 'Mauri', 'Nicolai', 'Octava Agnetis', 'Octava Andreae', 'Scholasticae', 'Thomae Apost.', 'Thomae Cant.', 'Vedasti']
Partition 402: 14 ['Dom. 1 Adventus', 'Dom. 1 Quadragesimae', 'Dom. 2 Adventus', 'Dom. 2 Quadragesimae', 'Dom. 3 Adventus', 'Dom. 3 Quadragesimae', 'Dom. 4 Adventus', 'Dom. 4 Quadragesimae', 'Dom. Quinquagesimae', 'Dom. Septuagesimae', 'Dom. Sexagesimae', 'Nativitas Domini,8', 'Vigilia Epiphaniae', 'Vigilia Nat. Domini']
Partition 397: 44 ['Barbarae', 'Dom. 4 p. Epiph.', 'Dom. 5 p. Epiph.', 'Dom. p. Oct. Nat.', 'Fer. 2 Hebd. 2 p.Ep.', 'Fer. 2 Hebd. 3 Adv.', 'Fer. 2 p. Epiphaniam', 'Fer. 3 Hebd. 2 p.Ep.', 'Fer. 3 Hebd. 3 Adv.', 'Fer. 3 p. Epiphaniam', 'Fer. 4 Hebd. 1 Adv.', 'Fer. 4 Hebd. 2 p.Ep.', 'Fer. 4 Hebd. 3 Adv.', 'Fer. 4 p. Epiphaniam', 'Fer. 5 Hebd. 2 p.Ep.', 'Fer. 5 Hebd. 3 Adv.', 'Fer. 5 p. Epiphaniam', 'Fer. 6 Hebd. 1 Adv.', 'Fer. 6 Hebd. 2 p.Ep.', 'Fer. 6 Hebd. 3 Adv.', 'Fer. 6 p. Epiphaniam', 'Feria 2 per annum', 'Feria 3 per annum', 'Feria 4 per annum', 'Feria 5 per annum', 'Feria 6 per annum', 'Gertrudis Nivellensis', 'Hebd. 2 Adventus', 'Hebd. 2 p. Pascha', 'Hebd. 3 Adventus', 'Hebd. Nat. Dom.', 'In tempore Epiphaniae', 'Joannis Evang.,8', 'Judoci', 'Lazari', 'Mariae Aegyptiacae', 'Materni', 'Nat. Innocentium,8', 'Octava Nat. Domini,8', 'Sabb. Hebd. 2 p. Ep.', 'Sabb. p. Epiphaniam', 'Sabbato Hebd. 1 Adv.', 'Sabbato Hebd. 3 Adv.', 'Suscept. Reliquiarum']
Partition 449: 34 ['Ad Suffragium', 'Die 2 p. Epiphaniam', 'Die 5 p. Nat. Domini', 'Die 6 p. Nat. Domini', 'Dom. Adventus', 'Dom. per annum', 'Epiphania,8', 'Fer. 2 Hebd. 1 Adv.', 'Fer. 2 Hebd. 4 Adv.', 'Fer. 2 per annum', 'Fer. 3 Hebd. 1 Adv.', 'Fer. 3 Hebd. 4 Adv.', 'Fer. 3 per annum', 'Fer. 4 Hebd. 4 Adv.', 'Fer. 4 per annum', 'Fer. 5 Hebd. 4 Adv.', 'Fer. 5 per annum', 'Fer. 6 Hebd. 4 Adv.', 'Fer. 6 per annum', 'Hebd. 1 Adventus', 'Hebd. 1 Quad.', 'Hebd. 4 Adventus', 'Hebd. Quinquagesimae', 'Hebd. Septuagesimae', 'Hebd. de Passione', 'Oct. Joannis Evang.', 'Oct. Nat. Innocent.', 'Octava Epiphaniae', 'Octava Nat. Domini', 'Octava Stephani', 'Sabb. Septuagesimae', 'Sabbato Hebd. 4 Adv.', 'Sabbato per annum', 'Suff. Mariae Nat.']
Partition 476: 38 ['Amandi', 'Ambrosii', 'Antonii', 'Arnulfi Metensis', 'Augustini', 'Barnabae', 'Bartholomaei', 'Bernardi', 'Callisti', 'Christophori', 'Comm. unius Virginis Martyris', 'Crispini,Crispiniani', 'Cyrici', 'Decem Millium Martyrum', 'Dionysii et socii', 'Dionysii,8', 'Divisio Apostolorum', 'Dominici', 'Eligii', 'Fer. 6 Q.T. Quad.', 'Germani', 'Germani Parisien.', 'Helenae', 'Hieronimi', 'Jacobi', 'Leodegarii', 'Lucae', 'Martialis, Apost.', 'Martialis, Epi.', 'Matthiae', 'Medardi', 'Nazarii, Celsi', 'Octava Laurentii', 'Petri, Mart.', 'Remigii', 'Saturnini', 'Transl. Martini', 'Victoris et Soc.']
Partition 688: 11 ['Ad Mandatum', 'Dom. de Passione', 'Dom. in Palmis', 'Epiphania', 'Fer. 5 in Cena Dom.', 'Fer. 6 in Parasceve', 'Joannis Evang.', 'Nat. Innocentium', 'Nativitas Domini', 'Sabbato Sancto', 'Stephani']
Partition 571: 25 ['Assumptio Mariae', 'Caeciliae', 'Clementis', 'Decoll. Jo. Bapt.', 'Exaltatio Crucis', 'Hippolyti', 'Inventio Crucis', 'Joannis Baptistae', 'Joannis, Pauli', 'Laurentii', 'Marci', 'Mariae Magdalenae', 'Martini', 'Matthaei', 'Michaelis', 'Nativitas Mariae', 'Octava Apostolorum', 'Omnium Sanctorum', 'Pauli', 'Petri', 'Petri, Pauli', 'Petri, Pauli,8', 'Philippi, Jacobi', 'Transl. Benedicti', 'Vincula Petri']
Partition 794: 128 ['Acacii et sociorum', 'Adalberti', 'Aichardi', 'Andreae,8', 'Annae', 'Assumptio Mariae,8', 'Audoeni', 'Baboleni', 'Caroli Magni', 'Catharinae', 'Comm. Conjungium', 'Comm. plurimorum Martyrum TP', 'Comm. unius Abbatis', 'Comm. unius Apostoli', 'Comm. unius Confessoris Abbatis', 'Comm. unius Confessoris TP', 'Comm. unius Confessoris et Episcopi', 'Comm. unius Confessoris non Episcopus', 'Comm. unius Martyris Pontificis', 'Comm. unius Martyris TP', 'Comm. unius Martyris non Pontificis', 'Comm. unius Virg.', 'Comm. unius Virginis non Martyris', 'Commune Apostolorum', 'Commune Apostolorum TP', 'Commune BMV', 'Commune apostolorum', 'Commune plurimorum Martyrum TP', 'Commune unius Confessoris', 'Commune unius Confessoris Epi.', 'Commune unius Martyris', 'Commune unius Martyris TP', 'Compassio Mariae TP', 'Corporis Christi', 'Cuthberti', 'De BMV TP', 'De BMV post Pent.', 'De Corona Spinea', 'De Sancta Lancea', 'Dedic. S. Salvatoris', 'Dom. 25 p. Pent.', 'Dom. mensis Nov.', 'Dom. p. Assumptionem', 'Dom. p. Cor. Christi', 'Dom. p. Pent.', 'Dominici Silensis', 'Dorotheae', 'Dunstani', 'Edmundi', 'Elisabeth Hung.', 'Eustachii', 'Firmini', 'Floriani', 'Gaugerici', 'Genulfi', 'Geraldi', 'Hedwigis', 'Hermagorae,Fortunati', 'Hilarii Arelatensis', 'In Dedicat. Eccl. TP', 'Inventio Stephani', 'Joannis Baptistae,8', 'Joannis Port. Lat.', 'Justi', 'Justinae, Cypriani', 'Ladislai', 'Ludmilae', 'Ludmillae', 'Margaritae', 'Mariae ad Nives', 'Marinae', 'Marthae', 'Martini,8', 'Meginrati', 'Monicae', 'Nativitas Mariae,8', 'Nicasii', 'Oct. Ascens. Domini', 'Oct. Om. Sanctorum', 'Octava Amandi', 'Octava Apostolorum Petri et Pauli', 'Octava Assumptionis', 'Octava Joannis Bapt.', 'Octava Martialis', 'Octava Martini', 'Octava Nat. Mariae', 'Octava Tr. Benedicti', 'Octava de Trinitate', 'Omnium Sanctorum,8', 'Oswaldi, Epi.', 'Pancratii et Soc.', 'Patriarcharum', 'Philiberti', 'Praesentatio Mariae', 'Procopii Sázaviensis', 'Purificatio Mariae,8', 'Recollectio Mariae', 'Relatio Vedasti', 'Reliquiarum', 'Remacli', 'Rictrudis', 'Sabae', 'Servatii', 'Stephani, Reg.', 'Stephani,8', 'Suff. Om. Sanctorum', 'Swithuni', 'Thomae de Aquino', 'Tiburtii, Valeriani, Maximi', 'Tr. Kunegundis', 'Transfiguratio Dom.', 'Transl. Adalberti', 'Transl. Baboleni', 'Transl. Benedicti,8', 'Transl. Francisci', 'Transl. Indalaetii', 'Transl. Lamberti', 'Transl. Stanislai', 'Transl. Stanislai Episcopi', 'Transl. Trium Regum', 'Transl. Wolfgangi', 'Tres Mariae', 'Ursulae', 'Valeriae', 'Visitatio Mariae', 'Wenceslai', 'Wulstani', 'XI milium Virginum']
Partition 477: 17 ['Ascensio Domini', 'De Trinitate', 'Dom. 2 p. Pascha', 'Dom. 3 p. Pascha', 'Dom. 4 p. Pascha', 'Dom. 5 p. Pascha', 'Dom. Pentecostes', 'Dom. Resurrect.,8', 'Dom. Resurrectionis', 'Dom. p. Ascensionem', 'Fer. 2 p. Pascha', 'Fer. 3 p. Pascha', 'Fer. 4 p. Pascha', 'Fer. 5 p. Pascha', 'Fer. 6 p. Pascha', 'Octava Paschae', 'Sabbato in Albis']
Partition 965: 35 ['Aegidii', 'Afrae', 'Antonini', 'Bonifacii', 'Chrysanthi, Dariae', 'Columbani', 'Comm. Virginum', 'Comm. plur. Conf.', 'Comm. plur. Mart.', 'Comm. un. Conf.Pont.', 'Comm. unius Conf.', 'Comm. unius Mart.', 'Commune plurimorum Martyrum', 'Constantii', 'Emmerami', 'Fidis', 'Galli', 'Gereonis et soc.', 'Januarii et Soc.', 'Julianae', 'Kiliani et Soc.', 'Lamberti', 'Leonardi', 'Magni', 'Oswaldi, Reg.', 'Othmari', 'Pantaleonis', 'Pelagii', 'Pirmini', 'Quintini', 'Romani', 'Udalrici', 'Viti et sociorum', 'Walburgae', 'Willibrordi']
Partition 542: 11 ['Agathae', 'Agnetis', 'Andreae', 'Annuntiatio Mariae', 'Benedicti', 'Cathedra Petri', 'Fabiani, Sebastiani', 'Gregorii', 'Luciae', 'Purificatio Mariae', 'Vincentii']
Partition 1025: 16 ['Ad Missam', 'Ad Processionem', 'Comm. unius Virginis', 'De BMV', 'De BMV Adv.', 'De BMV Nat.', 'De Sancta Cruce', 'Dom. 1 p. Pent.', 'Fer. 2 in Letaniis', 'Fer. 4 in Letaniis', 'Georgii', 'In Dedicatione Ecclesiae', 'Mauritii et sociorum', 'Pro defunctis', 'Vig. Assump. Mariae', 'Vigilia Pentecostes']
Partition 469: 12 ['Comm. Apostolorum', 'Comm. Evangelistarum', 'Comm. plurimorum Confessorum', 'Comm. plurimorum Martyrum', 'Comm. plurimorum Virginum', 'Comm. unius Confessoris', 'Comm. unius Confessoris Pontificis', 'Comm. unius Confessoris non Pontificis', 'Comm. unius Martyris', 'Hymni', 'In tempore Nat.', 'Invitatoria']
Partition 623: 16 ['Antonii Patavini', 'Appar. Michaelis', 'Clarae', 'Comm. Apostolorum TP', 'Comm. plurimorum Confessorum Pontificum', 'Comm. plurimorum Confessorum non Pontificum', 'De Sanctis', 'Dom. 5 Quadragesimae', 'Dominica TP', 'Dominica in estate', 'Francisci', 'In tempore Paschae', 'In tempore Quad.', 'Octava Paschae,8', 'Suff. Crucis', 'Syri']
Partition 848: 17 ['Circumcisio Domini', 'Dom. 1 p. Epiph.,8', 'Dom. 1 p. Epiphaniam', 'Dom. 2 p. Epiph.', 'Dom. 3 p. Epiph.', 'Dom. Quadragesimae', 'Dom. p. Nat. Dom.', 'Fer. 2 Hebd. 1 Quad.', 'Fer. 2 Maj. Hebd.', 'Fer. 2 de Passione', 'Fer. 3 Maj. Hebd.', 'Fer. 4 Cinerum', 'Fer. 4 Maj. Hebd.', 'Fer. 4 Q.T. Adventus', 'Sabb. Q.T. Adventus', 'Sabb. de Passione', 'Sabbato post Cineres']
Partition 874: 34 ['Fer. 2 Hebd. 2 Quad.', 'Fer. 2 Hebd. 3 Quad.', 'Fer. 2 Hebd. 4 Quad.', 'Fer. 3 Hebd. 1 Quad.', 'Fer. 3 Hebd. 2 Quad.', 'Fer. 3 Hebd. 3 Quad.', 'Fer. 3 Hebd. 4 Quad.', 'Fer. 3 de Passione', 'Fer. 4 Hebd. 1 Quad.', 'Fer. 4 Hebd. 2 Quad.', 'Fer. 4 Hebd. 3 Quad.', 'Fer. 4 Hebd. 4 Quad.', 'Fer. 4 Q.T. Pent.', 'Fer. 4 de Passione', 'Fer. 5 Hebd. 1 Quad.', 'Fer. 5 Hebd. 2 Quad.', 'Fer. 5 Hebd. 3 Quad.', 'Fer. 5 Hebd. 4 Quad.', 'Fer. 5 de Passione', 'Fer. 5 post Cineres', 'Fer. 6 Hebd. 1 Quad.', 'Fer. 6 Hebd. 2 Quad.', 'Fer. 6 Hebd. 3 Quad.', 'Fer. 6 Hebd. 4 Quad.', 'Fer. 6 Q.T. Adventus', 'Fer. 6 de Passione', 'Fer. 6 post Cineres', 'In Letaniis', 'Sabb. Hebd. 1 Quad.', 'Sabb. Hebd. 2 Quad.', 'Sabb. Hebd. 3 Quad.', 'Sabb. Hebd. 4 Quad.', 'Sabbato Q.T. Adventus', 'Vig. Ascensio Domini']
Partition 584: 56 ['Abdonis, Sennis', 'Adriani', 'Agapiti', 'Alexandri et Soc.', 'Apollinaris', 'Apostolorum et Evangelistarum', 'Basilidis et Soc.', 'Chrysogoni', 'Comm. unius Apostolus', 'Cornelii, Cypriani', 'Cosmae, Damiani', 'Cyriaci et Soc.', 'Dedic. S.Salv., Mar.', 'Donati', 'Euphemiae', 'Felicis, Adaucti', 'Felicissimi, Agapiti', 'Felicitatis', 'Genesii', 'Georgii, Adalberti', 'Gervasii, Protasii', 'Gordiani, Epimachi', 'Gorgonii', 'Hermetis', 'In tempore belli', 'Laurentii,8', 'Luciae, Germiniani', 'Marcellini, Petri', 'Marci, Marcellini', 'Marci, Pont.', 'Mennae', 'Nicomedis', 'Odilonis', 'Praxedis', 'Primi, Feliciani', 'Pro Sacerdote', 'Pro ordinatione Episcopi', 'Processi, Martiniani', 'Proti, Hiacinthi', 'Quat. Coronatorum', 'Sabinae', 'Sebastiani', 'Septem Fratrum', 'Simonis, Judae', 'Simplicii et Soc.', 'Sixti', 'Stephani, Pont.', 'Theodori Tiro', 'Tiburtii', 'Tiburtii, Susannae', 'Tiburtii, Valeriani', 'Urbani', 'Vig. Joannis Bapt.', 'Vig. Om. Sanctorum', 'Vigilia Petri', 'Vitalis']
Partition 782: 34 ['Adventus, dom. 1', 'Adventus, dom. 2', 'Adventus, dom. 3', 'Adventus, dom. 4', 'Angeli Custodis', 'Assumptio Mariae, infra oct.', 'De BMV post Epiph.', 'Dom. mensis Octobris', 'Dom. mensis Septembris', 'Dominica in Albis (Octava Paschae)', 'Fabiani et Sebastiani', 'Geraldi Archiepiscopi Bracharensis', 'Joannis Baptistae., vig.', 'Jonnis Baptistae, decol.', 'Nativitas Domini, vig.', 'Pauli, conversio', 'Pentecostes', 'Petri et Pauli', 'Petri, Pauli, vig.', 'Philippi et Jacobi', 'Purificatio Mariae [Presentationis Domini]', 'Quadrag., hebd. 1, fer. 2', 'Quadragesimae, dom. 1', 'Quadragesimae, dom. 2', 'Quadragesimae, dom. 3', 'Quadragesimae, dom. 4', 'Quinquagesimae, dom.', 'Sanctissimae Trinitatis', 'Septuagesimae, dom.', 'Sexagesimae, dom.', 'Stephani, inventio', 'Thomae', 'Transfiguratio Domini', 'undetermined']
Partition 964: 16 ['Agnetis,8', 'Dom. post Ascensionem', 'Felicis', 'Felicis Nolani', 'In Letaniis maj.', 'Marcelli', 'Marcelli, Pont.', 'Priscae', 'Pro infirmis', 'Pro iter agentibus', 'Pro pluvia', 'Sabbato Q.T. Pent.', 'Sabbato Q.T. Sept.', 'Silvestri', 'Timothei', 'Valentini']
Partition 746: 21 ['1D', '2D', '3D', '6f5', 'Corp', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D70', 'Ded.Eccl.', 'H6/S', 'H6/f5', 'H6/f6', 'Joh.ap.', 'Mort', 'Nat', 'Purif.BMV', 'Trin']
Partition 621: 12 ['Dom. 2 p. Pascha,8', 'Dom. 3 p. Pascha,8', 'Dom. 4 p. Pascha,8', 'Dom. Pentecostes,8', 'Dom. p. Epiphaniam', 'Fer. 2 Pent.', 'Fer. 3 Pent.', 'Fer. 3 in Letaniis', 'Fer. 4 Pent.', 'Fer. 5 Pent.', 'Fer. 6 Pent.', 'Sabbato Pent.']
Partition 524: 9 ['Ad Benedicite', 'Additamenta', 'Alexandri et sociorum', 'Ascensio Domini,8', 'Briccii', 'Dionysii', 'Juliani', 'Mauritii', 'Symphoriani']
Partition 778: 14 ['Ad Completorium', 'Ad Magnificat', 'De Esther', 'De Job', 'De Judith', 'De Machabaeis', 'De Prophetis', 'De Regum', 'De Sanctis TP', 'De Sapientia', 'De Tobia', 'Hebd. per annum', 'In Dedicatione Eccl.', 'Suff. Mariae']
Partition 705: 25 ['Ded.Mont.S.Michaelis', 'Dom. 10 p. Pent.', 'Dom. 11 p. Pent.', 'Dom. 12 p. Pent.', 'Dom. 13 p. Pent.', 'Dom. 14 p. Pent.', 'Dom. 15 p. Pent.', 'Dom. 16 p. Pent.', 'Dom. 17 p. Pent.', 'Dom. 18 p. Pent.', 'Dom. 19 p. Pent.', 'Dom. 2 p. Pent.', 'Dom. 20 p. Pent.', 'Dom. 21 p. Pent.', 'Dom. 22 p. Pent.', 'Dom. 23 p. Pent.', 'Dom. 24 p. Pent.', 'Dom. 3 p. Pent.', 'Dom. 4 p. Pent.', 'Dom. 5 p. Pent.', 'Dom. 6 p. Pent.', 'Dom. 7 p. Pent.', 'Dom. 8 p. Pent.', 'Dom. 9 p. Pent.', 'Oct. Apostolorum,8']
Partition 1077: 41 ['Aciscli', 'Aemiliani Cucullati', 'Allisionis Infantum', 'Assumptio Mariae (Hispanic rite)', 'Carnes Tollendas', 'Columbae', 'Commune Virginum', 'Commune unius Virginis', 'Cucuphatis', 'De Sacratione Baselice', 'De uno defuncto', 'De uno justi', 'Dom. Quotidiano', 'Engratiae', 'Eugeniae', 'Eulaliae Barcinonensis', 'Eulaliae Emeritensis', 'Exspectationis BMV', 'Felicis Gerundae', 'Fer. 5 de Letanias Apostolicas', 'Fer. 6 Hebd. 5 Quad.', 'Fer. 6 de Letanias Apostolicas', 'Fest. per annum', 'Fructuosi, Augurii et Eulogii', 'Hebd. Adventus', 'Hebd. Sancta', 'In tempore Adventus', 'Jacobi fratris Domini', 'Justae, Rufinae', 'Justi, Pastoris', 'Leocadiae', 'Letanias', 'Letanias Apostolicas', 'Letanias Canonicas', 'Letanias de Clade', 'Primitis', 'Pro defunctis Sacerdotibus', 'Pro uno infirmo', 'Sabb. Quadragesimae', 'Suff. Adventus', 'Torquati et sociorum']
Partition 963: 26 ['De Trinitate,8', 'Fer. 2 Hebd. 3 Pasc.', 'Fer. 2 Hebd. 4 Pasc.', 'Fer. 2 Hebd. 5 Pasc.', 'Fer. 2 p. Ascensio.', 'Fer. 2 p. Oct.Pasch.', 'Fer. 3 Hebd. 3 Pasc.', 'Fer. 3 Hebd. 4 Pasc.', 'Fer. 3 p. Oct.Pasch.', 'Fer. 4 Hebd. 3 Pasc.', 'Fer. 4 Hebd. 4 Pasc.', 'Fer. 4 Hebd. 5 Pasc.', 'Fer. 4 p. Oct.Pasch.', 'Fer. 5 p. Oct.Pasch.', 'Fer. 6 p. Ascensio.', 'Fer. 6 p. Oct. Asc.', 'Fer. 6 p. Oct.Pasch.', 'Feria 2 TP', 'Hebd. 3 p. Pascha', 'Hebd. TP', 'Octava Pentecostes', 'Sabb. p. Ascensionem', 'Sabb. p. Oct. Asc.', 'Sabb. p. Oct. Pasch.', 'Sabbato TP', 'Suff. Mariae Adv.']

Level 1:
11
Partition 2: 162 ['Acacii et sociorum', 'Ad Benedicite', 'Adalberti', 'Additamenta', 'Aichardi', 'Alexandri et sociorum', 'Andreae,8', 'Annae', 'Ascensio Domini,8', 'Assumptio Mariae,8', 'Audoeni', 'Baboleni', 'Blasii', 'Briccii', 'Caroli Magni', 'Catharinae', 'Comm. Apostolorum', 'Comm. Conjungium', 'Comm. Evangelistarum', 'Comm. plurimorum Confessorum', 'Comm. plurimorum Martyrum', 'Comm. plurimorum Martyrum TP', 'Comm. plurimorum Virginum', 'Comm. unius Abbatis', 'Comm. unius Apostoli', 'Comm. unius Confessoris', 'Comm. unius Confessoris Abbatis', 'Comm. unius Confessoris Pontificis', 'Comm. unius Confessoris TP', 'Comm. unius Confessoris et Episcopi', 'Comm. unius Confessoris non Episcopus', 'Comm. unius Confessoris non Pontificis', 'Comm. unius Martyris', 'Comm. unius Martyris Pontificis', 'Comm. unius Martyris TP', 'Comm. unius Martyris non Pontificis', 'Comm. unius Virg.', 'Comm. unius Virginis non Martyris', 'Commune Apostolorum', 'Commune Apostolorum TP', 'Commune BMV', 'Commune apostolorum', 'Commune plurimorum Martyrum TP', 'Commune unius Confessoris', 'Commune unius Confessoris Epi.', 'Commune unius Martyris', 'Commune unius Martyris TP', 'Compassio Mariae TP', 'Conceptio Mariae', 'Conversio Pauli', 'Corporis Christi', 'Cuthberti', 'De BMV TP', 'De BMV post Pent.', 'De BMV post Purif.', 'De Corona Spinea', 'De Sancta Lancea', 'Dedic. S. Salvatoris', 'Dionysii', 'Dom. 25 p. Pent.', 'Dom. mensis Nov.', 'Dom. p. Assumptionem', 'Dom. p. Cor. Christi', 'Dom. p. Pent.', 'Dominici Silensis', 'Dorotheae', 'Dunstani', 'Edmundi', 'Elisabeth Hung.', 'Eustachii', 'Firmini', 'Floriani', 'Gaugerici', 'Genulfi', 'Geraldi', 'Hedwigis', 'Hermagorae,Fortunati', 'Hilarii', 'Hilarii Arelatensis', 'Hymni', 'In Dedicat. Eccl. TP', 'In tempore Nat.', 'Inventio Stephani', 'Invitatoria', 'Joannis Baptistae,8', 'Joannis Port. Lat.', 'Juliani', 'Justi', 'Justinae, Cypriani', 'Ladislai', 'Ludmilae', 'Ludmillae', 'Margaritae', 'Mariae ad Nives', 'Marinae', 'Marthae', 'Martini,8', 'Mauri', 'Mauritii', 'Meginrati', 'Monicae', 'Nativitas Mariae,8', 'Nicasii', 'Nicolai', 'Oct. Ascens. Domini', 'Oct. Om. Sanctorum', 'Octava Agnetis', 'Octava Amandi', 'Octava Andreae', 'Octava Apostolorum Petri et Pauli', 'Octava Assumptionis', 'Octava Joannis Bapt.', 'Octava Martialis', 'Octava Martini', 'Octava Nat. Mariae', 'Octava Tr. Benedicti', 'Octava de Trinitate', 'Omnium Sanctorum,8', 'Oswaldi, Epi.', 'Pancratii et Soc.', 'Patriarcharum', 'Philiberti', 'Praesentatio Mariae', 'Procopii Sázaviensis', 'Purificatio Mariae,8', 'Recollectio Mariae', 'Relatio Vedasti', 'Reliquiarum', 'Remacli', 'Rictrudis', 'Sabae', 'Scholasticae', 'Servatii', 'Stephani, Reg.', 'Stephani,8', 'Suff. Om. Sanctorum', 'Swithuni', 'Symphoriani', 'Thomae Apost.', 'Thomae Cant.', 'Thomae de Aquino', 'Tiburtii, Valeriani, Maximi', 'Tr. Kunegundis', 'Transfiguratio Dom.', 'Transl. Adalberti', 'Transl. Baboleni', 'Transl. Benedicti,8', 'Transl. Francisci', 'Transl. Indalaetii', 'Transl. Lamberti', 'Transl. Stanislai', 'Transl. Stanislai Episcopi', 'Transl. Trium Regum', 'Transl. Wolfgangi', 'Tres Mariae', 'Ursulae', 'Valeriae', 'Vedasti', 'Visitatio Mariae', 'Wenceslai', 'Wulstani', 'XI milium Virginum']
Partition 12: 65 ['Circumcisio Domini', 'Dom. 1 Adventus', 'Dom. 1 Quadragesimae', 'Dom. 1 p. Epiph.,8', 'Dom. 1 p. Epiphaniam', 'Dom. 2 Adventus', 'Dom. 2 Quadragesimae', 'Dom. 2 p. Epiph.', 'Dom. 3 Adventus', 'Dom. 3 Quadragesimae', 'Dom. 3 p. Epiph.', 'Dom. 4 Adventus', 'Dom. 4 Quadragesimae', 'Dom. Quadragesimae', 'Dom. Quinquagesimae', 'Dom. Septuagesimae', 'Dom. Sexagesimae', 'Dom. p. Nat. Dom.', 'Fer. 2 Hebd. 1 Quad.', 'Fer. 2 Hebd. 2 Quad.', 'Fer. 2 Hebd. 3 Quad.', 'Fer. 2 Hebd. 4 Quad.', 'Fer. 2 Maj. Hebd.', 'Fer. 2 de Passione', 'Fer. 3 Hebd. 1 Quad.', 'Fer. 3 Hebd. 2 Quad.', 'Fer. 3 Hebd. 3 Quad.', 'Fer. 3 Hebd. 4 Quad.', 'Fer. 3 Maj. Hebd.', 'Fer. 3 de Passione', 'Fer. 4 Cinerum', 'Fer. 4 Hebd. 1 Quad.', 'Fer. 4 Hebd. 2 Quad.', 'Fer. 4 Hebd. 3 Quad.', 'Fer. 4 Hebd. 4 Quad.', 'Fer. 4 Maj. Hebd.', 'Fer. 4 Q.T. Adventus', 'Fer. 4 Q.T. Pent.', 'Fer. 4 de Passione', 'Fer. 5 Hebd. 1 Quad.', 'Fer. 5 Hebd. 2 Quad.', 'Fer. 5 Hebd. 3 Quad.', 'Fer. 5 Hebd. 4 Quad.', 'Fer. 5 de Passione', 'Fer. 5 post Cineres', 'Fer. 6 Hebd. 1 Quad.', 'Fer. 6 Hebd. 2 Quad.', 'Fer. 6 Hebd. 3 Quad.', 'Fer. 6 Hebd. 4 Quad.', 'Fer. 6 Q.T. Adventus', 'Fer. 6 de Passione', 'Fer. 6 post Cineres', 'In Letaniis', 'Nativitas Domini,8', 'Sabb. Hebd. 1 Quad.', 'Sabb. Hebd. 2 Quad.', 'Sabb. Hebd. 3 Quad.', 'Sabb. Hebd. 4 Quad.', 'Sabb. Q.T. Adventus', 'Sabb. de Passione', 'Sabbato Q.T. Adventus', 'Sabbato post Cineres', 'Vig. Ascensio Domini', 'Vigilia Epiphaniae', 'Vigilia Nat. Domini']

In [50]:
for level in sigla_partitions:
    print(f'Level {level}:')
    print(len(sigla_partitions[level]))
    for partition, sigla in sigla_partitions[level].items():
        print(f'Partition {partition}: {len(sigla)} : {sorted(sigla)}')
    print()

Level 0:
34
Partition 26: 20 : ['A-Gu 29 (olim 38/8 f.)', 'A-KN CCl 1010', 'A-KN CCl 1011', 'A-KN CCl 1015', 'A-KN CCl 1017', 'A-Wda C-11', 'CH-SGs 390', 'CZ-Pu XIV.B.13', 'D-MZb A', 'D-Mbs Clm 4303', 'DK-Kk Gl. Kgl. S. 3449 8o [02] II', 'F-Pn Lat. 9449', 'GB-Lbl Add MS 30847', 'H-Bu lat. 118', 'HR-Hf Cod. C Nr. 4', 'HR-Hf Cod. D Nr. 5', 'I-BV V 19', 'I-MC 542', 'PL-Kkar Ms.2 (rkp. Perg. 14)', 'PL-Kkar Ms.5 (rkp. Perg. 13)']
Partition 117: 6 : ['A-Gu 30 (olim 38/9 f.)', 'CZ-Bu R 387', 'CZ-Pu VI E 13', 'CZ-Pu XII C 3', 'CZ-Pu XIII C 4', 'CZ-Pu XIV C 20']
Partition 247: 3 : ['A-LIb 290 (olim 183; olim Gamma p 19)', 'A-Wn Cod. 1890', 'CZ-Pu VI G 11']
Partition 0: 12 : ['A-SF XI 480', 'CH-E 611', 'CH-SGs 388', 'D-B Mus. 40047', 'D-KA Aug. LX', 'D-KNd 215', 'D-Sl HB.I.55', 'E-Tc 44.1', 'F-Pn Latin 12044', 'GB-Ob MS. Laud Misc. 284', 'I-PCd cod. 65', 'I-Rv C.5']
Partition 95: 6 : ['B-TOb 63 (olim V)', 'B-TOb 64 (olim IV)', 'CDN-Hsmu M2149.L4 1554', 'CZ-Pu VI.E.4c', 'D-KNd 1161', 'I-VCd CLXX']
Partition 28: 13 : ['A-KN CCl 1013', 'CDN-Ttfl MSS 09700', 'CZ-Pn XV A 10', 'CZ-Pst DE I 7', 'D-W Cod. Guelf. 29 Helmst. (Heinemann-Nr. 32)', 'E-Bbc M 663', 'E-Bbc M 705', 'E-Bbc M 706', 'E-H Ms. 2', 'F-Pn NAL 1411', 'PL-PŁsem MsEPl 12', 'PL-Wn  rps 12720 V', 'SK-Bra BAIII ECLad.6']
Partition 49: 8 : ['CZ-Pn XII A 24', 'CZ-Pu Pu XIV A 19', 'D-B Theol. Lat. Qu. 149', 'E-BAR, s.s.', 'E-H Ms. 7 (ant. 5)', 'E-VI Mss. 113-114', 'PL-GD Mar. F 408', 'PL-STAb ms. 2']
Partition 20: 13 : ['A-KR Schachtel VI/258', 'A-VOR 287 (olim XXIX)', 'CDN-Mrb MS Medieval 0234', 'Cantus MA Impr. 1537', 'F-CA 38 (olim 40)', 'GB-AB 20541 E', 'GB-Cu Mm.ii.9', 'GB-WO F. 160 (olim 1247) (facsimile)', 'GB-WO F. 160 (olim 1247) (with hymnal)', 'NL-Uu Ms. 406 (shelfmark 3 J 7)', 'PL-KIk Ms. 1', 'PL-Klk 1', 'TR-Itks Deissmann 42']
Partition 17: 6 : ['F-Pn Latin 15181', 'F-Pn NAL 1236', 'F-TOm 149', 'SI-Lna 18 (olim 17)', 'SK-BRsa SNA 2', 'SK-BRsa SNA 4']
Partition 138: 7 : ['E-MO Ms. 72', 'P-AR Res. Ms. 021', 'P-AR Res. Ms. 025', 'P-BRs Ms. 028', 'P-BRs Ms. 032', 'P-EVpc 000', 'P-Ln RES. 253 P.']
Partition 65: 10 : ['A-Wda D-4', 'A-Wn Cod. 1799**', 'D-AAm G 20', 'E-Bbc M 888', 'E-SI MS 9', 'F-AS 465 (CGM 893)', 'F-CA Impr. XVI C 4', 'F-VAL 114', 'PL-WRu I F 401', 'PL-WRu Ms. R 503']
Partition 114: 9 : ['CH-Fco Ms. 2', 'D-Ma 12o Cmm 1', 'I-Ac 693', 'I-Ac 694', 'I-Ad 5', 'I-CHV s.c.', 'I-Nn vi. E. 20', 'US-Cn 24', 'V-CVbav lat. 8737']
Partition 69: 16 : ['Cantus GOTTSCHALK', 'D-BAs Msc.Lit.25 (olim Ed.IV.11)', 'E-Bbc M 662', 'E-Gs ms. 45 (olim Sant Feliu, 20)', 'F-AI 44', 'F-Pn Lat. 17296', 'F-Pn Latin 1085', 'F-Pn Latin 1090', 'F-Pn Latin 1240', 'F-Pn NAL 1535', 'GB-Lbl Add MS 30849', 'I-Far s.c.', 'I-Fl Conv. sopp. 560', 'I-Lc 601', 'I-MZ 15/79', 'V-CVbav San Pietro B.79']
Partition 58: 17 : ['CH-SGs Cod 378', 'CH-SGs Cod 380', 'CH-SGs Cod 484', 'D-Mbs Clm 14965b', 'D-Mbs Clm 4306', 'E-SA 6', 'F-CA Ms 0078 (79)', 'F-LA Ms 263', 'F-Pn Lat. 10510', 'F-Pn Lat. 1118', 'F-Pn Lat. 1135', 'F-Pn Lat. 13252', 'F-Pn Lat. 9448', 'F-SO 596', 'GB-Ccc Ms 473', 'GB-Lbl printed book IB.6753 (Augsburg Antiphoner 1495, olim AA Impr. 1495)', 'SK-BRsa SNA 17']
Partition 172: 16 : ['Antifonario s.s.', 'CZ-Pu VI G 3a', 'D-MZb E', 'D-Mbs Clm 4305', 'D-W Cod. Guelf. 28 Helmst. (Heinemann-Nr. 31)', 'E-Bbc Ms. 2322', 'E-E L. III. 3.', 'E-E L. III. 4.', 'E-H Ms. 9 (ant. 25)', 'E-LUc s.s.', 'F-CH Ms 0050', 'F-Pn NAL 1412', 'F-R 248 (olim  A. 339)', 'H-Bu lat. 122', 'HR-Hf Cod. E Nr. 3', 'PL-PŁsem MsEPl 12']
Partition 252: 6 : ['E-Bbc Ms. 619', 'E-Tc 44.2', 'GB-Lbl Add MS 30848', 'GB-Lbl Add MS 30850', 'GB-Ob MS. Canon. Liturg. 202', 'I-AO 6']
Partition 255: 29 : ['CH-E Codex 121', 'CH-SGs Cod 338', 'CH-SGs Cod 340', 'CH-SGv VadSlg Ms 0295', 'D-B Ms mus 40078', 'D-BAa Msc Lit 6', 'D-Ful Aa 0006', 'D-Mbs Clm 03005', 'F-AI Ms 0044', 'F-CA Ms 0061 (62)', 'F-CHRm Ms 0047 (40)', 'F-Collection privée Mont-Renaud', 'F-LA Ms 118', 'F-LA Ms 239', 'F-NS Ms 0004', 'F-Pm Ms 0384', 'F-Pn Lat. 1087', 'F-Pn Lat. 12050', 'F-Pn Lat. 2291', 'F-Pn NAL 1669', 'GB-Lbl Egerton 857', 'I-BGc MA 239 (Gamma III.18)', 'I-BV 34', 'I-Bc Q 09', 'I-Tn G.V.20', 'Reconstitution Sacramentaire de Tours (TU1)', 'V-CVbav Archivio di San Pietro F.22', 'V-CVbav Vat. lat. 4770', 'V-CVbav Vat. lat. 5319']
Partition 118: 12 : ['A-KN CCl 1018', 'A-KN CCl 589', 'A-Wda C-10', 'B-Gu Hs BKT.006', 'CH-SGs 391', 'CZ-R R 17', 'D-FUl Aa 55', 'D-MZb C', 'I-BV V 20', 'NL-ZUa 6', 'PL-Kkar Ms.3 (rkp. Perg. 15)', 'US-Cai 1911.142b']
Partition 116: 16 : ['A-KN CCl 1012', 'CZ-Pn (Praha) XII A 21', 'CZ-Pu XII E 15c', 'D-MZb D', 'D-Mbs Clm 4304', 'F-Pn Lat. 1030', 'F-Pn Latin 12601', 'F-Pn Latin 15182', 'H-Bu lat. 121', 'NZ-Wt MSR-03', 'PL-Kkar Ms.1 (rkp. Perg. 12)', 'PL-Kkar Ms.4 (rkp. Perg. 20)', 'SI-Lna 19 (olim 18)', 'SK-Bra BAI ECLad.3', 'SK-Sk 2', 'US-NYcubl MS 1']
Partition 246: 4 : ['E-SAu Ms 2637', 'P-AR Res. Ms. 016', 'P-BRs Ms. 034', 'P-Ln Iluminado 084']
Partition 256: 10 : ['D-Kl Theol. quart 0015', 'D-MZb B', 'E-Mn MSS/10110', 'E-Tc 35.5', 'F-LA Ms 240', 'F-Pn Lat. 1134', 'F-Pn Lat. 1136', 'F-VN Ms 0759', 'NL-Uu Hs. 0062', 'SK-BRnm MUS I 78']
Partition 264: 18 : ['B-Br Ms II 3823', 'D-KA Lichtenthal 002', 'E-Bbc M 648', 'E-Mh Cód. 51', 'F-AN Ms 0091', 'F-AS Ms 0437 (cat. 1011)', 'F-CA Ms 0075 (76)', 'F-LA Ms 236', 'F-PR Ms 0012', 'F-Pn Lat. 12584', 'F-Pn Lat. 780', 'F-Pn Lat. 9439', 'F-Pn NAL 1414', 'F-SOM Ms 0252', 'GB-Lbl Harley 4951', 'I-BGc MA 150 (Psi III.8)', 'PL-WRu I F 414', 'V-CVbav Ross.0076']
Partition 231: 9 : ['B-Br Ms 10127-44', 'CH-Cobodmer C 0074', 'CH-SGs Cod 339', 'D-BAa Msc Lit 5', 'D-BAa Msc Lit 7', 'D-LEu Ms Thomas 391', 'F-Pn Lat. 17436', 'GB-Dru Cosin V.V.6', 'US-Baw W.11']
Partition 220: 8 : ['A-Wn Cod. 1812', 'H-Bn Clmae 172a, 172b', 'H-Efkö MS I. 1 a-b', 'H-Efkö MS I. 3. a', 'RO-Sb Ms. 759', 'SK-BRa EC Lad. 3, EL 18', 'TR-Itks 2429', 'TR-Itks 42']
Partition 123: 6 : ['E-H Ms. 8 (ant. 6)', 'E-Tc 35.4', 'GB-Lbl Add MS 30846', 'H-Bu lat. 119', 'HR-Hf Cod. F Nr. 6', 'PL-WRzno Rkp. 12025/IV']
Partition 207: 7 : ['D-Mbs Clm 02542', 'D-Sl HB I 246', 'E-Bbc M 785', 'F-RS Ms 0221', 'F-VAL Ms 0121', 'GB-Lbl Add MS 30845', 'GB-Lbl Additional 18032']
Partition 197: 26 : ['CH-P 18', 'CH-ROM Ms. liturg. FiD 5', 'CZ-Bm A 7115', 'D-HEu Cod. Sal. X,007', 'D-KNd Ms 1001b', 'D-KWsr Drachenfels-Missale', 'E-Bbc M 1147', 'E-Mh Cód. 18', 'E-Mn Mss/1361', 'F-CA Ms 0060 (61)', 'F-LG Ms 0002 (17)', 'F-Pa Ms 0197', 'F-Pn Lat. 17307', 'F-Pn Lat. 833', 'F-Pn Lat. 904', 'F-Pn NAL 1235', 'F-Pn NAL 1890', 'NL-Uu Hs. 0415', 'PL-Kl RL 1', 'PL-SAk 40', 'PL-WRu I F 413', 'PL-WRu I F 416', 'PL-Wn Rps 12496 IV', 'PL-Wn rps 12722 V', 'US-NYcub Western MS 097', 'US-PHf Lewis E 158']
Partition 327: 9 : ['CZ-OLu M III 6', 'CZ-Pn XIII B 2', 'CZ-Pu XIII A 5c', 'D-Mbs Clm 02541', 'E-Bbc M 784', 'E-Mh Cód. 45', 'F-Pn Lat. 18010', 'F-Pn Lat. 9436', 'F-Togs Ms 001']
Partition 314: 9 : ['A-Gu Ms 0807', 'A-KN Cod 588', 'A-KN Cod 73', 'CH-SGs Cod 342', 'CH-SGs Cod 343', 'CH-SGs Cod 374', 'CH-SGs Cod 376', 'CZ-R R 418', 'D-TRp Hs 187']
Partition 217: 7 : ['CH-SGs Cod 375', 'D-DS Hs 0545', 'D-W Cod Guelf Helmst 1008', 'F-Pa Ms 0135', 'F-Pn Lat. 1132', 'F-Pn Lat. 903', 'F-Pn Lat. 9441']
Partition 317: 8 : ['CH-SGs Cod 381', 'CZ-Pn XIV D 12', 'CZ-R R 396', 'E-Bbc Ms. 1805', 'F-AUT Ms S 0010 (8*)', 'F-AUT Ms S 0012 (11)', 'F-G Ms 84 (Ms. 395 Rés.)', 'PL-WRu I F 411']
Partition 237: 6 : ['E-Bbc M 889', 'E-Bbc Ms. 3180', 'F-Pn Lat. 1121', 'F-Pn Lat. 909', 'F-SEm Ms 018', 'SK-BRsa SNA 67']
Partition 299: 5 : ['F-CO Ms 0444 (217)', 'F-RS Ms 0264', 'SK-BRl Rkp. 387', 'SK-Bra BMI EC Lad.3 EL18', 'SK-Sk Graduale Scepusiense Nr.1']
Partition 343: 6 : ['E-L Ms 8', 'E-Mh Cod. 30', 'E-Tc 35.6', 'GB-Lbl Add MS 30844', 'GB-Lbl Add MS 30851', 'I-VEcap Codex Veronensis LXXXIX']

Level 1:
7
Partition 42: 77 : ['A-Gu 29 (olim 38/8 f.)', 'A-KN CCl 1010', 'A-KN CCl 1011', 'A-KN CCl 1013', 'A-KN CCl 1015', 'A-KN CCl 1017', 'A-Wda C-11', 'B-TOb 63 (olim V)', 'B-TOb 64 (olim IV)', 'CDN-Hsmu M2149.L4 1554', 'CDN-Ttfl MSS 09700', 'CH-SGs 390', 'CH-SGs Cod 378', 'CH-SGs Cod 380', 'CH-SGs Cod 484', 'CZ-Pn XII A 24', 'CZ-Pn XV A 10', 'CZ-Pst DE I 7', 'CZ-Pu Pu XIV A 19', 'CZ-Pu VI.E.4c', 'CZ-Pu XIV.B.13', 'D-B Theol. Lat. Qu. 149', 'D-KNd 1161', 'D-MZb A', 'D-Mbs Clm 14965b', 'D-Mbs Clm 4303', 'D-Mbs Clm 4306', 'D-W Cod. Guelf. 29 Helmst. (Heinemann-Nr. 32)', 'DK-Kk Gl. Kgl. S. 3449 8o [02] II', 'E-BAR, s.s.', 'E-Bbc M 663', 'E-Bbc M 705', 'E-Bbc M 706', 'E-H Ms. 2', 'E-H Ms. 7 (ant. 5)', 'E-MO Ms. 72', 'E-SA 6', 'E-VI Mss. 113-114', 'F-CA Ms 0078 (79)', 'F-LA Ms 263', 'F-Pn Lat. 10510', 'F-Pn Lat. 1118', 'F-Pn Lat. 1135', 'F-Pn Lat. 13252', 'F-Pn Lat. 9448', 'F-Pn Lat. 9449', 'F-Pn Latin 15181', 'F-Pn NAL 1236', 'F-Pn NAL 1411', 'F-SO 596', 'F-TOm 149', 'GB-Ccc Ms 473', 'GB-Lbl Add MS 30847', 'GB-Lbl printed book IB.6753 (Augsburg Antiphoner 1495, olim AA Impr. 1495)', 'H-Bu lat. 118', 'HR-Hf Cod. C Nr. 4', 'HR-Hf Cod. D Nr. 5', 'I-BV V 19', 'I-MC 542', 'I-VCd CLXX', 'P-AR Res. Ms. 021', 'P-AR Res. Ms. 025', 'P-BRs Ms. 028', 'P-BRs Ms. 032', 'P-EVpc 000', 'P-Ln RES. 253 P.', 'PL-GD Mar. F 408', 'PL-Kkar Ms.2 (rkp. Perg. 14)', 'PL-Kkar Ms.5 (rkp. Perg. 13)', 'PL-PŁsem MsEPl 12', 'PL-STAb ms. 2', 'PL-Wn  rps 12720 V', 'SI-Lna 18 (olim 17)', 'SK-BRsa SNA 17', 'SK-BRsa SNA 2', 'SK-BRsa SNA 4', 'SK-Bra BAIII ECLad.6']
Partition 0: 56 : ['A-Gu 30 (olim 38/9 f.)', 'A-KN CCl 1012', 'A-KN CCl 1018', 'A-KN CCl 589', 'A-Wda C-10', 'Antifonario s.s.', 'B-Gu Hs BKT.006', 'CH-SGs 391', 'CZ-Bu R 387', 'CZ-Pn (Praha) XII A 21', 'CZ-Pu VI E 13', 'CZ-Pu VI G 3a', 'CZ-Pu XII C 3', 'CZ-Pu XII E 15c', 'CZ-Pu XIII C 4', 'CZ-Pu XIV C 20', 'CZ-R R 17', 'D-FUl Aa 55', 'D-MZb C', 'D-MZb D', 'D-MZb E', 'D-Mbs Clm 4304', 'D-Mbs Clm 4305', 'D-W Cod. Guelf. 28 Helmst. (Heinemann-Nr. 31)', 'E-Bbc Ms. 2322', 'E-E L. III. 3.', 'E-E L. III. 4.', 'E-H Ms. 8 (ant. 6)', 'E-H Ms. 9 (ant. 25)', 'E-LUc s.s.', 'E-Tc 35.4', 'F-CH Ms 0050', 'F-Pn Lat. 1030', 'F-Pn Latin 12601', 'F-Pn Latin 15182', 'F-Pn NAL 1412', 'F-R 248 (olim  A. 339)', 'GB-Lbl Add MS 30846', 'H-Bu lat. 119', 'H-Bu lat. 121', 'H-Bu lat. 122', 'HR-Hf Cod. E Nr. 3', 'HR-Hf Cod. F Nr. 6', 'I-BV V 20', 'NL-ZUa 6', 'NZ-Wt MSR-03', 'PL-Kkar Ms.1 (rkp. Perg. 12)', 'PL-Kkar Ms.3 (rkp. Perg. 15)', 'PL-Kkar Ms.4 (rkp. Perg. 20)', 'PL-PŁsem MsEPl 12', 'PL-WRzno Rkp. 12025/IV', 'SI-Lna 19 (olim 18)', 'SK-Bra BAI ECLad.3', 'SK-Sk 2', 'US-Cai 1911.142b', 'US-NYcubl MS 1']
Partition 40: 69 : ['A-KR Schachtel VI/258', 'A-LIb 290 (olim 183; olim Gamma p 19)', 'A-SF XI 480', 'A-VOR 287 (olim XXIX)', 'A-Wda D-4', 'A-Wn Cod. 1799**', 'A-Wn Cod. 1890', 'CDN-Mrb MS Medieval 0234', 'CH-E 611', 'CH-Fco Ms. 2', 'CH-SGs 388', 'CZ-Pu VI G 11', 'Cantus GOTTSCHALK', 'Cantus MA Impr. 1537', 'D-AAm G 20', 'D-B Mus. 40047', 'D-BAs Msc.Lit.25 (olim Ed.IV.11)', 'D-KA Aug. LX', 'D-KNd 215', 'D-Ma 12o Cmm 1', 'D-Sl HB.I.55', 'E-Bbc M 662', 'E-Bbc M 888', 'E-Bbc Ms. 619', 'E-Gs ms. 45 (olim Sant Feliu, 20)', 'E-SI MS 9', 'E-Tc 44.1', 'E-Tc 44.2', 'F-AI 44', 'F-AS 465 (CGM 893)', 'F-CA 38 (olim 40)', 'F-CA Impr. XVI C 4', 'F-Pn Lat. 17296', 'F-Pn Latin 1085', 'F-Pn Latin 1090', 'F-Pn Latin 12044', 'F-Pn Latin 1240', 'F-Pn NAL 1535', 'F-VAL 114', 'GB-AB 20541 E', 'GB-Cu Mm.ii.9', 'GB-Lbl Add MS 30848', 'GB-Lbl Add MS 30849', 'GB-Lbl Add MS 30850', 'GB-Ob MS. Canon. Liturg. 202', 'GB-Ob MS. Laud Misc. 284', 'GB-WO F. 160 (olim 1247) (facsimile)', 'GB-WO F. 160 (olim 1247) (with hymnal)', 'I-AO 6', 'I-Ac 693', 'I-Ac 694', 'I-Ad 5', 'I-CHV s.c.', 'I-Far s.c.', 'I-Fl Conv. sopp. 560', 'I-Lc 601', 'I-MZ 15/79', 'I-Nn vi. E. 20', 'I-PCd cod. 65', 'I-Rv C.5', 'NL-Uu Ms. 406 (shelfmark 3 J 7)', 'PL-KIk Ms. 1', 'PL-Klk 1', 'PL-WRu I F 401', 'PL-WRu Ms. R 503', 'TR-Itks Deissmann 42', 'US-Cn 24', 'V-CVbav San Pietro B.79', 'V-CVbav lat. 8737']
Partition 32: 89 : ['A-Gu Ms 0807', 'A-KN Cod 588', 'A-KN Cod 73', 'B-Br Ms II 3823', 'CH-E Codex 121', 'CH-P 18', 'CH-ROM Ms. liturg. FiD 5', 'CH-SGs Cod 338', 'CH-SGs Cod 340', 'CH-SGs Cod 342', 'CH-SGs Cod 343', 'CH-SGs Cod 374', 'CH-SGs Cod 375', 'CH-SGs Cod 376', 'CH-SGv VadSlg Ms 0295', 'CZ-Bm A 7115', 'CZ-R R 418', 'D-B Ms mus 40078', 'D-BAa Msc Lit 6', 'D-DS Hs 0545', 'D-Ful Aa 0006', 'D-HEu Cod. Sal. X,007', 'D-KA Lichtenthal 002', 'D-KNd Ms 1001b', 'D-KWsr Drachenfels-Missale', 'D-Mbs Clm 03005', 'D-TRp Hs 187', 'D-W Cod Guelf Helmst 1008', 'E-Bbc M 1147', 'E-Bbc M 648', 'E-Mh Cód. 18', 'E-Mh Cód. 51', 'E-Mn Mss/1361', 'F-AI Ms 0044', 'F-AN Ms 0091', 'F-AS Ms 0437 (cat. 1011)', 'F-CA Ms 0060 (61)', 'F-CA Ms 0061 (62)', 'F-CA Ms 0075 (76)', 'F-CHRm Ms 0047 (40)', 'F-Collection privée Mont-Renaud', 'F-LA Ms 118', 'F-LA Ms 236', 'F-LA Ms 239', 'F-LG Ms 0002 (17)', 'F-NS Ms 0004', 'F-PR Ms 0012', 'F-Pa Ms 0135', 'F-Pa Ms 0197', 'F-Pm Ms 0384', 'F-Pn Lat. 1087', 'F-Pn Lat. 1132', 'F-Pn Lat. 12050', 'F-Pn Lat. 12584', 'F-Pn Lat. 17307', 'F-Pn Lat. 2291', 'F-Pn Lat. 780', 'F-Pn Lat. 833', 'F-Pn Lat. 903', 'F-Pn Lat. 904', 'F-Pn Lat. 9439', 'F-Pn Lat. 9441', 'F-Pn NAL 1235', 'F-Pn NAL 1414', 'F-Pn NAL 1669', 'F-Pn NAL 1890', 'F-SOM Ms 0252', 'GB-Lbl Egerton 857', 'GB-Lbl Harley 4951', 'I-BGc MA 150 (Psi III.8)', 'I-BGc MA 239 (Gamma III.18)', 'I-BV 34', 'I-Bc Q 09', 'I-Tn G.V.20', 'NL-Uu Hs. 0415', 'PL-Kl RL 1', 'PL-SAk 40', 'PL-WRu I F 413', 'PL-WRu I F 414', 'PL-WRu I F 416', 'PL-Wn Rps 12496 IV', 'PL-Wn rps 12722 V', 'Reconstitution Sacramentaire de Tours (TU1)', 'US-NYcub Western MS 097', 'US-PHf Lewis E 158', 'V-CVbav Archivio di San Pietro F.22', 'V-CVbav Ross.0076', 'V-CVbav Vat. lat. 4770', 'V-CVbav Vat. lat. 5319']
Partition 57: 10 : ['E-L Ms 8', 'E-Mh Cod. 30', 'E-SAu Ms 2637', 'E-Tc 35.6', 'GB-Lbl Add MS 30844', 'GB-Lbl Add MS 30851', 'I-VEcap Codex Veronensis LXXXIX', 'P-AR Res. Ms. 016', 'P-BRs Ms. 034', 'P-Ln Iluminado 084']
Partition 54: 54 : ['B-Br Ms 10127-44', 'CH-Cobodmer C 0074', 'CH-SGs Cod 339', 'CH-SGs Cod 381', 'CZ-OLu M III 6', 'CZ-Pn XIII B 2', 'CZ-Pn XIV D 12', 'CZ-Pu XIII A 5c', 'CZ-R R 396', 'D-BAa Msc Lit 5', 'D-BAa Msc Lit 7', 'D-Kl Theol. quart 0015', 'D-LEu Ms Thomas 391', 'D-MZb B', 'D-Mbs Clm 02541', 'D-Mbs Clm 02542', 'D-Sl HB I 246', 'E-Bbc M 784', 'E-Bbc M 785', 'E-Bbc M 889', 'E-Bbc Ms. 1805', 'E-Bbc Ms. 3180', 'E-Mh Cód. 45', 'E-Mn MSS/10110', 'E-Tc 35.5', 'F-AUT Ms S 0010 (8*)', 'F-AUT Ms S 0012 (11)', 'F-CO Ms 0444 (217)', 'F-G Ms 84 (Ms. 395 Rés.)', 'F-LA Ms 240', 'F-Pn Lat. 1121', 'F-Pn Lat. 1134', 'F-Pn Lat. 1136', 'F-Pn Lat. 17436', 'F-Pn Lat. 18010', 'F-Pn Lat. 909', 'F-Pn Lat. 9436', 'F-RS Ms 0221', 'F-RS Ms 0264', 'F-SEm Ms 018', 'F-Togs Ms 001', 'F-VAL Ms 0121', 'F-VN Ms 0759', 'GB-Dru Cosin V.V.6', 'GB-Lbl Add MS 30845', 'GB-Lbl Additional 18032', 'NL-Uu Hs. 0062', 'PL-WRu I F 411', 'SK-BRl Rkp. 387', 'SK-BRnm MUS I 78', 'SK-BRsa SNA 67', 'SK-Bra BMI EC Lad.3 EL18', 'SK-Sk Graduale Scepusiense Nr.1', 'US-Baw W.11']
Partition 22: 8 : ['A-Wn Cod. 1812', 'H-Bn Clmae 172a, 172b', 'H-Efkö MS I. 1 a-b', 'H-Efkö MS I. 3. a', 'RO-Sb Ms. 759', 'SK-BRa EC Lad. 3, EL 18', 'TR-Itks 2429', 'TR-Itks 42']

Level 2:
3
Partition 1: 197 : ['A-Gu 29 (olim 38/8 f.)', 'A-Gu 30 (olim 38/9 f.)', 'A-KN CCl 1010', 'A-KN CCl 1011', 'A-KN CCl 1012', 'A-KN CCl 1013', 'A-KN CCl 1015', 'A-KN CCl 1017', 'A-KN CCl 1018', 'A-KN CCl 589', 'A-Wda C-10', 'A-Wda C-11', 'Antifonario s.s.', 'B-Br Ms 10127-44', 'B-Gu Hs BKT.006', 'B-TOb 63 (olim V)', 'B-TOb 64 (olim IV)', 'CDN-Hsmu M2149.L4 1554', 'CDN-Ttfl MSS 09700', 'CH-Cobodmer C 0074', 'CH-SGs 390', 'CH-SGs 391', 'CH-SGs Cod 339', 'CH-SGs Cod 378', 'CH-SGs Cod 380', 'CH-SGs Cod 381', 'CH-SGs Cod 484', 'CZ-Bu R 387', 'CZ-OLu M III 6', 'CZ-Pn (Praha) XII A 21', 'CZ-Pn XII A 24', 'CZ-Pn XIII B 2', 'CZ-Pn XIV D 12', 'CZ-Pn XV A 10', 'CZ-Pst DE I 7', 'CZ-Pu Pu XIV A 19', 'CZ-Pu VI E 13', 'CZ-Pu VI G 3a', 'CZ-Pu VI.E.4c', 'CZ-Pu XII C 3', 'CZ-Pu XII E 15c', 'CZ-Pu XIII A 5c', 'CZ-Pu XIII C 4', 'CZ-Pu XIV C 20', 'CZ-Pu XIV.B.13', 'CZ-R R 17', 'CZ-R R 396', 'D-B Theol. Lat. Qu. 149', 'D-BAa Msc Lit 5', 'D-BAa Msc Lit 7', 'D-FUl Aa 55', 'D-KNd 1161', 'D-Kl Theol. quart 0015', 'D-LEu Ms Thomas 391', 'D-MZb A', 'D-MZb B', 'D-MZb C', 'D-MZb D', 'D-MZb E', 'D-Mbs Clm 02541', 'D-Mbs Clm 02542', 'D-Mbs Clm 14965b', 'D-Mbs Clm 4303', 'D-Mbs Clm 4304', 'D-Mbs Clm 4305', 'D-Mbs Clm 4306', 'D-Sl HB I 246', 'D-W Cod. Guelf. 28 Helmst. (Heinemann-Nr. 31)', 'D-W Cod. Guelf. 29 Helmst. (Heinemann-Nr. 32)', 'DK-Kk Gl. Kgl. S. 3449 8o [02] II', 'E-BAR, s.s.', 'E-Bbc M 663', 'E-Bbc M 705', 'E-Bbc M 706', 'E-Bbc M 784', 'E-Bbc M 785', 'E-Bbc M 889', 'E-Bbc Ms. 1805', 'E-Bbc Ms. 2322', 'E-Bbc Ms. 3180', 'E-E L. III. 3.', 'E-E L. III. 4.', 'E-H Ms. 2', 'E-H Ms. 7 (ant. 5)', 'E-H Ms. 8 (ant. 6)', 'E-H Ms. 9 (ant. 25)', 'E-L Ms 8', 'E-LUc s.s.', 'E-MO Ms. 72', 'E-Mh Cod. 30', 'E-Mh Cód. 45', 'E-Mn MSS/10110', 'E-SA 6', 'E-SAu Ms 2637', 'E-Tc 35.4', 'E-Tc 35.5', 'E-Tc 35.6', 'E-VI Mss. 113-114', 'F-AUT Ms S 0010 (8*)', 'F-AUT Ms S 0012 (11)', 'F-CA Ms 0078 (79)', 'F-CH Ms 0050', 'F-CO Ms 0444 (217)', 'F-G Ms 84 (Ms. 395 Rés.)', 'F-LA Ms 240', 'F-LA Ms 263', 'F-Pn Lat. 1030', 'F-Pn Lat. 10510', 'F-Pn Lat. 1118', 'F-Pn Lat. 1121', 'F-Pn Lat. 1134', 'F-Pn Lat. 1135', 'F-Pn Lat. 1136', 'F-Pn Lat. 13252', 'F-Pn Lat. 17436', 'F-Pn Lat. 18010', 'F-Pn Lat. 909', 'F-Pn Lat. 9436', 'F-Pn Lat. 9448', 'F-Pn Lat. 9449', 'F-Pn Latin 12601', 'F-Pn Latin 15181', 'F-Pn Latin 15182', 'F-Pn NAL 1236', 'F-Pn NAL 1411', 'F-Pn NAL 1412', 'F-R 248 (olim  A. 339)', 'F-RS Ms 0221', 'F-RS Ms 0264', 'F-SEm Ms 018', 'F-SO 596', 'F-TOm 149', 'F-Togs Ms 001', 'F-VAL Ms 0121', 'F-VN Ms 0759', 'GB-Ccc Ms 473', 'GB-Dru Cosin V.V.6', 'GB-Lbl Add MS 30844', 'GB-Lbl Add MS 30845', 'GB-Lbl Add MS 30846', 'GB-Lbl Add MS 30847', 'GB-Lbl Add MS 30851', 'GB-Lbl Additional 18032', 'GB-Lbl printed book IB.6753 (Augsburg Antiphoner 1495, olim AA Impr. 1495)', 'H-Bu lat. 118', 'H-Bu lat. 119', 'H-Bu lat. 121', 'H-Bu lat. 122', 'HR-Hf Cod. C Nr. 4', 'HR-Hf Cod. D Nr. 5', 'HR-Hf Cod. E Nr. 3', 'HR-Hf Cod. F Nr. 6', 'I-BV V 19', 'I-BV V 20', 'I-MC 542', 'I-VCd CLXX', 'I-VEcap Codex Veronensis LXXXIX', 'NL-Uu Hs. 0062', 'NL-ZUa 6', 'NZ-Wt MSR-03', 'P-AR Res. Ms. 016', 'P-AR Res. Ms. 021', 'P-AR Res. Ms. 025', 'P-BRs Ms. 028', 'P-BRs Ms. 032', 'P-BRs Ms. 034', 'P-EVpc 000', 'P-Ln Iluminado 084', 'P-Ln RES. 253 P.', 'PL-GD Mar. F 408', 'PL-Kkar Ms.1 (rkp. Perg. 12)', 'PL-Kkar Ms.2 (rkp. Perg. 14)', 'PL-Kkar Ms.3 (rkp. Perg. 15)', 'PL-Kkar Ms.4 (rkp. Perg. 20)', 'PL-Kkar Ms.5 (rkp. Perg. 13)', 'PL-PŁsem MsEPl 12', 'PL-PŁsem MsEPl 12', 'PL-STAb ms. 2', 'PL-WRu I F 411', 'PL-WRzno Rkp. 12025/IV', 'PL-Wn  rps 12720 V', 'SI-Lna 18 (olim 17)', 'SI-Lna 19 (olim 18)', 'SK-BRl Rkp. 387', 'SK-BRnm MUS I 78', 'SK-BRsa SNA 17', 'SK-BRsa SNA 2', 'SK-BRsa SNA 4', 'SK-BRsa SNA 67', 'SK-Bra BAI ECLad.3', 'SK-Bra BAIII ECLad.6', 'SK-Bra BMI EC Lad.3 EL18', 'SK-Sk 2', 'SK-Sk Graduale Scepusiense Nr.1', 'US-Baw W.11', 'US-Cai 1911.142b', 'US-NYcubl MS 1']

In [84]:
importlib.reload(utils)
source_vs_feast_df = utils.get_sigla_vs_feast_partitions(corpus, sigla_partitions[1], feasts_partitions[1])

In [86]:
source_vs_feast_df.head(10)

,source_partition,n_of_sources,f_p_46,f_p_49,f_p_21,f_p_30,f_p_50,f_p_38
0,8,86,0.020,0.312,0.229,0.221,0.040,0.0
1,51,54,0.036,0.004,0.002,0.197,0.029,0.0
2,1,32,0.068,0.390,0.267,0.465,0.095,0.0
3,34,26,0.002,0.143,0.112,0.059,0.022,0.0
4,28,71,0.122,0.511,0.037,0.497,0.002,0.0
5,25,8,0.016,0.098,0.066,0.109,0.019,0.0
6,3,56,0.108,0.347,0.028,0.328,0.005,0.0
7,55,30,0.013,0.217,0.013,0.132,0.008,0.0

In [ ]:
source_vs_feast_df.to_csv(f'visual/nested_dc_sbm_source_vs_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}_levels_1_1.csv', index=False)

In [51]:
save_path = f"partitions/nested_dc_sbm_partitions_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}.csv"
df_partitions = utils.save_nested_partitions(sigla_partitions, save_path)
df_partitions.head()

Saved nested partitions to partitions/nested_dc_sbm_partitions_20_f_reducted_50_threshold_5_min_600.csv

,siglum,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,...,level2_new,level3_new,level4_new,level5_new,level6_new,level7_new,level8_new,level9_new,level10_new,level11_new
0,A-Gu 29 (olim 38/8 f.),26,42,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CZ-Pu XIV.B.13,26,42,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,A-KN CCl 1010,26,42,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,A-KN CCl 1011,26,42,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,A-KN CCl 1015,26,42,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [52]:
for col in df_partitions.columns:
    if col.startswith("level") and col.endswith("_new"):
        print(col, df_partitions[col].nunique())

level0_new 34
level1_new 7
level2_new 3
level3_new 1
level4_new 1
level5_new 1
level6_new 1
level7_new 1
level8_new 1
level9_new 1
level10_new 1
level11_new 1

In [53]:
COLS_4 = ["siglum", "level0_new", "level1_new", "level2_new", "level3_new"]

In [54]:
importlib.reload(utils)
utils.get_dendro_json(save_path, columns=COLS_4, output_path=f"visual/nested_dc_sbm_dendro_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_threshold_{MIN_FEAST_CHANTS_PER_SOURCE}_min_{MIN_CHANTS_PER_SOURCE}_cols4.json")