In [1]:
import utils
import sbmodel
import pycantus
import pycantus.data as data

In [3]:
corpus = data.load_dataset('cantuscorpus_v1.0')

Loading chants and sources...
Data loaded!

In [4]:
n_chants = len(corpus.chants)
print(f'Number of chants in CantusCorpus v1.0: {n_chants}')
n_sources = len(corpus.sources)
print(f'Number of sources in CantusCorpus v1.0: {n_sources}')

Number of chants in CantusCorpus v1.0: 888010
Number of sources in CantusCorpus v1.0: 2278

In [5]:
# Drop doxology
doxo_filter = pycantus.filtration.Filter('doxo_filter')
doxo_filter.add_value_exclude('cantus_id', '909000')
corpus.apply_filter(doxo_filter)

In [6]:
MIN_CHANTS_PER_SOURCE = 600

In [7]:
# Drop fragments => sources with less than 100 chants
corpus.drop_small_sources_data(min_chants=MIN_CHANTS_PER_SOURCE)

In [8]:
n_chants = len(corpus.chants)
print(f'Number of chants in CantusCorpus v1.0: {n_chants}')
n_sources = len(corpus.sources)
print(f'Number of sources in CantusCorpus v1.0: {n_sources}')

Number of chants in CantusCorpus v1.0: 812806
Number of sources in CantusCorpus v1.0: 363

In [9]:
sigla_dict = {source.srclink: source.siglum for source in corpus.sources}

### Networks

In [10]:
import importlib
importlib.reload(utils)

In [11]:
MIN_CID_PER_FEAST = 50

In [30]:
graph = utils.construct_bipart_source_feast_reducted_graph(corpus, min_cid_per_feast=MIN_CID_PER_FEAST)

Constructing bipartite graph between sources and feasts...
Number of source nodes: 363
Number of feast nodes: 719
Number of source-feast edges: 53137

In [122]:
utils.save_graph(graph, f"nets/source_feast_reducted_{MIN_CID_PER_FEAST}_bi_graph_min_{MIN_CHANTS_PER_SOURCE}.gt")

### SBM

In [12]:
N_INIT = 20

In [93]:
model = sbmodel.SBModel()

In [94]:
model.load_graph(f"nets/source_feast_reducted_{MIN_CID_PER_FEAST}_bi_graph_min_{MIN_CHANTS_PER_SOURCE}.gt")

Loaded graph with 1082 vertices, 53137 edges

In [95]:
model.fit_sbm(n_init=N_INIT)

Fitting SBM to graph with 1082 vertices and 53137 edges...
Fitting SBM (init 1/20)...
[1/20] entropy = 91618.28
Fitting SBM (init 2/20)...
[2/20] entropy = 91601.71
Fitting SBM (init 3/20)...
[3/20] entropy = 91550.25
Fitting SBM (init 4/20)...
[4/20] entropy = 91557.43
Fitting SBM (init 5/20)...
[5/20] entropy = 91540.11
Fitting SBM (init 6/20)...
[6/20] entropy = 91581.69
Fitting SBM (init 7/20)...
[7/20] entropy = 91550.62
Fitting SBM (init 8/20)...
[8/20] entropy = 91489.00
Fitting SBM (init 9/20)...
[9/20] entropy = 91568.83
Fitting SBM (init 10/20)...
[10/20] entropy = 91580.51
Fitting SBM (init 11/20)...
[11/20] entropy = 91531.34
Fitting SBM (init 12/20)...
[12/20] entropy = 91577.04
Fitting SBM (init 13/20)...
[13/20] entropy = 91629.22
Fitting SBM (init 14/20)...
[14/20] entropy = 91547.87
Fitting SBM (init 15/20)...
[15/20] entropy = 91565.43
Fitting SBM (init 16/20)...
[16/20] entropy = 91619.81
Fitting SBM (init 17/20)...
[17/20] entropy = 91548.23
Fitting SBM (init 18/20)...
[18/20] entropy = 91479.88
Fitting SBM (init 19/20)...
[19/20] entropy = 91682.86
Fitting SBM (init 20/20)...
[20/20] entropy = 91526.85

In [96]:
model.save_states(f"models/dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

In [97]:
model.fit_nested_sbm(n_init=N_INIT)

Fitting nested SBM to graph with 1082 vertices and 53137 edges...
Fitting nested SBM (init 1/20)...
[1/20] entropy = 88930.48
Fitting nested SBM (init 2/20)...
[2/20] entropy = 88929.42
Fitting nested SBM (init 3/20)...
[3/20] entropy = 89341.70
Fitting nested SBM (init 4/20)...
[4/20] entropy = 88870.60
Fitting nested SBM (init 5/20)...
[5/20] entropy = 89031.22
Fitting nested SBM (init 6/20)...
[6/20] entropy = 89024.54
Fitting nested SBM (init 7/20)...
[7/20] entropy = 89055.73
Fitting nested SBM (init 8/20)...
[8/20] entropy = 89004.07
Fitting nested SBM (init 9/20)...
[9/20] entropy = 88969.36
Fitting nested SBM (init 10/20)...
[10/20] entropy = 88962.24
Fitting nested SBM (init 11/20)...
[11/20] entropy = 88938.16
Fitting nested SBM (init 12/20)...
[12/20] entropy = 89053.96
Fitting nested SBM (init 13/20)...
[13/20] entropy = 89116.37
Fitting nested SBM (init 14/20)...
[14/20] entropy = 89021.66
Fitting nested SBM (init 15/20)...
[15/20] entropy = 89234.97
Fitting nested SBM (init 16/20)...
[16/20] entropy = 89212.46
Fitting nested SBM (init 17/20)...
[17/20] entropy = 89007.84
Fitting nested SBM (init 18/20)...
[18/20] entropy = 89240.39
Fitting nested SBM (init 19/20)...
[19/20] entropy = 89080.47
Fitting nested SBM (init 20/20)...
[20/20] entropy = 88943.04

In [98]:
model.save_states(f"models/dc_nested_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

In [99]:
model.fit_sbm_weighted(n_init=N_INIT, weight_label='weight')

Fitting weighted SBM to graph with 1082 vertices and 53137 edges...
Fitting weighted SBM (init 1/20)...
[1/20] entropy = 200294.14
Fitting weighted SBM (init 2/20)...
[2/20] entropy = 200458.28
Fitting weighted SBM (init 3/20)...
[3/20] entropy = 200351.21
Fitting weighted SBM (init 4/20)...
[4/20] entropy = 200284.40
Fitting weighted SBM (init 5/20)...
[5/20] entropy = 200233.78
Fitting weighted SBM (init 6/20)...
[6/20] entropy = 200288.43
Fitting weighted SBM (init 7/20)...
[7/20] entropy = 200326.03
Fitting weighted SBM (init 8/20)...
[8/20] entropy = 200527.57
Fitting weighted SBM (init 9/20)...
[9/20] entropy = 200335.61
Fitting weighted SBM (init 10/20)...
[10/20] entropy = 200208.12
Fitting weighted SBM (init 11/20)...
[11/20] entropy = 200348.66
Fitting weighted SBM (init 12/20)...
[12/20] entropy = 200417.48
Fitting weighted SBM (init 13/20)...
[13/20] entropy = 200279.37
Fitting weighted SBM (init 14/20)...
[14/20] entropy = 200308.80
Fitting weighted SBM (init 15/20)...
[15/20] entropy = 200318.23
Fitting weighted SBM (init 16/20)...
[16/20] entropy = 200361.75
Fitting weighted SBM (init 17/20)...
[17/20] entropy = 200333.57
Fitting weighted SBM (init 18/20)...
[18/20] entropy = 200233.92
Fitting weighted SBM (init 19/20)...
[19/20] entropy = 200390.79
Fitting weighted SBM (init 20/20)...
[20/20] entropy = 200293.12

In [100]:
model.save_states(f"models/weighted_dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

In [101]:
model.fit_nested_sbm_weighted(n_init=N_INIT, weight_label='weight')

Fitting weighted nested SBM to graph with 1082 vertices and 53137 edges...
Fitting weighted nested SBM (init 1/20)...
[1/20] entropy = 200952.65
Fitting weighted nested SBM (init 2/20)...
[2/20] entropy = 200717.16
Fitting weighted nested SBM (init 3/20)...
[3/20] entropy = 200415.68
Fitting weighted nested SBM (init 4/20)...
[4/20] entropy = 200431.96
Fitting weighted nested SBM (init 5/20)...
[5/20] entropy = 200379.14
Fitting weighted nested SBM (init 6/20)...
[6/20] entropy = 200586.53
Fitting weighted nested SBM (init 7/20)...
[7/20] entropy = 200592.73
Fitting weighted nested SBM (init 8/20)...
[8/20] entropy = 200696.82
Fitting weighted nested SBM (init 9/20)...
[9/20] entropy = 200752.40
Fitting weighted nested SBM (init 10/20)...
[10/20] entropy = 200384.41
Fitting weighted nested SBM (init 11/20)...
[11/20] entropy = 200498.77
Fitting weighted nested SBM (init 12/20)...
[12/20] entropy = 200768.94
Fitting weighted nested SBM (init 13/20)...
[13/20] entropy = 200414.96
Fitting weighted nested SBM (init 14/20)...
[14/20] entropy = 200262.24
Fitting weighted nested SBM (init 15/20)...
[15/20] entropy = 200306.14
Fitting weighted nested SBM (init 16/20)...
[16/20] entropy = 200680.77
Fitting weighted nested SBM (init 17/20)...
[17/20] entropy = 200249.53
Fitting weighted nested SBM (init 18/20)...
[18/20] entropy = 200489.83
Fitting weighted nested SBM (init 19/20)...
[19/20] entropy = 200743.64
Fitting weighted nested SBM (init 20/20)...
[20/20] entropy = 200454.49

In [102]:
model.save_states(f"models/weighted_nested_dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.pickle")

### Infering

In [13]:
import pickle
importlib.reload(sbmodel)
importlib.reload(utils)

In [14]:
model = sbmodel.SBModel()

In [15]:
model.load_states(f'models/weighted_nested_dc_sbm_best_states_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.pickle')

In [16]:
print(model.best_states.keys())

dict_keys(['DC_SBM', 'Nested_DC_SBM', 'Weighted_DC_SBM', 'Weighted_Nested_DC_SBM'])

#### DC-SBM

In [107]:
best_state = model.best_states['DC_SBM']

In [108]:
print("Best DC SBM state:")
print(best_state)
index_partitions, sigla_partitions, feasts_partitions = utils.get_partitions_from_state(best_state, sigla_dict)
print('Number of partitions:', len(index_partitions))
print('Number of sigla partitions:', len(sigla_partitions))
print('Number of feast partitions:', len(feasts_partitions))

Best DC SBM state:
<BlockState object with 1082 blocks (36 nonempty), degree-corrected, for graph <Graph object, undirected, with 1082 vertices and 53137 edges, 2 internal vertex properties, 2 internal edge properties, at 0x766de96c1ba0>, at 0x766de96c0b50>
Number of partitions: 36
Number of sigla partitions: 19
Number of feast partitions: 17

In [109]:
with open(f'visual/dc_sbm_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.txt', 'w') as f:
    for partition, feasts in feasts_partitions.items():
        print(sorted(feasts), file=f)
        print(file=f)

#### DC-Weighted-SBM

In [17]:
best_state = model.best_states['Weighted_DC_SBM']

In [18]:
print("Best Weighted DC SBM state:")
print(best_state)
index_partitions, sigla_partitions, feasts_partitions = utils.get_partitions_from_state(best_state, sigla_dict)
print('Number of partitions:', len(index_partitions))
print('Number of sigla partitions:', len(sigla_partitions))
print('Number of feast partitions:', len(feasts_partitions))

Best Weighted DC SBM state:
<BlockState object with 1082 blocks (32 nonempty), degree-corrected, with 1 edge covariate, for graph <Graph object, undirected, with 1082 vertices and 53137 edges, 2 internal vertex properties, 2 internal edge properties, at 0x77b0ed84a890>, at 0x77b0ebc1f490>
Number of partitions: 32
Number of sigla partitions: 17
Number of feast partitions: 15

In [132]:
with open(f'visual/weighted_dc_sbm_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.txt', 'w') as f:
    for partition, feasts in feasts_partitions.items():
        print('Partition:', partition, file=f)
        print(sorted(feasts), file=f)
        print(file=f)

In [ ]:
importlib.reload(utils)
source_vs_feast_df = utils.get_sigla_vs_feast_partitions(corpus, sigla_partitions, feasts_partitions)

In [77]:
source_vs_feast_df.to_csv(f'visual/weighted_dc_sbm_source_vs_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.csv', index=False)

In [26]:
importlib.reload(utils)
utils.detect_sanctorale_in_partitions(feasts_partitions)

Partition 406: 48/50 : {'Dec': 7, 'undetermined': 26, 'Jun': 1, 'Feb': 2, 'Jul': 1, 'Aug': 4, 'Apr': 1, 'May': 1, 'Jan': 2, 'Oct': 3}
Sanctorale feasts: ['Nicolai', 'Comm. unius Virginis', 'Comm. plurimorum Virginum', 'Antonii Patavini', 'Thomae Apost.', 'Scholasticae', 'Marthae', 'De Corona Spinea', 'Mariae Aegyptiacae', 'In tempore Nat.', 'Clarae', 'Thomae Cant.', 'Comm. Evangelistarum', 'Comm. unius Confessoris non Pontificis', 'Comm. plurimorum Confessorum', 'Comm. unius Martyris', 'Comm. unius Confessoris', 'De BMV Nat.', 'Comm. plurimorum Martyrum', 'Comm. plurimorum Confessorum Pontificum', 'Commune plurimorum Martyrum TP', 'Joannis Port. Lat.', 'Comm. Apostolorum', 'Dorotheae', 'Commune Apostolorum TP', 'Mauri', 'Conceptio Mariae', 'Angeli Custodis', 'De Sanctis', 'Comm. unius Abbatis', 'Purificatio Mariae,8', 'Juliani', 'Comm. unius Confessoris Pontificis', 'Comm. unius Confessoris et Episcopi', 'Mariae ad Nives', 'Octava Agnetis', 'Hedwigis', 'Barbarae', 'Comm. Conjungium', 'De BMV TP', 'Judoci', 'Columbae', 'Comm. unius Martyris Pontificis', 'Andreae,8', 'Comm. unius Virginis non Martyris', 'Francisci', 'Commune BMV', 'De BMV post Epiph.']
Temporal feasts: ['Corporis Christi', 'De BMV Adv.']

Partition 445: 9/40 : {'Dec': 4, 'Jan': 3, 'Sep': 1, 'Oct': 1}
Sanctorale feasts: ['Vigilia Nat. Domini', 'Nativitas Domini', 'Silvestri', 'Epiphania', 'Circumcisio Domini', 'Vigilia Epiphaniae', 'Valeriae', 'Materni', 'Dedic. S.Salv., Mar.']
Temporal feasts: ['Dom. 4 Adventus', 'Dom. Septuagesimae', 'Dom. 1 Quadragesimae', 'Dom. de Passione', 'Dom. Sexagesimae', 'Nativitas Domini,8', 'Dom. p. Nat. Dom.', 'Fer. 4 Maj. Hebd.', 'Fer. 2 Maj. Hebd.', 'Dom. 1 p. Epiphaniam', 'Dom. 2 Quadragesimae', 'Dom. 3 Quadragesimae', 'Dom. Quinquagesimae', 'Fer. 5 in Cena Dom.', 'Fer. 6 in Parasceve', 'Dom. 1 Adventus', 'Dom. 2 p. Epiph.', 'Sabbato Sancto', 'Ad Mandatum', 'Dom. 3 Adventus', 'Fer. 4 Q.T. Adventus', 'Dom. 2 Adventus', 'Dom. in Palmis', 'Dom. 4 Quadragesimae', 'Dom. Quadragesimae', 'Fer. 3 Maj. Hebd.', 'Dom. p. Oct. Nat.', 'Sabb. Q.T. Adventus', 'Sabb. Septuagesimae', 'Fer. 6 Hebd. 5 Quad.', 'In tempore Quad.']

Partition 676: 9/57 : {'Jan': 4, 'Mar': 1, 'Dec': 3, 'Jul': 1}
Sanctorale feasts: ['Oct. Nat. Innocent.', 'Oct. Joannis Evang.', 'Gertrudis Nivellensis', 'Die 2 p. Epiphaniam', 'Octava Stephani', 'Die 5 p. Nat. Domini', 'Die 6 p. Nat. Domini', 'Syri', 'Octava Martialis']
Temporal feasts: ['Hebd. 3 Adventus', 'Fer. 5 Hebd. 4 Adv.', 'Fer. 6 Hebd. 3 Adv.', 'Sabbato Hebd. 3 Adv.', 'Fer. 2 Hebd. 4 Adv.', 'Fer. 3 Hebd. 4 Adv.', 'Fer. 4 Hebd. 4 Adv.', 'Sabbato Hebd. 4 Adv.', 'Hebd. 4 Adventus', 'Nat. Innocentium,8', 'Sabb. p. Epiphaniam', 'In tempore Epiphaniae', 'Hebd. 1 Quad.', 'Fer. 2 Hebd. 1 Adv.', 'Hebd. 2 Adventus', 'Fer. 5 p. Epiphaniam', 'Fer. 5 Hebd. 2 p.Ep.', 'Fer. 4 Hebd. 2 p.Ep.', 'Fer. 3 Hebd. 2 p.Ep.', 'Fer. 4 Hebd. 1 Adv.', 'Fer. 4 p. Epiphaniam', 'Fer. 3 p. Epiphaniam', 'Ad Completorium', 'Hebd. de Passione', 'Fer. 2 Hebd. 2 p.Ep.', 'Hebd. Sancta', 'Fer. 2 p. Epiphaniam', 'Fer. 6 Hebd. 2 p.Ep.', 'Hebd. Quinquagesimae', 'Fer. 3 Hebd. 3 Adv.', 'Fer. 2 Hebd. 3 Adv.', 'Fer. 6 Hebd. 4 Adv.', 'Hebd. 1 Adventus', 'Hebd. Adventus', 'Fer. 3 Hebd. 1 Adv.', 'Fer. 6 Hebd. 1 Adv.', 'Dom. 4 p. Epiph.', 'Fer. 5 Hebd. 3 Adv.', 'Fer. 4 Hebd. 3 Adv.', 'Octava Nat. Domini,8', 'Hebd. Nat. Dom.', 'Hebd. Septuagesimae', 'Sabb. Hebd. 2 p. Ep.', 'Suff. Mariae Nat.', 'Suff. Mariae Adv.', 'Sabbato Hebd. 1 Adv.', 'Dom. 5 p. Epiph.', 'Fer. 6 p. Epiphaniam']

Partition 416: 145/149 : {'Jul': 17, 'Jun': 8, 'Aug': 17, 'Feb': 7, 'May': 7, 'Nov': 16, 'Sep': 15, 'undetermined': 36, 'Oct': 11, 'Dec': 3, 'Apr': 4, 'Jan': 2, 'Mar': 2}
Sanctorale feasts: ['Jacobi', 'Viti et sociorum', 'Bartholomaei', 'Julianae', 'Monicae', 'Praesentatio Mariae', 'Aegidii', 'Divisio Apostolorum', 'Bonifacii', 'Transl. Benedicti', 'Hieronimi', 'Inventio Stephani', 'Visitatio Mariae', 'Germani Parisien.', 'Dominici', 'Walburgae', 'Eustachii', 'Barnabae', 'Marinae', 'Elisabeth Hung.', 'Margaritae', 'Octava Assumptionis', 'Assumptio Mariae,8', 'De BMV post Purif.', 'Petri, Pauli,8', 'Kiliani et Soc.', 'Oswaldi, Reg.', 'Comm. unius Confessoris non Episcopus', 'Lucae', 'Octava Tr. Benedicti', 'Commune plurimorum Martyrum', 'Comm. plur. Mart.', 'Comm. plur. Conf.', 'Patriarcharum', 'Suscept. Reliquiarum', 'Dionysii', 'XI milium Virginum', 'Reliquiarum', 'Remigii', 'Mauritii', 'Matthiae', 'Comm. unius Apostoli', 'Petri, Mart.', 'Annae', 'Catharinae', 'Helenae', 'Leonardi', 'Philiberti', 'Afrae', 'Commune apostolorum', 'Commune Apostolorum', 'Victoris et Soc.', 'Aichardi', 'Oswaldi, Epi.', 'Nicasii', 'Quintini', 'Nazarii, Celsi', 'Ambrosii', 'Othmari', 'Transl. Stanislai', 'Vedasti', 'Dom. p. Assumptionem', 'Nativitas Mariae,8', 'Romani', 'Constantii', 'Eligii', 'Amandi', 'Ursulae', 'Wenceslai', 'Audoeni', 'Genulfi', 'Blasii', 'Procopii Sázaviensis', 'Comm. unius Conf.', 'Comm. un. Conf.Pont.', 'Commune unius Confessoris', 'Thomae de Aquino', 'Omnium Sanctorum,8', 'Gaugerici', 'Stephani, Reg.', 'Justinae, Cypriani', 'Comm. Virginum', 'Comm. unius Virg.', 'Antonini', 'Geraldi', 'Rictrudis', 'Hermagorae,Fortunati', 'Tiburtii, Valeriani, Maximi', 'Christophori', 'Felicitatis', 'Oct. Om. Sanctorum', 'Dionysii,8', 'Januarii et Soc.', 'Cuthberti', 'Magni', 'Pantaleonis', 'Emmerami', 'Oct. Apostolorum,8', 'Ludmilae', 'Comm. unius Virginis Martyris', 'Augustini', 'Pelagii', 'Edmundi', 'Arnulfi Metensis', 'Octava Martini', 'Fidis', 'Symphoriani', 'Tr. Kunegundis', 'Compassio Mariae TP', 'Udalrici', 'Martini,8', 'Dunstani', 'De BMV post Pent.', 'Adalberti', 'Acacii et sociorum', 'Decem Millium Martyrum', 'Comm. unius Mart.', 'Commune unius Martyris', 'Antonii', 'Transl. Martini', 'Lamberti', 'Galli', 'Gereonis et soc.', 'Tres Mariae', 'Octava Laurentii', 'Briccii', 'Pirmini', 'Firmini', 'Ladislai', 'Columbani', 'Bernardi', 'Floriani', 'Martialis, Epi.', 'Remacli', 'Transl. Adalberti', 'Comm. unius Confessoris Abbatis', 'Swithuni', 'Chrysanthi, Dariae', 'Willibrordi', 'Servatii', 'Pancratii et Soc.', 'Commune unius Martyris TP', 'Georgii, Adalberti', 'Callisti', 'Comm. unius Martyris non Pontificis']
Temporal feasts: ['Octava de Trinitate', 'Dom. p. Cor. Christi', 'In Dedicat. Eccl. TP', 'Fer. 6 Q.T. Quad.']

Partition 721: 16/17 : {'Dec': 4, 'Jan': 4, 'Feb': 3, 'Mar': 3, 'Nov': 1, 'undetermined': 1}
Sanctorale feasts: ['Nat. Innocentium', 'Agnetis', 'Stephani', 'Cathedra Petri', 'Purificatio Mariae', 'Joannis Evang.', 'Vincentii', 'Benedicti', 'Conversio Pauli', 'Fabiani, Sebastiani', 'Andreae', 'Luciae', 'Gregorii', 'Agathae', 'Annuntiatio Mariae', 'De BMV']
Temporal feasts: ['Pro defunctis']

Partition 720: 25/28 : {'Nov': 5, 'Jun': 5, 'Aug': 6, 'Apr': 2, 'Sep': 4, 'Jul': 1, 'May': 2}
Sanctorale feasts: ['Omnium Sanctorum', 'Petri, Pauli', 'Petri', 'Transfiguratio Dom.', 'Assumptio Mariae', 'Vincula Petri', 'Marci', 'Matthaei', 'Joannis, Pauli', 'Pauli', 'Decoll. Jo. Bapt.', 'Mariae Magdalenae', 'Michaelis', 'Philippi, Jacobi', 'Nativitas Mariae', 'Laurentii', 'Georgii', 'Exaltatio Crucis', 'Joannis Baptistae', 'Inventio Crucis', 'Clementis', 'Caeciliae', 'Martini', 'Hippolyti', 'Saturnini']
Temporal feasts: ['Octava Apostolorum', 'De Trinitate', 'In Dedicatione Ecclesiae']

Partition 506: 30/67 : {'undetermined': 17, 'Nov': 1, 'Feb': 1, 'Dec': 5, 'Jul': 1, 'Jan': 1, 'Aug': 2, 'May': 1, 'Apr': 1}
Sanctorale feasts: ['Transl. Indalaetii', 'Purificatio Mariae [Presentationis Domini]', 'Pauli, conversio', 'Stephani, inventio', 'Assumptio Mariae, infra oct.', 'Petri et Pauli', 'Commune unius Virginis', 'Commune Virginum', 'Philippi et Jacobi', 'Petri, Pauli, vig.', 'Aemiliani Cucullati', 'Joannis Baptistae., vig.', 'Eulaliae Barcinonensis', 'Justae, Rufinae', 'Leocadiae', 'Geraldi Archiepiscopi Bracharensis', 'Cucuphatis', 'Fabiani et Sebastiani', 'Thomae', 'Exspectationis BMV', 'Jonnis Baptistae, decol.', 'Aciscli', 'Eulaliae Emeritensis', 'Fructuosi, Augurii et Eulogii', 'Felicis Gerundae', 'Justi, Pastoris', 'Torquati et sociorum', 'Jacobi fratris Domini', 'Engratiae', 'Eugeniae']
Temporal feasts: ['Quadrag., hebd. 1, fer. 2', 'Sexagesimae, dom.', 'Quinquagesimae, dom.', 'Sanctissimae Trinitatis', 'Transfiguratio Domini', 'Pentecostes', 'Adventus, dom. 4', 'Adventus, dom. 1', 'Nativitas Domini, vig.', 'Quadragesimae, dom. 1', 'Adventus, dom. 3', 'Adventus, dom. 2', 'Quadragesimae, dom. 2', 'undetermined', 'Septuagesimae, dom.', 'Quadragesimae, dom. 4', 'Quadragesimae, dom. 3', 'Dominica in Albis (Octava Paschae)', 'Fest. per annum', 'Suff. Adventus', 'Dom. mensis Septembris', 'Carnes Tollendas', 'Assumptio Mariae (Hispanic rite)', 'Pro uno infirmo', 'De Sacratione Baselice', 'Dom. Quotidiano', 'Pro defunctis Sacerdotibus', 'De uno defuncto', 'Allisionis Infantum', 'Primitis', 'Letanias Canonicas', 'De uno justi', 'Letanias', 'Fer. 6 de Letanias Apostolicas', 'Fer. 5 de Letanias Apostolicas', 'Letanias Apostolicas', 'Letanias de Clade']

Partition 1003: 0/32 : {}
Sanctorale feasts: []
Temporal feasts: ['Ascensio Domini', 'Fer. 4 Pent.', 'Fer. 4 p. Pascha', 'In Letaniis', 'Fer. 3 in Letaniis', 'Fer. 2 in Letaniis', 'Dom. 1 p. Pent.', 'Dom. Resurrect.,8', 'Dom. Resurrectionis', 'Octava Paschae', 'Dom. 4 p. Pascha', 'In tempore Paschae', 'Fer. 5 p. Pascha', 'Fer. 3 p. Pascha', 'Sabbato in Albis', 'Dom. Pentecostes', 'Sabbato Pent.', 'Vigilia Pentecostes', 'Fer. 2 Pent.', 'Dom. Pentecostes,8', 'Fer. 5 Pent.', 'Fer. 3 Pent.', 'Fer. 6 Pent.', 'Fer. 2 p. Pascha', 'Fer. 6 p. Pascha', 'Dom. 3 p. Pascha', 'Dom. 2 p. Pascha', 'Dom. 1 p. Epiph.,8', 'Dom. 5 p. Pascha', 'Dom. 3 p. Pascha,8', 'Dom. 2 p. Pascha,8', 'Dom. 4 p. Pascha,8']

Partition 658: 40/87 : {'undetermined': 16, 'Jan': 3, 'Jul': 4, 'Jun': 1, 'Sep': 2, 'May': 4, 'Dec': 5, 'Apr': 1, 'Feb': 1, 'Oct': 2, 'Aug': 1}
Sanctorale feasts: ['Stephani,8', 'Meginrati', 'Octava Apostolorum Petri et Pauli', 'Joannis Evang.,8', 'De Sancta Lancea', 'Transl. Benedicti,8', 'Dedic. S. Salvatoris', 'Octava Joannis Bapt.', 'Recollectio Mariae', 'De Sanctis TP', 'Comm. unius Martyris TP', 'Comm. unius Confessoris TP', 'Baboleni', 'Transl. Stanislai Episcopi', 'Octava Nat. Mariae', 'Comm. plurimorum Confessorum non Pontificum', 'Suff. Mariae', 'Appar. Michaelis', 'Hilarii Arelatensis', 'Caroli Magni', 'Comm. plurimorum Martyrum TP', 'Wulstani', 'Suff. Crucis', 'Alexandri et sociorum', 'Sabae', 'Transl. Lamberti', 'Octava Andreae', 'Commune unius Confessoris Epi.', 'Joannis Baptistae,8', 'Octava Amandi', 'Transl. Trium Regum', 'Transl. Wolfgangi', 'Justi', 'Tiburtii, Susannae', 'Relatio Vedasti', 'Transl. Baboleni', 'Ludmillae', 'Transl. Francisci', 'Dominici Silensis', 'Lazari']
Temporal feasts: ['Oct. Ascens. Domini', 'Feria 5 per annum', 'Additamenta', 'Feria 4 per annum', 'Dom. 5 Quadragesimae', 'Fer. 4 in Letaniis', 'Hebd. per annum', 'Feria 6 per annum', 'De Trinitate,8', 'Octava Paschae,8', 'Dominica TP', 'Fer. 2 p. Oct.Pasch.', 'Fer. 5 p. Oct.Pasch.', 'Fer. 2 Hebd. 4 Pasc.', 'Fer. 3 p. Oct.Pasch.', 'Ascensio Domini,8', 'Sabb. p. Ascensionem', 'Fer. 6 p. Oct. Asc.', 'Fer. 6 p. Ascensio.', 'Fer. 2 p. Ascensio.', 'Fer. 6 p. Oct.Pasch.', 'Fer. 4 p. Oct.Pasch.', 'Sabbato TP', 'Hebd. TP', 'Fer. 4 Hebd. 3 Pasc.', 'Fer. 2 Hebd. 5 Pasc.', 'Fer. 3 Hebd. 4 Pasc.', 'Fer. 2 Hebd. 3 Pasc.', 'Fer. 3 Hebd. 3 Pasc.', 'Feria 2 per annum', 'Dom. Adventus', 'Dom. p. Pent.', 'Dom. p. Ascensionem', 'Ad Suffragium', 'Feria 3 per annum', 'Hebd. 2 p. Pascha', 'Fer. 4 Hebd. 4 Pasc.', 'Sabb. p. Oct. Asc.', 'In tempore Adventus', 'Invitatoria', 'Feria 2 TP', 'Sabb. p. Oct. Pasch.', 'Suff. Om. Sanctorum', 'Hebd. 3 p. Pascha', 'Octava Pentecostes', 'Fer. 4 Hebd. 5 Pasc.', 'Hymni']

Partition 489: 3/10 : {'Jan': 2, 'undetermined': 1}
Sanctorale feasts: ['Octava Nat. Domini', 'Octava Epiphaniae', 'Epiphania,8']
Temporal feasts: ['Dom. per annum', 'Fer. 5 per annum', 'Fer. 3 per annum', 'Fer. 4 per annum', 'Fer. 6 per annum', 'Fer. 2 per annum', 'Sabbato per annum']

Partition 405: 1/38 : {'Jan': 1}
Sanctorale feasts: ['Hilarii']
Temporal feasts: ['Fer. 2 Hebd. 1 Quad.', 'Fer. 3 Hebd. 1 Quad.', 'Fer. 5 Hebd. 4 Quad.', 'Fer. 4 Cinerum', 'Fer. 4 de Passione', 'Fer. 4 Hebd. 1 Quad.', 'Fer. 5 Hebd. 3 Quad.', 'Fer. 2 de Passione', 'Fer. 3 Hebd. 3 Quad.', 'Fer. 5 Hebd. 1 Quad.', 'Sabbato post Cineres', 'Sabb. de Passione', 'Dom. p. Epiphaniam', 'Fer. 6 post Cineres', 'Fer. 4 Hebd. 2 Quad.', 'Sabb. Hebd. 4 Quad.', 'Sabb. Hebd. 3 Quad.', 'Fer. 6 Hebd. 1 Quad.', 'Dom. 3 p. Epiph.', 'Fer. 5 post Cineres', 'Fer. 2 Hebd. 2 Quad.', 'Fer. 2 Hebd. 3 Quad.', 'Fer. 2 Hebd. 4 Quad.', 'Fer. 3 de Passione', 'Fer. 5 de Passione', 'Fer. 6 de Passione', 'Fer. 6 Hebd. 3 Quad.', 'Fer. 5 Hebd. 2 Quad.', 'Fer. 6 Hebd. 2 Quad.', 'Sabb. Hebd. 2 Quad.', 'Fer. 3 Hebd. 4 Quad.', 'Fer. 4 Hebd. 4 Quad.', 'Fer. 6 Hebd. 4 Quad.', 'Fer. 3 Hebd. 2 Quad.', 'Fer. 4 Hebd. 3 Quad.', 'Sabb. Hebd. 1 Quad.', 'Sabb. Quadragesimae']

Partition 817: 68/84 : {'Jun': 8, 'Apr': 1, 'Oct': 6, 'Aug': 9, 'Sep': 10, 'undetermined': 16, 'Feb': 1, 'Jan': 4, 'Jul': 8, 'May': 2, 'Nov': 3}
Sanctorale feasts: ['Gervasii, Protasii', 'In Letaniis maj.', 'Cyrici', 'Simonis, Judae', 'Agapiti', 'Cosmae, Damiani', 'Vig. Om. Sanctorum', 'Mauritii et sociorum', 'Apostolorum et Evangelistarum', 'Valentini', 'Sebastiani', 'Medardi', 'Timothei', 'Odilonis', 'Vig. Assump. Mariae', 'De Sancta Cruce', 'Septem Fratrum', 'Hermetis', 'Basilidis et Soc.', 'Processi, Martiniani', 'Cornelii, Cypriani', 'Marcellini, Petri', 'Marci, Marcellini', 'Felicis, Adaucti', 'Proti, Hiacinthi', 'Vigilia Petri', 'Praxedis', 'Priscae', 'Sabinae', 'Simplicii et Soc.', 'Donati', 'Germani', 'Martialis, Apost.', 'Gorgonii', 'Apollinaris', 'Euphemiae', 'Gordiani, Epimachi', 'Ded.Mont.S.Michaelis', 'Laurentii,8', 'Marci, Pont.', 'Marcelli, Pont.', 'Adriani', 'Alexandri et Soc.', 'Luciae, Germiniani', 'Felicis', 'Mennae', 'Chrysogoni', 'Leodegarii', 'Vig. Joannis Bapt.', 'Felicis Nolani', 'Nicomedis', 'Agnetis,8', 'Urbani', 'Cyriaci et Soc.', 'Primi, Feliciani', 'Crispini,Crispiniani', 'Stephani, Pont.', 'Theodori Tiro', 'Tiburtii, Valeriani', 'Pro ordinatione Episcopi', 'Abdonis, Sennis', 'Vitalis', 'Quat. Coronatorum', 'Felicissimi, Agapiti', 'Marcelli', 'Genesii', 'Comm. unius Apostolus', 'Dionysii et socii']
Temporal feasts: ['Ad Processionem', 'In tempore belli', 'Sabbato Q.T. Adventus', 'Pro pluvia', 'Vig. Ascensio Domini', 'Sixti', 'Pro infirmis', 'Pro iter agentibus', 'Sabbato Q.T. Sept.', 'Fer. 6 Q.T. Adventus', 'Tiburtii', 'Dom. post Ascensionem', 'Ad Missam', 'Pro Sacerdote', 'Sabbato Q.T. Pent.', 'Fer. 4 Q.T. Pent.']

Partition 442: 0/21 : {}
Sanctorale feasts: []
Temporal feasts: ['Nat', 'D5', '6f5', 'H6/f5', 'H6/S', '1D', 'D1', 'D70', 'D4', 'Mort', 'D6', 'Corp', 'Trin', '3D', 'D3', '2D', 'D2', 'Purif.BMV', 'H6/f6', 'Ded.Eccl.', 'Joh.ap.']

Partition 453: 0/15 : {}
Sanctorale feasts: []
Temporal feasts: ['De Regum', 'Dominica in estate', 'De Machabaeis', 'Ad Magnificat', 'Comm. Apostolorum TP', 'Ad Benedicite', 'In Dedicatione Eccl.', 'De Sapientia', 'De Prophetis', 'Dom. mensis Nov.', 'De Job', 'De Judith', 'Dom. mensis Octobris', 'De Tobia', 'De Esther']

Partition 1020: 0/24 : {}
Sanctorale feasts: []
Temporal feasts: ['Dom. 19 p. Pent.', 'Dom. 3 p. Pent.', 'Dom. 12 p. Pent.', 'Dom. 13 p. Pent.', 'Dom. 24 p. Pent.', 'Dom. 7 p. Pent.', 'Dom. 6 p. Pent.', 'Dom. 8 p. Pent.', 'Dom. 4 p. Pent.', 'Dom. 2 p. Pent.', 'Dom. 18 p. Pent.', 'Dom. 17 p. Pent.', 'Dom. 15 p. Pent.', 'Dom. 14 p. Pent.', 'Dom. 16 p. Pent.', 'Dom. 23 p. Pent.', 'Dom. 22 p. Pent.', 'Dom. 21 p. Pent.', 'Dom. 11 p. Pent.', 'Dom. 25 p. Pent.', 'Dom. 20 p. Pent.', 'Dom. 10 p. Pent.', 'Dom. 9 p. Pent.', 'Dom. 5 p. Pent.']

In [27]:
srclink_dict = {source.siglum: source.srclink for source in corpus.sources}

In [46]:
from collections import defaultdict
import numpy as np

def construct_bipart_source_feast_reducted_graph(corpus, min_cid_per_feast, per_source_threshold = 0):
    """
    Construct a bipartite weighted graph where source nodes are connected to feast nodes
    while we consider only feasts that have at least min_cid_per_feast unique cantus IDs 
    across all sources
    """
    g = gt.Graph(directed=False)
    source_map, feast_map = {}, {}

    vprop_name = g.new_vertex_property("string")
    vprop_type = g.new_vertex_property("int")
    eprop_count = g.new_edge_property("int")
    eprop_weight = g.new_edge_property("double")

    # deetct bog enough feasts
    feast_sizes = defaultdict(set)
    for chant in corpus.chants:
        feast = chant.feast
        cantus_id = chant.cantus_id

        if feast is None or cantus_id is None:
            continue

        feast_sizes[feast].add(cantus_id)

    big_enough_feasts = {feast for feast, cantus_ids in feast_sizes.items() if len(cantus_ids) >= min_cid_per_feast}

    # unique Cantus IDs for each source-feast pair
    source_feast_cid = defaultdict(set)

    for chant in corpus.chants:
        source = chant.srclink
        feast = chant.feast
        cantus_id = chant.cantus_id

        if source is None or feast is None or cantus_id is None:
            continue
        if feast not in big_enough_feasts:
            continue

        source_feast_cid[(source, feast)].add(cantus_id)

    print("Constructing bipartite graph between sources and feasts...")

    for (source, feast), cantus_ids in source_feast_cid.items():
        if source not in source_map:
            source_vertex = g.add_vertex()
            source_map[source] = source_vertex
            vprop_name[source_vertex] = source
            vprop_type[source_vertex] = 0

        if feast not in feast_map:
            feast_vertex = g.add_vertex()
            feast_map[feast] = feast_vertex
            vprop_name[feast_vertex] = feast
            vprop_type[feast_vertex] = 1

        if len(cantus_ids) < per_source_threshold: # we are potentially not insterested in sources with very few chants connected to given feast
            continue
        edge = g.add_edge(source_map[source], feast_map[feast])
        count = len(cantus_ids)
        eprop_count[edge] = count
        eprop_weight[edge] = 0.5 if count == 1 else np.log2(count) # setting weight to 0.5 when only one chant

    g.vp["name"] = vprop_name
    g.vp["type"] = vprop_type

    g.ep["count"] = eprop_count
    g.ep["weight"] = eprop_weight

    print(f"Number of source nodes: {len(source_map)}")
    print(f"Number of feast nodes: {len(feast_map)}")
    print(f"Number of source-feast edges: {g.num_edges()}")

    return g, source_map, feast_map

In [47]:
graph, source_map, feast_map = construct_bipart_source_feast_reducted_graph(corpus, min_cid_per_feast=MIN_CID_PER_FEAST)

Constructing bipartite graph between sources and feasts...
Number of source nodes: 363
Number of feast nodes: 719
Number of source-feast edges: 53137

In [55]:
import graph_tool as gt
def between_partitions_edges(graph, source_map, feast_map, sigla_partitions, feast_partitions):
    """
    Get the number of edges between partitions in a bipartite graph.
    Get also the number of edges coming from source partitions.
    """
    between_edges = {}
    source_edges = {}
    for s_part, sigla_partition in sigla_partitions.items():
        for f_part, feast_partition in feast_partitions.items():
            count = 0
            for siglum in sigla_partition:
                srclink = srclink_dict[siglum]
                src_index = source_map[srclink]
                for feast in feast_partition:
                    feast_index = feast_map[feast]
                    if graph.edge(graph.vertex(src_index), graph.vertex(feast_index)) is not None:
                        count += 1
            between_edges[(s_part, f_part)] = count
            source_edges[s_part] = sum(between_edges[(s_part, f_part)] for f_part in feast_partition)
    return between_edges, source_edges

In [56]:
between_edges, source_edges = between_partitions_edges(graph, source_map, feast_map, sigla_partitions, feasts_partitions)

KeyError: (31, 'Nicolai')

#### DC-Nested-SBM

In [113]:
best_state = model.best_states['Nested_DC_SBM']

In [114]:
importlib.reload(utils)
print("Best Nested DC SBM state:")
print(best_state)
index_partitions, sigla_partitions, feasts_partitions = utils.get_nested_partitions_from_state(best_state, sigla_dict)

Best Nested DC SBM state:
<NestedBlockState object, with base <BlockState object with 1082 blocks (67 nonempty), degree-corrected, for graph <Graph object, undirected, with 1082 vertices and 53137 edges, 2 internal vertex properties, 2 internal edge properties, at 0x766de96c1ba0>, at 0x766ddb8ac7f0>, and 12 levels of sizes [(1082, 67), (67, 20), (20, 7), (7, 4), (4, 3), (3, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2)] at 0x766de9818d60>

In [115]:
print('Feast partitions:')
for level in feasts_partitions:
    print(f'Level {level}:')
    print(len(feasts_partitions[level]))
    for partition, feasts in feasts_partitions[level].items():
        print(f'Partition {partition}: {len(feasts)} {sorted(feasts)}')
    print()

Feast partitions:
Level 0:
29
Partition 60: 20 ['Agathae', 'Agnetis', 'Andreae', 'Annuntiatio Mariae', 'Benedicti', 'Cathedra Petri', 'Conversio Pauli', 'De BMV', 'Fabiani, Sebastiani', 'Gregorii', 'Joannis Evang.', 'Luciae', 'Nat. Innocentium', 'Nicolai', 'Pro defunctis', 'Purificatio Mariae', 'Silvestri', 'Stephani', 'Thomae Apost.', 'Vincentii']
Partition 660: 30 ['Ad Mandatum', 'Circumcisio Domini', 'Dom. 1 Adventus', 'Dom. 1 Quadragesimae', 'Dom. 1 p. Epiphaniam', 'Dom. 2 Adventus', 'Dom. 2 Quadragesimae', 'Dom. 2 p. Epiph.', 'Dom. 3 Adventus', 'Dom. 3 Quadragesimae', 'Dom. 3 p. Epiph.', 'Dom. 4 Adventus', 'Dom. 4 Quadragesimae', 'Dom. Quadragesimae', 'Dom. Quinquagesimae', 'Dom. Septuagesimae', 'Dom. Sexagesimae', 'Dom. de Passione', 'Dom. in Palmis', 'Dom. p. Epiphaniam', 'Dom. p. Nat. Dom.', 'Epiphania', 'Fer. 4 Q.T. Adventus', 'Fer. 5 in Cena Dom.', 'Fer. 6 in Parasceve', 'Nativitas Domini', 'Sabb. Septuagesimae', 'Sabbato Sancto', 'Vigilia Epiphaniae', 'Vigilia Nat. Domini']
Partition 1051: 15 ['Dom. 5 Quadragesimae', 'Fer. 2 Hebd. 2 p.Ep.', 'Fer. 2 p. Epiphaniam', 'Fer. 3 Hebd. 2 p.Ep.', 'Fer. 3 p. Epiphaniam', 'Fer. 4 Hebd. 2 p.Ep.', 'Fer. 4 p. Epiphaniam', 'Fer. 5 Hebd. 2 p.Ep.', 'Fer. 5 p. Epiphaniam', 'Fer. 6 Hebd. 2 p.Ep.', 'Fer. 6 Hebd. 5 Quad.', 'Fer. 6 p. Epiphaniam', 'Hebd. 3 Adventus', 'In tempore Epiphaniae', 'Sabb. Hebd. 2 p. Ep.']
Partition 189: 31 ['Die 5 p. Nat. Domini', 'Die 6 p. Nat. Domini', 'Fer. 2 Hebd. 1 Adv.', 'Fer. 2 Hebd. 3 Adv.', 'Fer. 2 Hebd. 4 Adv.', 'Fer. 3 Hebd. 1 Adv.', 'Fer. 3 Hebd. 3 Adv.', 'Fer. 3 Hebd. 4 Adv.', 'Fer. 4 Hebd. 1 Adv.', 'Fer. 4 Hebd. 3 Adv.', 'Fer. 4 Hebd. 4 Adv.', 'Fer. 5 Hebd. 3 Adv.', 'Fer. 5 Hebd. 4 Adv.', 'Fer. 6 Hebd. 1 Adv.', 'Fer. 6 Hebd. 3 Adv.', 'Fer. 6 Hebd. 4 Adv.', 'Hebd. 1 Adventus', 'Hebd. 1 Quad.', 'Hebd. 4 Adventus', 'Hebd. Nat. Dom.', 'Hebd. Septuagesimae', 'Meginrati', 'Oct. Joannis Evang.', 'Oct. Nat. Innocent.', 'Octava Nat. Domini,8', 'Octava Stephani', 'Sabb. p. Epiphaniam', 'Sabbato Hebd. 1 Adv.', 'Sabbato Hebd. 3 Adv.', 'Sabbato Hebd. 4 Adv.', 'Suff. Mariae Nat.']
Partition 554: 18 ['Aegidii', 'Ambrosii', 'Antonii', 'Augustini', 'Barnabae', 'Bartholomaei', 'Comm. unius Apostoli', 'Germani', 'Hieronimi', 'Jacobi', 'Lucae', 'Nazarii, Celsi', 'Oct. Apostolorum,8', 'Octava Laurentii', 'Petri, Mart.', 'Remigii', 'Transl. Benedicti', 'Transl. Martini']
Partition 289: 19 ['Ad Completorium', 'Die 2 p. Epiphaniam', 'Dom. 4 p. Epiph.', 'Dom. 5 p. Epiph.', 'Dom. p. Oct. Nat.', 'Dom. per annum', 'Epiphania,8', 'Feria 2 per annum', 'Feria 3 per annum', 'Feria 4 per annum', 'Feria 5 per annum', 'Feria 6 per annum', 'Hebd. 2 Adventus', 'Nat. Innocentium,8', 'Nativitas Domini,8', 'Octava Epiphaniae', 'Octava Nat. Domini', 'Sabb. Q.T. Adventus', 'Sabbato post Cineres']
Partition 149: 27 ['Ad Missam', 'Assumptio Mariae', 'Caeciliae', 'Clementis', 'Decoll. Jo. Bapt.', 'Exaltatio Crucis', 'Hippolyti', 'Inventio Crucis', 'Joannis Baptistae', 'Joannis Port. Lat.', 'Joannis, Pauli', 'Laurentii', 'Marci', 'Mariae Magdalenae', 'Martialis, Epi.', 'Martini', 'Michaelis', 'Nativitas Mariae', 'Octava Apostolorum', 'Omnium Sanctorum', 'Pauli', 'Petri', 'Petri, Pauli', 'Petri, Pauli,8', 'Philippi, Jacobi', 'Transfiguratio Dom.', 'Vincula Petri']
Partition 285: 46 ['Aciscli', 'Aemiliani Cucullati', 'Allisionis Infantum', 'Assumptio Mariae (Hispanic rite)', 'Carnes Tollendas', 'Columbae', 'Commune Virginum', 'Commune unius Martyris TP', 'Commune unius Virginis', 'Cucuphatis', 'De Sacratione Baselice', 'De uno defuncto', 'De uno justi', 'Dom. Quotidiano', 'Dunstani', 'Engratiae', 'Eugeniae', 'Eulaliae Barcinonensis', 'Eulaliae Emeritensis', 'Exspectationis BMV', 'Felicis Gerundae', 'Fer. 5 de Letanias Apostolicas', 'Fer. 6 de Letanias Apostolicas', 'Fest. per annum', 'Fructuosi, Augurii et Eulogii', 'Genesii', 'Geraldi', 'Jacobi fratris Domini', 'Juliani', 'Justae, Rufinae', 'Justi, Pastoris', 'Leocadiae', 'Letanias', 'Letanias Apostolicas', 'Letanias Canonicas', 'Letanias de Clade', 'Primitis', 'Pro defunctis Sacerdotibus', 'Pro uno infirmo', 'Purificatio Mariae,8', 'Romani', 'Saturnini', 'Suff. Adventus', 'Swithuni', 'Torquati et sociorum', 'Transl. Indalaetii']
Partition 634: 32 ['Ascensio Domini', 'De Trinitate', 'Dom. 1 p. Epiph.,8', 'Dom. 1 p. Pent.', 'Dom. 2 p. Pascha', 'Dom. 2 p. Pascha,8', 'Dom. 3 p. Pascha', 'Dom. 3 p. Pascha,8', 'Dom. 4 p. Pascha', 'Dom. 4 p. Pascha,8', 'Dom. 5 p. Pascha', 'Dom. Pentecostes', 'Dom. Pentecostes,8', 'Dom. Resurrect.,8', 'Dom. Resurrectionis', 'Dom. p. Ascensionem', 'Fer. 2 Pent.', 'Fer. 2 p. Pascha', 'Fer. 3 Pent.', 'Fer. 3 p. Pascha', 'Fer. 4 Pent.', 'Fer. 4 p. Pascha', 'Fer. 5 Pent.', 'Fer. 5 p. Pascha', 'Fer. 6 Pent.', 'Fer. 6 p. Pascha', 'In Letaniis', 'Octava Paschae', 'Octava Pentecostes', 'Sabbato Pent.', 'Sabbato in Albis', 'Vigilia Pentecostes']
Partition 305: 26 ['De Trinitate,8', 'Fer. 2 Hebd. 3 Pasc.', 'Fer. 2 Hebd. 4 Pasc.', 'Fer. 2 Hebd. 5 Pasc.', 'Fer. 2 p. Ascensio.', 'Fer. 2 p. Oct.Pasch.', 'Fer. 3 Hebd. 3 Pasc.', 'Fer. 3 Hebd. 4 Pasc.', 'Fer. 3 p. Oct.Pasch.', 'Fer. 4 Hebd. 3 Pasc.', 'Fer. 4 Hebd. 4 Pasc.', 'Fer. 4 Hebd. 5 Pasc.', 'Fer. 4 p. Oct.Pasch.', 'Fer. 5 p. Oct.Pasch.', 'Fer. 6 p. Ascensio.', 'Fer. 6 p. Oct. Asc.', 'Fer. 6 p. Oct.Pasch.', 'Feria 2 TP', 'Hebd. 2 p. Pascha', 'Hebd. 3 p. Pascha', 'Hebd. TP', 'Oct. Ascens. Domini', 'Sabb. p. Ascensionem', 'Sabb. p. Oct. Asc.', 'Sabb. p. Oct. Pasch.', 'Suff. Om. Sanctorum']
Partition 485: 33 ['Acacii et sociorum', 'Adalberti', 'Afrae', 'Comm. Virginum', 'Comm. plur. Conf.', 'Comm. plur. Mart.', 'Comm. unius Conf.', 'Comm. unius Mart.', 'Comm. unius Virg.', 'Commune apostolorum', 'Commune plurimorum Martyrum', 'Commune unius Confessoris', 'Commune unius Martyris', 'Compassio Mariae TP', 'Divisio Apostolorum', 'Emmerami', 'Galli', 'Georgii, Adalberti', 'In Dedicat. Eccl. TP', 'Kiliani et Soc.', 'Ladislai', 'Ludmilae', 'Margaritae', 'Octava de Trinitate', 'Oswaldi, Reg.', 'Othmari', 'Pirmini', 'Procopii Sázaviensis', 'Stephani, Reg.', 'Tiburtii, Valeriani, Maximi', 'Transl. Adalberti', 'Viti et sociorum', 'Wenceslai']
Partition 754: 35 ['Amandi', 'Antonini', 'Arnulfi Metensis', 'Bonifacii', 'Callisti', 'Christophori', 'Chrysanthi, Dariae', 'Columbani', 'Constantii', 'Crispini,Crispiniani', 'Dionysii,8', 'Eligii', 'Eustachii', 'Felicitatis', 'Fidis', 'Gereonis et soc.', 'Germani Parisien.', 'Hermagorae,Fortunati', 'Januarii et Soc.', 'Julianae', 'Lamberti', 'Leodegarii', 'Leonardi', 'Magni', 'Octava Tr. Benedicti', 'Pancratii et Soc.', 'Pantaleonis', 'Pelagii', 'Philiberti', 'Quintini', 'Remacli', 'Transl. Benedicti,8', 'Udalrici', 'Walburgae', 'Willibrordi']
Partition 900: 33 ['Angeli Custodis', 'Annae', 'Bernardi', 'Catharinae', 'Comm. unius Confessoris non Pontificis', 'Comm. unius Virginis Martyris', 'Commune Apostolorum', 'Commune Apostolorum TP', 'Commune BMV', 'Corporis Christi', 'De BMV post Pent.', 'De Corona Spinea', 'De Sancta Lancea', 'Decem Millium Martyrum', 'Dominici', 'Elisabeth Hung.', 'Floriani', 'Genulfi', 'Hedwigis', 'Joannis Baptistae,8', 'Mariae ad Nives', 'Marinae', 'Marthae', 'Monicae', 'Nativitas Mariae,8', 'Omnium Sanctorum,8', 'Patriarcharum', 'Praesentatio Mariae', 'Servatii', 'Transl. Stanislai', 'Tres Mariae', 'Ursulae', 'Visitatio Mariae']
Partition 974: 12 ['Comm. Apostolorum', 'Comm. Evangelistarum', 'Comm. plurimorum Martyrum', 'Comm. plurimorum Martyrum TP', 'Comm. plurimorum Virginum', 'Comm. unius Confessoris', 'Comm. unius Confessoris Pontificis', 'Comm. unius Martyris', 'Comm. unius Virginis', 'Dom. p. Pent.', 'Edmundi', 'In tempore Paschae']
Partition 1021: 15 ['Antonii Patavini', 'Appar. Michaelis', 'Clarae', 'Comm. Conjungium', 'Comm. plurimorum Confessorum Pontificum', 'Comm. plurimorum Confessorum non Pontificum', 'De BMV Adv.', 'De BMV Nat.', 'De BMV TP', 'De Sanctis', 'Francisci', 'Hebd. Adventus', 'Hebd. Sancta', 'In tempore Adventus', 'In tempore Quad.']
Partition 1045: 38 ['Dedic. S.Salv., Mar.', 'Fer. 2 Hebd. 1 Quad.', 'Fer. 2 Hebd. 2 Quad.', 'Fer. 2 Hebd. 3 Quad.', 'Fer. 2 Hebd. 4 Quad.', 'Fer. 2 Maj. Hebd.', 'Fer. 2 de Passione', 'Fer. 3 Hebd. 1 Quad.', 'Fer. 3 Hebd. 2 Quad.', 'Fer. 3 Hebd. 3 Quad.', 'Fer. 3 Hebd. 4 Quad.', 'Fer. 3 Maj. Hebd.', 'Fer. 3 de Passione', 'Fer. 4 Cinerum', 'Fer. 4 Hebd. 1 Quad.', 'Fer. 4 Hebd. 2 Quad.', 'Fer. 4 Hebd. 3 Quad.', 'Fer. 4 Hebd. 4 Quad.', 'Fer. 4 Maj. Hebd.', 'Fer. 4 de Passione', 'Fer. 5 Hebd. 1 Quad.', 'Fer. 5 Hebd. 2 Quad.', 'Fer. 5 Hebd. 3 Quad.', 'Fer. 5 Hebd. 4 Quad.', 'Fer. 5 de Passione', 'Fer. 5 post Cineres', 'Fer. 6 Hebd. 1 Quad.', 'Fer. 6 Hebd. 2 Quad.', 'Fer. 6 Hebd. 3 Quad.', 'Fer. 6 Hebd. 4 Quad.', 'Fer. 6 de Passione', 'Fer. 6 post Cineres', 'Sabb. Hebd. 1 Quad.', 'Sabb. Hebd. 2 Quad.', 'Sabb. Hebd. 3 Quad.', 'Sabb. Hebd. 4 Quad.', 'Sabb. Quadragesimae', 'Sabb. de Passione']
Partition 291: 44 ['Abdonis, Sennis', 'Agapiti', 'Apollinaris', 'Basilidis et Soc.', 'Chrysogoni', 'Cyriaci et Soc.', 'Cyrici', 'Ded.Mont.S.Michaelis', 'Dionysii et socii', 'Donati', 'Euphemiae', 'Felicis, Adaucti', 'Felicissimi, Agapiti', 'Fer. 6 Q.T. Quad.', 'Gervasii, Protasii', 'Gorgonii', 'Hermetis', 'In tempore belli', 'Laurentii,8', 'Luciae, Germiniani', 'Marcellini, Petri', 'Marci, Marcellini', 'Marci, Pont.', 'Odilonis', 'Praxedis', 'Primi, Feliciani', 'Pro Sacerdote', 'Processi, Martiniani', 'Proti, Hiacinthi', 'Quat. Coronatorum', 'Sabinae', 'Sebastiani', 'Septem Fratrum', 'Simplicii et Soc.', 'Sixti', 'Stephani, Pont.', 'Theodori Tiro', 'Tiburtii', 'Timothei', 'Urbani', 'Victoris et Soc.', 'Vig. Assump. Mariae', 'Vig. Joannis Bapt.', 'Vig. Om. Sanctorum']
Partition 81: 31 ['Adventus, dom. 1', 'Adventus, dom. 2', 'Adventus, dom. 3', 'Adventus, dom. 4', 'Assumptio Mariae, infra oct.', 'Dom. mensis Septembris', 'Dominica in Albis (Octava Paschae)', 'Fabiani et Sebastiani', 'Geraldi Archiepiscopi Bracharensis', 'Joannis Baptistae., vig.', 'Jonnis Baptistae, decol.', 'Nativitas Domini, vig.', 'Pauli, conversio', 'Pentecostes', 'Petri et Pauli', 'Petri, Pauli, vig.', 'Philippi et Jacobi', 'Purificatio Mariae [Presentationis Domini]', 'Quadrag., hebd. 1, fer. 2', 'Quadragesimae, dom. 1', 'Quadragesimae, dom. 2', 'Quadragesimae, dom. 3', 'Quadragesimae, dom. 4', 'Quinquagesimae, dom.', 'Sanctissimae Trinitatis', 'Septuagesimae, dom.', 'Sexagesimae, dom.', 'Stephani, inventio', 'Thomae', 'Transfiguratio Domini', 'undetermined']
Partition 201: 17 ['Ad Processionem', 'Apostolorum et Evangelistarum', 'Comm. unius Apostolus', 'De Sancta Cruce', 'Dom. post Ascensionem', 'Fer. 6 Q.T. Adventus', 'In Dedicatione Ecclesiae', 'In Letaniis maj.', 'Martialis, Apost.', 'Mauritii et sociorum', 'Medardi', 'Pro ordinatione Episcopi', 'Sabbato Q.T. Adventus', 'Sabbato Q.T. Pent.', 'Sabbato Q.T. Sept.', 'Valeriae', 'Vig. Ascensio Domini']
Partition 65: 48 ['Aichardi', 'Andreae,8', 'Audoeni', 'Barbarae', 'Blasii', 'Comm. plurimorum Confessorum', 'Comm. unius Abbatis', 'Comm. unius Confessoris Abbatis', 'Comm. unius Confessoris et Episcopi', 'Comm. unius Confessoris non Episcopus', 'Comm. unius Martyris Pontificis', 'Comm. unius Martyris non Pontificis', 'Comm. unius Virginis non Martyris', 'Commune plurimorum Martyrum TP', 'Commune unius Confessoris Epi.', 'Conceptio Mariae', 'Cuthberti', 'De BMV post Epiph.', 'De BMV post Purif.', 'Dorotheae', 'Firmini', 'Gaugerici', 'Gertrudis Nivellensis', 'Helenae', 'In tempore Nat.', 'Joannis Evang.,8', 'Judoci', 'Justinae, Cypriani', 'Lazari', 'Mariae Aegyptiacae', 'Materni', 'Matthiae', 'Mauri', 'Nicasii', 'Oct. Om. Sanctorum', 'Octava Agnetis', 'Octava Andreae', 'Octava Apostolorum Petri et Pauli', 'Oswaldi, Epi.', 'Reliquiarum', 'Rictrudis', 'Scholasticae', 'Stephani,8', 'Suscept. Reliquiarum', 'Thomae Cant.', 'Thomae de Aquino', 'Vedasti', 'Wulstani']
Partition 770: 15 ['Ascensio Domini,8', 'Assumptio Mariae,8', 'Briccii', 'Dionysii', 'Dom. mensis Nov.', 'Dom. p. Assumptionem', 'Dom. p. Cor. Christi', 'Inventio Stephani', 'Martini,8', 'Mauritii', 'Octava Assumptionis', 'Octava Martini', 'Symphoriani', 'Tiburtii, Susannae', 'XI milium Virginum']
Partition 983: 21 ['1D', '2D', '3D', '6f5', 'Corp', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D70', 'Ded.Eccl.', 'H6/S', 'H6/f5', 'H6/f6', 'Joh.ap.', 'Mort', 'Nat', 'Purif.BMV', 'Trin']
Partition 763: 12 ['Ad Suffragium', 'Dom. Adventus', 'Fer. 2 per annum', 'Fer. 3 per annum', 'Fer. 4 per annum', 'Fer. 5 per annum', 'Fer. 6 per annum', 'Hebd. Quinquagesimae', 'Hebd. de Passione', 'Hebd. per annum', 'Sabbato per annum', 'Suff. Mariae Adv.']
Partition 394: 8 ['Adriani', 'Cornelii, Cypriani', 'Cosmae, Damiani', 'Georgii', 'Matthaei', 'Mennae', 'Nicomedis', 'Simonis, Judae']
Partition 721: 37 ['Ad Magnificat', 'Additamenta', 'Alexandri et sociorum', 'Baboleni', 'Caroli Magni', 'Comm. Apostolorum TP', 'Comm. un. Conf.Pont.', 'Comm. unius Confessoris TP', 'Comm. unius Martyris TP', 'De Sanctis TP', 'Dedic. S. Salvatoris', 'Dom. 25 p. Pent.', 'Dominica TP', 'Dominica in estate', 'Dominici Silensis', 'Hilarii Arelatensis', 'Hymni', 'In Dedicatione Eccl.', 'Invitatoria', 'Ludmillae', 'Octava Amandi', 'Octava Martialis', 'Octava Nat. Mariae', 'Recollectio Mariae', 'Relatio Vedasti', 'Sabae', 'Sabbato TP', 'Suff. Crucis', 'Suff. Mariae', 'Syri', 'Tr. Kunegundis', 'Transl. Baboleni', 'Transl. Francisci', 'Transl. Lamberti', 'Transl. Stanislai Episcopi', 'Transl. Trium Regum', 'Transl. Wolfgangi']
Partition 759: 11 ['Ad Benedicite', 'De Esther', 'De Job', 'De Judith', 'De Machabaeis', 'De Prophetis', 'De Regum', 'De Sapientia', 'De Tobia', 'Dom. mensis Octobris', 'Octava Joannis Bapt.']
Partition 1029: 23 ['Dom. 10 p. Pent.', 'Dom. 11 p. Pent.', 'Dom. 12 p. Pent.', 'Dom. 13 p. Pent.', 'Dom. 14 p. Pent.', 'Dom. 15 p. Pent.', 'Dom. 16 p. Pent.', 'Dom. 17 p. Pent.', 'Dom. 18 p. Pent.', 'Dom. 19 p. Pent.', 'Dom. 2 p. Pent.', 'Dom. 20 p. Pent.', 'Dom. 21 p. Pent.', 'Dom. 22 p. Pent.', 'Dom. 23 p. Pent.', 'Dom. 24 p. Pent.', 'Dom. 3 p. Pent.', 'Dom. 4 p. Pent.', 'Dom. 5 p. Pent.', 'Dom. 6 p. Pent.', 'Dom. 7 p. Pent.', 'Dom. 8 p. Pent.', 'Dom. 9 p. Pent.']
Partition 178: 16 ['Agnetis,8', 'Alexandri et Soc.', 'Felicis', 'Felicis Nolani', 'Fer. 4 Q.T. Pent.', 'Gordiani, Epimachi', 'Marcelli', 'Marcelli, Pont.', 'Priscae', 'Pro infirmis', 'Pro iter agentibus', 'Pro pluvia', 'Tiburtii, Valeriani', 'Valentini', 'Vigilia Petri', 'Vitalis']
Partition 502: 6 ['Fer. 2 in Letaniis', 'Fer. 3 in Letaniis', 'Fer. 4 in Letaniis', 'Hilarii', 'Justi', 'Octava Paschae,8']

Level 1:
10
Partition 46: 132 ['Ad Mandatum', 'Ad Missam', 'Agathae', 'Agnetis', 'Andreae', 'Annuntiatio Mariae', 'Ascensio Domini', 'Assumptio Mariae', 'Benedicti', 'Caeciliae', 'Cathedra Petri', 'Circumcisio Domini', 'Clementis', 'Conversio Pauli', 'De BMV', 'De Trinitate', 'Decoll. Jo. Bapt.', 'Dom. 1 Adventus', 'Dom. 1 Quadragesimae', 'Dom. 1 p. Epiph.,8', 'Dom. 1 p. Epiphaniam', 'Dom. 1 p. Pent.', 'Dom. 10 p. Pent.', 'Dom. 11 p. Pent.', 'Dom. 12 p. Pent.', 'Dom. 13 p. Pent.', 'Dom. 14 p. Pent.', 'Dom. 15 p. Pent.', 'Dom. 16 p. Pent.', 'Dom. 17 p. Pent.', 'Dom. 18 p. Pent.', 'Dom. 19 p. Pent.', 'Dom. 2 Adventus', 'Dom. 2 Quadragesimae', 'Dom. 2 p. Epiph.', 'Dom. 2 p. Pascha', 'Dom. 2 p. Pascha,8', 'Dom. 2 p. Pent.', 'Dom. 20 p. Pent.', 'Dom. 21 p. Pent.', 'Dom. 22 p. Pent.', 'Dom. 23 p. Pent.', 'Dom. 24 p. Pent.', 'Dom. 3 Adventus', 'Dom. 3 Quadragesimae', 'Dom. 3 p. Epiph.', 'Dom. 3 p. Pascha', 'Dom. 3 p. Pascha,8', 'Dom. 3 p. Pent.', 'Dom. 4 Adventus', 'Dom. 4 Quadragesimae', 'Dom. 4 p. Pascha', 'Dom. 4 p. Pascha,8', 'Dom. 4 p. Pent.', 'Dom. 5 p. Pascha', 'Dom. 5 p. Pent.', 'Dom. 6 p. Pent.', 'Dom. 7 p. Pent.', 'Dom. 8 p. Pent.', 'Dom. 9 p. Pent.', 'Dom. Pentecostes', 'Dom. Pentecostes,8', 'Dom. Quadragesimae', 'Dom. Quinquagesimae', 'Dom. Resurrect.,8', 'Dom. Resurrectionis', 'Dom. Septuagesimae', 'Dom. Sexagesimae', 'Dom. de Passione', 'Dom. in Palmis', 'Dom. p. Ascensionem', 'Dom. p. Epiphaniam', 'Dom. p. Nat. Dom.', 'Epiphania', 'Exaltatio Crucis', 'Fabiani, Sebastiani', 'Fer. 2 Pent.', 'Fer. 2 p. Pascha', 'Fer. 3 Pent.', 'Fer. 3 p. Pascha', 'Fer. 4 Pent.', 'Fer. 4 Q.T. Adventus', 'Fer. 4 p. Pascha', 'Fer. 5 Pent.', 'Fer. 5 in Cena Dom.', 'Fer. 5 p. Pascha', 'Fer. 6 Pent.', 'Fer. 6 in Parasceve', 'Fer. 6 p. Pascha', 'Gregorii', 'Hippolyti', 'In Letaniis', 'Inventio Crucis', 'Joannis Baptistae', 'Joannis Evang.', 'Joannis Port. Lat.', 'Joannis, Pauli', 'Laurentii', 'Luciae', 'Marci', 'Mariae Magdalenae', 'Martialis, Epi.', 'Martini', 'Michaelis', 'Nat. Innocentium', 'Nativitas Domini', 'Nativitas Mariae', 'Nicolai', 'Octava Apostolorum', 'Octava Paschae', 'Octava Pentecostes', 'Omnium Sanctorum', 'Pauli', 'Petri', 'Petri, Pauli', 'Petri, Pauli,8', 'Philippi, Jacobi', 'Pro defunctis', 'Purificatio Mariae', 'Sabb. Septuagesimae', 'Sabbato Pent.', 'Sabbato Sancto', 'Sabbato in Albis', 'Silvestri', 'Stephani', 'Thomae Apost.', 'Transfiguratio Dom.', 'Vigilia Epiphaniae', 'Vigilia Nat. Domini', 'Vigilia Pentecostes', 'Vincentii', 'Vincula Petri']
Partition 64: 21 ['Dom. 5 Quadragesimae', 'Fer. 2 Hebd. 2 p.Ep.', 'Fer. 2 in Letaniis', 'Fer. 2 p. Epiphaniam', 'Fer. 3 Hebd. 2 p.Ep.', 'Fer. 3 in Letaniis', 'Fer. 3 p. Epiphaniam', 'Fer. 4 Hebd. 2 p.Ep.', 'Fer. 4 in Letaniis', 'Fer. 4 p. Epiphaniam', 'Fer. 5 Hebd. 2 p.Ep.', 'Fer. 5 p. Epiphaniam', 'Fer. 6 Hebd. 2 p.Ep.', 'Fer. 6 Hebd. 5 Quad.', 'Fer. 6 p. Epiphaniam', 'Hebd. 3 Adventus', 'Hilarii', 'In tempore Epiphaniae', 'Justi', 'Octava Paschae,8', 'Sabb. Hebd. 2 p. Ep.']
Partition 49: 50 ['Ad Completorium', 'Die 2 p. Epiphaniam', 'Die 5 p. Nat. Domini', 'Die 6 p. Nat. Domini', 'Dom. 4 p. Epiph.', 'Dom. 5 p. Epiph.', 'Dom. p. Oct. Nat.', 'Dom. per annum', 'Epiphania,8', 'Fer. 2 Hebd. 1 Adv.', 'Fer. 2 Hebd. 3 Adv.', 'Fer. 2 Hebd. 4 Adv.', 'Fer. 3 Hebd. 1 Adv.', 'Fer. 3 Hebd. 3 Adv.', 'Fer. 3 Hebd. 4 Adv.', 'Fer. 4 Hebd. 1 Adv.', 'Fer. 4 Hebd. 3 Adv.', 'Fer. 4 Hebd. 4 Adv.', 'Fer. 5 Hebd. 3 Adv.', 'Fer. 5 Hebd. 4 Adv.', 'Fer. 6 Hebd. 1 Adv.', 'Fer. 6 Hebd. 3 Adv.', 'Fer. 6 Hebd. 4 Adv.', 'Feria 2 per annum', 'Feria 3 per annum', 'Feria 4 per annum', 'Feria 5 per annum', 'Feria 6 per annum', 'Hebd. 1 Adventus', 'Hebd. 1 Quad.', 'Hebd. 2 Adventus', 'Hebd. 4 Adventus', 'Hebd. Nat. Dom.', 'Hebd. Septuagesimae', 'Meginrati', 'Nat. Innocentium,8', 'Nativitas Domini,8', 'Oct. Joannis Evang.', 'Oct. Nat. Innocent.', 'Octava Epiphaniae', 'Octava Nat. Domini', 'Octava Nat. Domini,8', 'Octava Stephani', 'Sabb. Q.T. Adventus', 'Sabb. p. Epiphaniam', 'Sabbato Hebd. 1 Adv.', 'Sabbato Hebd. 3 Adv.', 'Sabbato Hebd. 4 Adv.', 'Sabbato post Cineres', 'Suff. Mariae Nat.']
Partition 16: 70 ['Abdonis, Sennis', 'Adriani', 'Aegidii', 'Agapiti', 'Ambrosii', 'Antonii', 'Apollinaris', 'Augustini', 'Barnabae', 'Bartholomaei', 'Basilidis et Soc.', 'Chrysogoni', 'Comm. unius Apostoli', 'Cornelii, Cypriani', 'Cosmae, Damiani', 'Cyriaci et Soc.', 'Cyrici', 'Ded.Mont.S.Michaelis', 'Dionysii et socii', 'Donati', 'Euphemiae', 'Felicis, Adaucti', 'Felicissimi, Agapiti', 'Fer. 6 Q.T. Quad.', 'Georgii', 'Germani', 'Gervasii, Protasii', 'Gorgonii', 'Hermetis', 'Hieronimi', 'In tempore belli', 'Jacobi', 'Laurentii,8', 'Lucae', 'Luciae, Germiniani', 'Marcellini, Petri', 'Marci, Marcellini', 'Marci, Pont.', 'Matthaei', 'Mennae', 'Nazarii, Celsi', 'Nicomedis', 'Oct. Apostolorum,8', 'Octava Laurentii', 'Odilonis', 'Petri, Mart.', 'Praxedis', 'Primi, Feliciani', 'Pro Sacerdote', 'Processi, Martiniani', 'Proti, Hiacinthi', 'Quat. Coronatorum', 'Remigii', 'Sabinae', 'Sebastiani', 'Septem Fratrum', 'Simonis, Judae', 'Simplicii et Soc.', 'Sixti', 'Stephani, Pont.', 'Theodori Tiro', 'Tiburtii', 'Timothei', 'Transl. Benedicti', 'Transl. Martini', 'Urbani', 'Victoris et Soc.', 'Vig. Assump. Mariae', 'Vig. Joannis Bapt.', 'Vig. Om. Sanctorum']

In [116]:
for level in sigla_partitions:
    print(f'Level {level}:')
    print(len(sigla_partitions[level]))
    for partition, sigla in sigla_partitions[level].items():
        print(f'Partition {partition}: {len(sigla)} : {sorted(sigla)}')
    print()

Level 0:
38
Partition 645: 17 : ['A-Gu 29 (olim 38/8 f.)', 'A-KN CCl 1010', 'A-KN CCl 1017', 'A-Wda C-11', 'B-TOb 63 (olim V)', 'B-TOb 64 (olim IV)', 'CDN-Hsmu M2149.L4 1554', 'CH-SGs 390', 'CZ-Pu VI.E.4c', 'CZ-Pu XIV.B.13', 'D-KNd 1161', 'D-Mbs Clm 4303', 'H-Bu lat. 118', 'I-BV V 19', 'I-VCd CLXX', 'PL-Kkar Ms.2 (rkp. Perg. 14)', 'PL-Kkar Ms.5 (rkp. Perg. 13)']
Partition 315: 3 : ['A-Gu 30 (olim 38/9 f.)', 'CZ-Bu R 387', 'CZ-Pu VI E 13']
Partition 606: 3 : ['A-LIb 290 (olim 183; olim Gamma p 19)', 'A-Wn Cod. 1890', 'CZ-Pu VI G 11']
Partition 164: 19 : ['A-SF XI 480', 'A-Wn Cod. 1799**', 'CDN-Mrb MS Medieval 0234', 'CH-E 611', 'CH-SGs 388', 'D-AAm G 20', 'D-B Mus. 40047', 'D-BAs Msc.Lit.25 (olim Ed.IV.11)', 'D-KA Aug. LX', 'D-KNd 215', 'D-Sl HB.I.55', 'E-Tc 44.2', 'F-Pn Latin 12044', 'F-VAL 114', 'GB-Ob MS. Canon. Liturg. 202', 'GB-Ob MS. Laud Misc. 284', 'I-Far s.c.', 'I-Rv C.5', 'TR-Itks Deissmann 42']
Partition 4: 8 : ['CZ-Pn (Praha) XII A 21', 'CZ-Pu XII C 3', 'CZ-Pu XIII C 4', 'CZ-Pu XIV C 20', 'CZ-R R 17', 'D-W Cod. Guelf. 28 Helmst. (Heinemann-Nr. 31)', 'SK-Bra BAI ECLad.3', 'SK-Sk 2']
Partition 259: 7 : ['CDN-Ttfl MSS 09700', 'CZ-Pn XV A 10', 'CZ-Pu Pu XIV A 19', 'D-MZb B', 'D-W Cod. Guelf. 29 Helmst. (Heinemann-Nr. 32)', 'E-Bbc M 705', 'E-H Ms. 2']
Partition 322: 7 : ['CZ-Pst DE I 7', 'E-Bbc M 663', 'E-Bbc M 706', 'F-Pn NAL 1411', 'PL-PŁsem MsEPl 12', 'PL-Wn  rps 12720 V', 'SK-Bra BAIII ECLad.6']
Partition 657: 7 : ['D-B Theol. Lat. Qu. 149', 'E-BAR, s.s.', 'E-H Ms. 7 (ant. 5)', 'E-Tc 35.5', 'E-VI Mss. 113-114', 'SK-BRsa SNA 2', 'SK-BRsa SNA 4']
Partition 152: 12 : ['A-KR Schachtel VI/258', 'A-VOR 287 (olim XXIX)', 'A-Wda D-4', 'Cantus MA Impr. 1537', 'F-CA 38 (olim 40)', 'GB-Cu Mm.ii.9', 'I-AO 6', 'I-PCd cod. 65', 'NL-Uu Ms. 406 (shelfmark 3 J 7)', 'PL-KIk Ms. 1', 'PL-Klk 1', 'PL-WRu Ms. R 503']
Partition 569: 7 : ['A-KN CCl 1013', 'Cantus GOTTSCHALK', 'F-Pn Latin 15181', 'F-Pn NAL 1236', 'F-TOm 149', 'I-CHV s.c.', 'SI-Lna 18 (olim 17)']
Partition 572: 7 : ['E-SI MS 9', 'F-AS 465 (CGM 893)', 'F-CA Impr. XVI C 4', 'GB-AB 20541 E', 'GB-WO F. 160 (olim 1247) (facsimile)', 'GB-WO F. 160 (olim 1247) (with hymnal)', 'V-CVbav San Pietro B.79']
Partition 451: 13 : ['CZ-Pu VI G 3a', 'D-MZb E', 'D-Mbs Clm 4304', 'D-Mbs Clm 4305', 'E-Bbc Ms. 2322', 'F-Pn NAL 1412', 'F-R 248 (olim  A. 339)', 'H-Bu lat. 122', 'HR-Hf Cod. E Nr. 3', 'P-AR Res. Ms. 025', 'P-BRs Ms. 028', 'PL-Kkar Ms.1 (rkp. Perg. 12)', 'PL-PŁsem MsEPl 12']
Partition 105: 4 : ['P-AR Res. Ms. 021', 'P-BRs Ms. 032', 'P-EVpc 000', 'P-Ln RES. 253 P.']
Partition 27: 7 : ['A-KN CCl 1011', 'A-KN CCl 1015', 'CZ-Pn XII A 24', 'D-MZb A', 'DK-Kk Gl. Kgl. S. 3449 8o [02] II', 'HR-Hf Cod. C Nr. 4', 'PL-GD Mar. F 408']
Partition 144: 8 : ['CH-Fco Ms. 2', 'D-Ma 12o Cmm 1', 'I-Ac 693', 'I-Ac 694', 'I-Ad 5', 'I-Nn vi. E. 20', 'US-Cn 24', 'V-CVbav lat. 8737']
Partition 140: 18 : ['D-Mbs Clm 4306', 'E-Bbc M 888', 'E-Bbc Ms. 619', 'E-Gs ms. 45 (olim Sant Feliu, 20)', 'E-Tc 44.1', 'F-AI 44', 'F-Pn Lat. 17296', 'F-Pn Latin 1085', 'F-Pn Latin 1090', 'F-Pn Latin 1240', 'F-Pn NAL 1535', 'GB-Lbl Add MS 30848', 'GB-Lbl Add MS 30849', 'GB-Lbl Add MS 30850', 'I-Fl Conv. sopp. 560', 'I-Lc 601', 'I-MZ 15/79', 'PL-WRu I F 401']
Partition 979: 8 : ['Antifonario s.s.', 'CZ-Pu XII E 15c', 'E-Bbc M 785', 'E-E L. III. 3.', 'E-E L. III. 4.', 'E-H Ms. 9 (ant. 25)', 'E-LUc s.s.', 'GB-Lbl Add MS 30845']
Partition 232: 10 : ['CH-SGs Cod 378', 'CH-SGs Cod 380', 'CH-SGs Cod 484', 'E-Bbc M 662', 'E-SA 6', 'F-LA Ms 263', 'F-Pn Lat. 10510', 'F-Pn Lat. 1118', 'F-Pn Lat. 9448', 'F-SO 596']
Partition 382: 46 : ['B-Br Ms II 3823', 'CH-E Codex 121', 'CH-SGs Cod 338', 'CH-SGs Cod 340', 'CH-SGv VadSlg Ms 0295', 'CZ-Pn XIV D 12', 'CZ-R R 396', 'D-B Ms mus 40078', 'D-BAa Msc Lit 6', 'D-BAa Msc Lit 7', 'D-Ful Aa 0006', 'D-Mbs Clm 03005', 'D-Mbs Clm 14965b', 'E-Bbc M 648', 'E-Bbc Ms. 1805', 'E-Mh Cód. 51', 'F-AI Ms 0044', 'F-AN Ms 0091', 'F-AUT Ms S 0010 (8*)', 'F-CA Ms 0061 (62)', 'F-CA Ms 0075 (76)', 'F-CHRm Ms 0047 (40)', 'F-Collection privée Mont-Renaud', 'F-LA Ms 118', 'F-LA Ms 236', 'F-LA Ms 239', 'F-NS Ms 0004', 'F-Pm Ms 0384', 'F-Pn Lat. 1087', 'F-Pn Lat. 12050', 'F-Pn Lat. 12584', 'F-Pn Lat. 2291', 'F-Pn Lat. 9439', 'F-Pn NAL 1669', 'F-SOM Ms 0252', 'GB-Lbl Egerton 857', 'GB-Lbl Harley 4951', 'I-BGc MA 150 (Psi III.8)', 'I-BGc MA 239 (Gamma III.18)', 'I-BV 34', 'I-Bc Q 09', 'I-Tn G.V.20', 'Reconstitution Sacramentaire de Tours (TU1)', 'V-CVbav Archivio di San Pietro F.22', 'V-CVbav Ross.0076', 'V-CVbav Vat. lat. 5319']
Partition 328: 9 : ['D-Kl Theol. quart 0015', 'E-Mn MSS/10110', 'F-LA Ms 240', 'F-Pn Lat. 9449', 'GB-Lbl Add MS 30847', 'HR-Hf Cod. D Nr. 5', 'I-MC 542', 'NL-Uu Hs. 0062', 'PL-STAb ms. 2']
Partition 595: 12 : ['A-KN CCl 1018', 'A-KN CCl 589', 'A-Wda C-10', 'B-Gu Hs BKT.006', 'CH-SGs 391', 'D-FUl Aa 55', 'D-MZb C', 'I-BV V 20', 'NL-ZUa 6', 'NZ-Wt MSR-03', 'PL-Kkar Ms.3 (rkp. Perg. 15)', 'US-Cai 1911.142b']
Partition 673: 6 : ['A-KN CCl 1012', 'D-MZb D', 'F-Pn Lat. 1030', 'F-Pn Latin 12601', 'F-Pn Latin 15182', 'SI-Lna 19 (olim 18)']
Partition 169: 4 : ['E-MO Ms. 72', 'H-Bu lat. 121', 'PL-Kkar Ms.4 (rkp. Perg. 20)', 'US-NYcubl MS 1']
Partition 449: 4 : ['E-SAu Ms 2637', 'P-AR Res. Ms. 016', 'P-BRs Ms. 034', 'P-Ln Iluminado 084']
Partition 1001: 10 : ['B-Br Ms 10127-44', 'CH-Cobodmer C 0074', 'CH-SGs Cod 339', 'D-BAa Msc Lit 5', 'D-DS Hs 0545', 'D-LEu Ms Thomas 391', 'F-Pn Lat. 1136', 'F-Pn Lat. 17436', 'GB-Dru Cosin V.V.6', 'US-Baw W.11']
Partition 366: 8 : ['A-Wn Cod. 1812', 'H-Bn Clmae 172a, 172b', 'H-Efkö MS I. 1 a-b', 'H-Efkö MS I. 3. a', 'RO-Sb Ms. 759', 'SK-BRa EC Lad. 3, EL 18', 'TR-Itks 2429', 'TR-Itks 42']
Partition 391: 4 : ['F-Pn Lat. 13252', 'GB-Lbl printed book IB.6753 (Augsburg Antiphoner 1495, olim AA Impr. 1495)', 'SK-BRsa SNA 17', 'SK-BRsa SNA 67']
Partition 226: 4 : ['E-H Ms. 8 (ant. 6)', 'H-Bu lat. 119', 'HR-Hf Cod. F Nr. 6', 'PL-WRzno Rkp. 12025/IV']
Partition 505: 3 : ['D-Mbs Clm 02542', 'D-Sl HB I 246', 'F-CH Ms 0050']
Partition 218: 17 : ['A-KN Cod 588', 'A-KN Cod 73', 'CH-P 18', 'CH-SGs Cod 343', 'CZ-OLu M III 6', 'F-Pn Lat. 833', 'NL-Uu Hs. 0415', 'PL-Kl RL 1', 'PL-SAk 40', 'PL-WRu I F 413', 'PL-WRu I F 414', 'PL-WRu I F 416', 'PL-Wn Rps 12496 IV', 'PL-Wn rps 12722 V', 'SK-Bra BMI EC Lad.3 EL18', 'SK-Sk Graduale Scepusiense Nr.1', 'US-NYcub Western MS 097']
Partition 341: 24 : ['CH-ROM Ms. liturg. FiD 5', 'CH-SGs Cod 381', 'CZ-Bm A 7115', 'D-HEu Cod. Sal. X,007', 'D-KA Lichtenthal 002', 'D-KNd Ms 1001b', 'D-KWsr Drachenfels-Missale', 'E-Bbc M 1147', 'E-Mh Cód. 18', 'E-Mn Mss/1361', 'F-AS Ms 0437 (cat. 1011)', 'F-CA Ms 0060 (61)', 'F-LG Ms 0002 (17)', 'F-PR Ms 0012', 'F-Pa Ms 0197', 'F-Pn Lat. 17307', 'F-Pn Lat. 904', 'F-Pn Lat. 9441', 'F-Pn NAL 1235', 'F-Pn NAL 1414', 'F-Pn NAL 1890', 'PL-WRu I F 411', 'US-PHf Lewis E 158', 'V-CVbav Vat. lat. 4770']
Partition 191: 8 : ['D-Mbs Clm 02541', 'E-Bbc M 784', 'E-Mh Cód. 45', 'F-Pn Lat. 18010', 'F-Pn Lat. 9436', 'F-Togs Ms 001', 'F-VN Ms 0759', 'SK-BRnm MUS I 78']
Partition 383: 12 : ['A-Gu Ms 0807', 'CH-SGs Cod 342', 'CH-SGs Cod 374', 'CH-SGs Cod 375', 'CH-SGs Cod 376', 'CZ-R R 418', 'D-TRp Hs 187', 'D-W Cod Guelf Helmst 1008', 'F-Pa Ms 0135', 'F-Pn Lat. 1132', 'F-Pn Lat. 780', 'F-Pn Lat. 903']
Partition 1012: 6 : ['F-AUT Ms S 0012 (11)', 'F-CA Ms 0078 (79)', 'F-G Ms 84 (Ms. 395 Rés.)', 'F-Pn Lat. 1121', 'F-Pn Lat. 1134', 'F-Pn Lat. 909']
Partition 72: 5 : ['CZ-Pn XIII B 2', 'CZ-Pu XIII A 5c', 'E-Bbc M 889', 'E-Bbc Ms. 3180', 'F-SEm Ms 018']
Partition 762: 6 : ['F-CO Ms 0444 (217)', 'F-RS Ms 0221', 'F-RS Ms 0264', 'F-VAL Ms 0121', 'GB-Lbl Additional 18032', 'SK-BRl Rkp. 387']
Partition 1013: 2 : ['F-Pn Lat. 1135', 'GB-Ccc Ms 473']
Partition 648: 8 : ['E-L Ms 8', 'E-Mh Cod. 30', 'E-Tc 35.4', 'E-Tc 35.6', 'GB-Lbl Add MS 30844', 'GB-Lbl Add MS 30846', 'GB-Lbl Add MS 30851', 'I-VEcap Codex Veronensis LXXXIX']

Level 1:
10
Partition 32: 25 : ['A-Gu 29 (olim 38/8 f.)', 'A-KN CCl 1010', 'A-KN CCl 1017', 'A-Wda C-11', 'B-TOb 63 (olim V)', 'B-TOb 64 (olim IV)', 'CDN-Hsmu M2149.L4 1554', 'CH-Fco Ms. 2', 'CH-SGs 390', 'CZ-Pu VI.E.4c', 'CZ-Pu XIV.B.13', 'D-KNd 1161', 'D-Ma 12o Cmm 1', 'D-Mbs Clm 4303', 'H-Bu lat. 118', 'I-Ac 693', 'I-Ac 694', 'I-Ad 5', 'I-BV V 19', 'I-Nn vi. E. 20', 'I-VCd CLXX', 'PL-Kkar Ms.2 (rkp. Perg. 14)', 'PL-Kkar Ms.5 (rkp. Perg. 13)', 'US-Cn 24', 'V-CVbav lat. 8737']
Partition 31: 17 : ['A-Gu 30 (olim 38/9 f.)', 'A-KN CCl 1012', 'CZ-Bu R 387', 'CZ-Pn (Praha) XII A 21', 'CZ-Pu VI E 13', 'CZ-Pu XII C 3', 'CZ-Pu XIII C 4', 'CZ-Pu XIV C 20', 'CZ-R R 17', 'D-MZb D', 'D-W Cod. Guelf. 28 Helmst. (Heinemann-Nr. 31)', 'F-Pn Lat. 1030', 'F-Pn Latin 12601', 'F-Pn Latin 15182', 'SI-Lna 19 (olim 18)', 'SK-Bra BAI ECLad.3', 'SK-Sk 2']
Partition 59: 71 : ['A-KN CCl 1018', 'A-KN CCl 589', 'A-KR Schachtel VI/258', 'A-LIb 290 (olim 183; olim Gamma p 19)', 'A-SF XI 480', 'A-VOR 287 (olim XXIX)', 'A-Wda C-10', 'A-Wda D-4', 'A-Wn Cod. 1799**', 'A-Wn Cod. 1890', 'B-Gu Hs BKT.006', 'CDN-Mrb MS Medieval 0234', 'CH-E 611', 'CH-SGs 388', 'CH-SGs 391', 'CZ-Pu VI G 11', 'Cantus MA Impr. 1537', 'D-AAm G 20', 'D-B Mus. 40047', 'D-BAs Msc.Lit.25 (olim Ed.IV.11)', 'D-FUl Aa 55', 'D-KA Aug. LX', 'D-KNd 215', 'D-MZb C', 'D-Mbs Clm 4306', 'D-Sl HB.I.55', 'E-Bbc M 888', 'E-Bbc Ms. 619', 'E-Gs ms. 45 (olim Sant Feliu, 20)', 'E-SI MS 9', 'E-Tc 44.1', 'E-Tc 44.2', 'F-AI 44', 'F-AS 465 (CGM 893)', 'F-CA 38 (olim 40)', 'F-CA Impr. XVI C 4', 'F-Pn Lat. 17296', 'F-Pn Latin 1085', 'F-Pn Latin 1090', 'F-Pn Latin 12044', 'F-Pn Latin 1240', 'F-Pn NAL 1535', 'F-VAL 114', 'GB-AB 20541 E', 'GB-Cu Mm.ii.9', 'GB-Lbl Add MS 30848', 'GB-Lbl Add MS 30849', 'GB-Lbl Add MS 30850', 'GB-Ob MS. Canon. Liturg. 202', 'GB-Ob MS. Laud Misc. 284', 'GB-WO F. 160 (olim 1247) (facsimile)', 'GB-WO F. 160 (olim 1247) (with hymnal)', 'I-AO 6', 'I-BV V 20', 'I-Far s.c.', 'I-Fl Conv. sopp. 560', 'I-Lc 601', 'I-MZ 15/79', 'I-PCd cod. 65', 'I-Rv C.5', 'NL-Uu Ms. 406 (shelfmark 3 J 7)', 'NL-ZUa 6', 'NZ-Wt MSR-03', 'PL-KIk Ms. 1', 'PL-Kkar Ms.3 (rkp. Perg. 15)', 'PL-Klk 1', 'PL-WRu I F 401', 'PL-WRu Ms. R 503', 'TR-Itks Deissmann 42', 'US-Cai 1911.142b', 'V-CVbav San Pietro B.79']
Partition 35: 56 : ['A-KN CCl 1011', 'A-KN CCl 1013', 'A-KN CCl 1015', 'CDN-Ttfl MSS 09700', 'CZ-Pn XII A 24', 'CZ-Pn XV A 10', 'CZ-Pst DE I 7', 'CZ-Pu Pu XIV A 19', 'Cantus GOTTSCHALK', 'D-B Theol. Lat. Qu. 149', 'D-Kl Theol. quart 0015', 'D-MZb A', 'D-MZb B', 'D-Mbs Clm 02541', 'D-W Cod. Guelf. 29 Helmst. (Heinemann-Nr. 32)', 'DK-Kk Gl. Kgl. S. 3449 8o [02] II', 'E-BAR, s.s.', 'E-Bbc M 663', 'E-Bbc M 705', 'E-Bbc M 706', 'E-Bbc M 784', 'E-H Ms. 2', 'E-H Ms. 7 (ant. 5)', 'E-H Ms. 8 (ant. 6)', 'E-Mh Cód. 45', 'E-Mn MSS/10110', 'E-Tc 35.5', 'E-VI Mss. 113-114', 'F-LA Ms 240', 'F-Pn Lat. 18010', 'F-Pn Lat. 9436', 'F-Pn Lat. 9449', 'F-Pn Latin 15181', 'F-Pn NAL 1236', 'F-Pn NAL 1411', 'F-TOm 149', 'F-Togs Ms 001', 'F-VN Ms 0759', 'GB-Lbl Add MS 30847', 'H-Bu lat. 119', 'HR-Hf Cod. C Nr. 4', 'HR-Hf Cod. D Nr. 5', 'HR-Hf Cod. F Nr. 6', 'I-CHV s.c.', 'I-MC 542', 'NL-Uu Hs. 0062', 'PL-GD Mar. F 408', 'PL-PŁsem MsEPl 12', 'PL-STAb ms. 2', 'PL-WRzno Rkp. 12025/IV', 'PL-Wn  rps 12720 V', 'SI-Lna 18 (olim 17)', 'SK-BRnm MUS I 78', 'SK-BRsa SNA 2', 'SK-BRsa SNA 4', 'SK-Bra BAIII ECLad.6']
Partition 11: 17 : ['CZ-Pu VI G 3a', 'D-MZb E', 'D-Mbs Clm 4304', 'D-Mbs Clm 4305', 'E-Bbc Ms. 2322', 'E-SAu Ms 2637', 'F-Pn NAL 1412', 'F-R 248 (olim  A. 339)', 'H-Bu lat. 122', 'HR-Hf Cod. E Nr. 3', 'P-AR Res. Ms. 016', 'P-AR Res. Ms. 025', 'P-BRs Ms. 028', 'P-BRs Ms. 034', 'P-Ln Iluminado 084', 'PL-Kkar Ms.1 (rkp. Perg. 12)', 'PL-PŁsem MsEPl 12']
Partition 38: 4 : ['P-AR Res. Ms. 021', 'P-BRs Ms. 032', 'P-EVpc 000', 'P-Ln RES. 253 P.']
Partition 36: 40 : ['Antifonario s.s.', 'B-Br Ms 10127-44', 'CH-Cobodmer C 0074', 'CH-SGs Cod 339', 'CZ-Pn XIII B 2', 'CZ-Pu XII E 15c', 'CZ-Pu XIII A 5c', 'D-BAa Msc Lit 5', 'D-DS Hs 0545', 'D-LEu Ms Thomas 391', 'D-Mbs Clm 02542', 'D-Sl HB I 246', 'E-Bbc M 785', 'E-Bbc M 889', 'E-Bbc Ms. 3180', 'E-E L. III. 3.', 'E-E L. III. 4.', 'E-H Ms. 9 (ant. 25)', 'E-LUc s.s.', 'F-AUT Ms S 0012 (11)', 'F-CA Ms 0078 (79)', 'F-CH Ms 0050', 'F-CO Ms 0444 (217)', 'F-G Ms 84 (Ms. 395 Rés.)', 'F-Pn Lat. 1121', 'F-Pn Lat. 1134', 'F-Pn Lat. 1135', 'F-Pn Lat. 1136', 'F-Pn Lat. 17436', 'F-Pn Lat. 909', 'F-RS Ms 0221', 'F-RS Ms 0264', 'F-SEm Ms 018', 'F-VAL Ms 0121', 'GB-Ccc Ms 473', 'GB-Dru Cosin V.V.6', 'GB-Lbl Add MS 30845', 'GB-Lbl Additional 18032', 'SK-BRl Rkp. 387', 'US-Baw W.11']
Partition 66: 26 : ['CH-SGs Cod 378', 'CH-SGs Cod 380', 'CH-SGs Cod 484', 'E-Bbc M 662', 'E-L Ms 8', 'E-MO Ms. 72', 'E-Mh Cod. 30', 'E-SA 6', 'E-Tc 35.4', 'E-Tc 35.6', 'F-LA Ms 263', 'F-Pn Lat. 10510', 'F-Pn Lat. 1118', 'F-Pn Lat. 13252', 'F-Pn Lat. 9448', 'F-SO 596', 'GB-Lbl Add MS 30844', 'GB-Lbl Add MS 30846', 'GB-Lbl Add MS 30851', 'GB-Lbl printed book IB.6753 (Augsburg Antiphoner 1495, olim AA Impr. 1495)', 'H-Bu lat. 121', 'I-VEcap Codex Veronensis LXXXIX', 'PL-Kkar Ms.4 (rkp. Perg. 20)', 'SK-BRsa SNA 17', 'SK-BRsa SNA 67', 'US-NYcubl MS 1']
Partition 7: 99 : ['A-Gu Ms 0807', 'A-KN Cod 588', 'A-KN Cod 73', 'B-Br Ms II 3823', 'CH-E Codex 121', 'CH-P 18', 'CH-ROM Ms. liturg. FiD 5', 'CH-SGs Cod 338', 'CH-SGs Cod 340', 'CH-SGs Cod 342', 'CH-SGs Cod 343', 'CH-SGs Cod 374', 'CH-SGs Cod 375', 'CH-SGs Cod 376', 'CH-SGs Cod 381', 'CH-SGv VadSlg Ms 0295', 'CZ-Bm A 7115', 'CZ-OLu M III 6', 'CZ-Pn XIV D 12', 'CZ-R R 396', 'CZ-R R 418', 'D-B Ms mus 40078', 'D-BAa Msc Lit 6', 'D-BAa Msc Lit 7', 'D-Ful Aa 0006', 'D-HEu Cod. Sal. X,007', 'D-KA Lichtenthal 002', 'D-KNd Ms 1001b', 'D-KWsr Drachenfels-Missale', 'D-Mbs Clm 03005', 'D-Mbs Clm 14965b', 'D-TRp Hs 187', 'D-W Cod Guelf Helmst 1008', 'E-Bbc M 1147', 'E-Bbc M 648', 'E-Bbc Ms. 1805', 'E-Mh Cód. 18', 'E-Mh Cód. 51', 'E-Mn Mss/1361', 'F-AI Ms 0044', 'F-AN Ms 0091', 'F-AS Ms 0437 (cat. 1011)', 'F-AUT Ms S 0010 (8*)', 'F-CA Ms 0060 (61)', 'F-CA Ms 0061 (62)', 'F-CA Ms 0075 (76)', 'F-CHRm Ms 0047 (40)', 'F-Collection privée Mont-Renaud', 'F-LA Ms 118', 'F-LA Ms 236', 'F-LA Ms 239', 'F-LG Ms 0002 (17)', 'F-NS Ms 0004', 'F-PR Ms 0012', 'F-Pa Ms 0135', 'F-Pa Ms 0197', 'F-Pm Ms 0384', 'F-Pn Lat. 1087', 'F-Pn Lat. 1132', 'F-Pn Lat. 12050', 'F-Pn Lat. 12584', 'F-Pn Lat. 17307', 'F-Pn Lat. 2291', 'F-Pn Lat. 780', 'F-Pn Lat. 833', 'F-Pn Lat. 903', 'F-Pn Lat. 904', 'F-Pn Lat. 9439', 'F-Pn Lat. 9441', 'F-Pn NAL 1235', 'F-Pn NAL 1414', 'F-Pn NAL 1669', 'F-Pn NAL 1890', 'F-SOM Ms 0252', 'GB-Lbl Egerton 857', 'GB-Lbl Harley 4951', 'I-BGc MA 150 (Psi III.8)', 'I-BGc MA 239 (Gamma III.18)', 'I-BV 34', 'I-Bc Q 09', 'I-Tn G.V.20', 'NL-Uu Hs. 0415', 'PL-Kl RL 1', 'PL-SAk 40', 'PL-WRu I F 411', 'PL-WRu I F 413', 'PL-WRu I F 414', 'PL-WRu I F 416', 'PL-Wn Rps 12496 IV', 'PL-Wn rps 12722 V', 'Reconstitution Sacramentaire de Tours (TU1)', 'SK-Bra BMI EC Lad.3 EL18', 'SK-Sk Graduale Scepusiense Nr.1', 'US-NYcub Western MS 097', 'US-PHf Lewis E 158', 'V-CVbav Archivio di San Pietro F.22', 'V-CVbav Ross.0076', 'V-CVbav Vat. lat. 4770', 'V-CVbav Vat. lat. 5319']
Partition 17: 8 : ['A-Wn Cod. 1812', 'H-Bn Clmae 172a, 172b', 'H-Efkö MS I. 1 a-b', 'H-Efkö MS I. 3. a', 'RO-Sb Ms. 759', 'SK-BRa EC Lad. 3, EL 18', 'TR-Itks 2429', 'TR-Itks 42']

Level 2:
3

In [84]:
importlib.reload(utils)
source_vs_feast_df = utils.get_sigla_vs_feast_partitions(corpus, sigla_partitions[1], feasts_partitions[1])

In [86]:
source_vs_feast_df.head(10)

,source_partition,n_of_sources,f_p_46,f_p_49,f_p_21,f_p_30,f_p_50,f_p_38
0,8,86,0.020,0.312,0.229,0.221,0.040,0.0
1,51,54,0.036,0.004,0.002,0.197,0.029,0.0
2,1,32,0.068,0.390,0.267,0.465,0.095,0.0
3,34,26,0.002,0.143,0.112,0.059,0.022,0.0
4,28,71,0.122,0.511,0.037,0.497,0.002,0.0
5,25,8,0.016,0.098,0.066,0.109,0.019,0.0
6,3,56,0.108,0.347,0.028,0.328,0.005,0.0
7,55,30,0.013,0.217,0.013,0.132,0.008,0.0

In [87]:
source_vs_feast_df.to_csv(f'visual/nested_dc_sbm_source_vs_feast_partitions{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}_levels_1_1.csv', index=False)

In [ ]:
save_path = f"partitions/nested_dc_sbm_partitions_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}.csv"
df_partitions = utils.save_nested_partitions_csv(sigla_partitions, save_path)
df_partitions.head()

Saved nested partitions to partitions/nested_dc_sbm_partitions_20_f_reducted_50_min_600.csv

,siglum,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,...,level2_new,level3_new,level4_new,level5_new,level6_new,level7_new,level8_new,level9_new,level10_new,level11_new
0,A-Gu 29 (olim 38/8 f.),645,32,11,0,2,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,CZ-Pu VI.E.4c,645,32,11,0,2,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,CZ-Pu XIV.B.13,645,32,11,0,2,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,A-KN CCl 1010,645,32,11,0,2,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,A-KN CCl 1017,645,32,11,0,2,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [118]:
for col in df_partitions.columns:
    if col.startswith("level") and col.endswith("_new"):
        print(col, df_partitions[col].nunique())

level0_new 38
level1_new 10
level2_new 3
level3_new 2
level4_new 1
level5_new 1
level6_new 1
level7_new 1
level8_new 1
level9_new 1
level10_new 1
level11_new 1

In [119]:
COLS_4 = ["siglum", "level0_new", "level1_new", "level2_new", "level3_new"]

In [120]:
importlib.reload(utils)
utils.get_dendro_json(save_path, columns=COLS_4, output_path=f"visual/nested_dc_sbm_dendro_{N_INIT}_f_reducted_{MIN_CID_PER_FEAST}_min_{MIN_CHANTS_PER_SOURCE}_cols4.json")